import Link from 'next/link';
import { notFound } from 'next/navigation';
import { JsonLd } from '../../../components/JsonLd';
import { GROUPS, TYPES, TYPE_CODES } from '../../../data/types';
import { breadcrumbJsonLd, pageMetadata } from '../../../lib/metadata';
import { isLocale, localePath } from '../../../lib/site';
import { TypesGuideDiscovery } from '../../../components/GuideDiscovery';

const COPY = {
  en: { title: 'Explore the 16 personality types', body: 'Use these guides as a language for reflection, not as limits on what you can become.', read: 'Read the guide', groups: { Analysts: 'Analysts', Diplomats: 'Diplomats', Sentinels: 'Sentinels', Explorers: 'Explorers' } },
  hi: { title: '16 पर्सनैलिटी टाइप्स देखें', body: 'इन गाइड्स को आत्मचिंतन की भाषा की तरह देखें, अपनी सीमाओं की तरह नहीं।', read: 'गाइड पढ़ें', groups: { Analysts: 'विश्लेषक', Diplomats: 'कूटनीतिज्ञ', Sentinels: 'संरक्षक', Explorers: 'अन्वेषक' } },
  fr: { title: 'Découvrir les 16 types de personnalité', body: 'Ces guides offrent un langage pour réfléchir à soi, pas des limites à ce que vous pouvez devenir.', read: 'Lire le guide', groups: { Analysts: 'Analystes', Diplomats: 'Diplomates', Sentinels: 'Sentinelles', Explorers: 'Explorateurs' } },
  ja: { title: '16のパーソナリティタイプを知る', body: 'これらのガイドは、自分を考えるための言葉です。可能性を決めつけるものではありません。', read: 'ガイドを読む', groups: { Analysts: '分析家', Diplomats: '外交官', Sentinels: '番人', Explorers: '探検家' } },
};
const NAMES = { fr: { INTJ: 'L’Architecte', INTP: 'Le Logicien', ENTJ: 'Le Commandant', ENTP: 'L’Innovateur', INFJ: 'L’Avocat', INFP: 'Le Médiateur', ENFJ: 'Le Protagoniste', ENFP: 'L’Inspirateur', ISTJ: 'Le Logisticien', ISFJ: 'Le Défenseur', ESTJ: 'Le Directeur', ESFJ: 'Le Consul', ISTP: 'Le Virtuose', ISFP: 'L’Aventurier', ESTP: 'L’Entrepreneur', ESFP: 'L’Amuseur' }, ja: { INTJ: '建築家', INTP: '論理学者', ENTJ: '指揮官', ENTP: '討論者', INFJ: '提唱者', INFP: '仲介者', ENFJ: '主人公', ENFP: '運動家', ISTJ: '管理者', ISFJ: '擁護者', ESTJ: '幹部', ESFJ: '領事', ISTP: '巨匠', ISFP: '冒険家', ESTP: '起業家', ESFP: 'エンターテイナー' } };
const HEADLINES = { fr: { INTJ: 'Un stratège discret, attentif aux systèmes et au temps long.', INTP: 'Un esprit curieux qui aime comprendre avant de conclure.', ENTJ: 'Un organisateur ambitieux, tourné vers l’action et la direction.', ENTP: 'Un explorateur d’idées qui aime remettre les évidences en question.', INFJ: 'Un observateur idéaliste, sensible aux personnes et au sens.', INFP: 'Un créatif guidé par ses valeurs et son monde intérieur.', ENFJ: 'Un rassembleur attentif qui encourage la progression des autres.', ENFP: 'Un enthousiaste imaginatif qui voit des possibilités partout.', ISTJ: 'Un repère fiable, méthodique et attentif à ses engagements.', ISFJ: 'Un soutien discret qui veille concrètement sur les autres.', ESTJ: 'Un responsable pragmatique qui transforme les plans en résultats.', ESFJ: 'Un créateur de liens chaleureux, attentif au groupe.', ISTP: 'Un expérimentateur calme qui apprend en manipulant et en observant.', ISFP: 'Un créatif réservé, sensible à l’instant et à l’authenticité.', ESTP: 'Un acteur direct qui s’adapte vite à ce qui se présente.', ESFP: 'Un présence expressive qui apporte énergie et convivialité.' }, ja: { INTJ: '静かに全体像を捉え、長期的な戦略を考える人。', INTP: '結論を急がず、仕組みを深く理解しようとする人。', ENTJ: '目標に向かって人や資源をまとめ、前に進める人。', ENTP: '当たり前を問い直し、新しい発想を広げる人。', INFJ: '人と意味のつながりを丁寧に見つめる理想家。', INFP: '内なる価値観と想像力を大切にする創造者。', ENFJ: '周囲の成長を後押しし、協力を育てる人。', ENFP: '人や状況に眠る可能性を見つける熱心な人。', ISTJ: '責任を重んじ、着実に約束を果たす人。', ISFJ: 'さりげない気配りで、人を具体的に支える人。', ESTJ: '実務的に整理し、計画を成果へつなげる人。', ESFJ: '人とのつながりを育て、場をあたためる人。', ISTP: '観察と試行を通じて、実践的に理解する人。', ISFP: '自分らしさと今この瞬間を大切にする表現者。', ESTP: '目の前の状況に素早く対応し、行動する人。', ESFP: '表現力と親しみやすさで、場に活気をもたらす人。' } };
export async function generateMetadata({ params }) { const { locale } = await params; if (!isLocale(locale)) return {}; const c = COPY[locale]; return pageMetadata({ locale, path: 'types', title: c.title, description: c.body }); }
export default async function TypesPage({ params }) {
  const { locale } = await params;
  if (!isLocale(locale)) notFound();
  const c = COPY[locale];
  return <><JsonLd data={{ '@context': 'https://schema.org', '@graph': [breadcrumbJsonLd(locale, [{ name: 'KalQLater' }, { name: c.title, path: 'types' }]), { '@type': 'CollectionPage', name: c.title, description: c.body, inLanguage: locale }] }} /><main className="mx-auto max-w-7xl px-4 py-12 sm:px-6 lg:py-16"><p className="section-kicker">KalQLater</p><h1 className="display-font mt-3 text-4xl text-brand-ink sm:text-6xl">{c.title}</h1><p className="mt-5 max-w-2xl text-lg leading-relaxed text-brand-subtle">{c.body}</p><div className="mt-12 space-y-14">{GROUPS.map((group) => <section key={group}><h2 className="section-kicker">{c.groups[group]}</h2><div className="mt-5 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{TYPE_CODES.filter((code) => TYPES[code].group === group).map((code) => { const type = TYPES[code]; const info = locale === 'hi' ? type.hi : type.en; const title = NAMES[locale]?.[code] || info.nickname; const headline = HEADLINES[locale]?.[code] || info.headline; return <Link key={code} href={localePath(locale, `personality/${code.toLowerCase()}`)} className="group relative overflow-hidden rounded-3xl border border-brand-line bg-white p-6 transition hover:-translate-y-1 hover:shadow-lg"><span aria-hidden="true" className="absolute -right-10 -top-10 h-28 w-28 rounded-full opacity-20 blur-xl" style={{ background: type.color }} /><p className="text-xs font-bold tracking-[.2em] text-brand-teal">{code}</p><h3 className="display-font mt-3 text-2xl text-brand-ink">{title}</h3><p className="mt-3 min-h-16 text-sm leading-relaxed text-brand-subtle">{headline}</p><span className="mt-5 inline-flex text-sm font-semibold text-brand-teal">{c.read} <span aria-hidden="true">→</span></span></Link>; })}</div></section>)}</div>{locale === 'en' ? <TypesGuideDiscovery /> : null}</main></>;
}
