import Link from 'next/link';

import { JsonLd } from './JsonLd';
import { localePath } from '../lib/site';

/** Renders the authored rich Compare contract without affecting legacy locale packages. */
export function LocalizedCompareContent({ locale, page }) {
  const { fields } = page;
  const { editorial } = fields;
  const ja = locale === 'ja';
  const title = fields.ui || fields.seo?.title;
  const faqSchema = { '@context': 'https://schema.org', '@type': 'FAQPage', inLanguage: locale, mainEntity: editorial.faqs.map(({ question, answer }) => ({ '@type': 'Question', name: question, acceptedAnswer: { '@type': 'Answer', text: answer } })) };
  const labels = ja ? { sections: '比較を深める視点', faq: 'よくある質問', related: '関連コンテンツ' } : { sections: 'Pour approfondir cette comparaison', faq: 'Questions fréquentes', related: 'Pour aller plus loin' };
  return <><JsonLd data={faqSchema} /><main className="mx-auto max-w-7xl px-4 py-10 sm:px-6 sm:py-16"><nav aria-label="KalQLater" className="text-sm text-brand-subtle"><Link href={localePath(locale)}>KalQLater</Link><span aria-hidden="true"> / </span><Link href={localePath(locale, 'compare')}>{ja ? 'タイプ比較' : 'Comparer les personnalités'}</Link><span aria-hidden="true"> / </span>{fields.jsonLd?.breadcrumb || title}</nav><header className="relative mt-6 overflow-hidden rounded-[2rem] bg-brand-ink px-7 py-10 text-white shadow-[0_24px_70px_rgba(45,40,37,.16)] sm:px-10 sm:py-14"><span aria-hidden="true" className="absolute -right-16 -top-16 h-56 w-56 rounded-full bg-brand-teal/35 blur-3xl" /><div className="relative max-w-4xl"><p className="section-kicker text-brand-sand">{fields.eyebrow}</p><h1 className="display-font mt-4 text-4xl leading-tight sm:text-6xl">{title}</h1><p className="mt-5 text-lg leading-relaxed text-white/85">{fields.intro}</p><p className="mt-5 max-w-3xl text-sm leading-relaxed text-white/70">{fields.helper}</p></div></header><section className="mt-12"><p className="section-kicker">{labels.sections}</p><div className="mt-5 grid gap-5 lg:grid-cols-2">{editorial.sections.map(({ id, title: sectionTitle, body }, index) => <article key={id} className={`rounded-[1.75rem] p-6 sm:p-8 ${index % 4 === 1 ? 'bg-brand-cream' : index % 4 === 2 ? 'bg-brand-sand/25' : index % 4 === 3 ? 'bg-brand-teal/5' : 'border border-brand-line bg-white'}`}><p className="section-kicker">{String(index + 1).padStart(2, '0')}</p><h2 className="display-font mt-3 text-2xl text-brand-ink">{sectionTitle}</h2><p className="mt-4 leading-relaxed text-brand-subtle">{body}</p></article>)}</div></section><section className="mt-14 rounded-[2rem] border border-brand-line bg-white p-7 sm:p-9"><p className="section-kicker">{labels.faq}</p><div className="mt-6 space-y-3">{editorial.faqs.map(({ question, answer }) => <details key={question} className="rounded-2xl bg-brand-cream p-5"><summary className="cursor-pointer font-semibold text-brand-ink focus:outline-none focus-visible:ring-2 focus-visible:ring-brand-teal">{question}</summary><p className="mt-4 leading-relaxed text-brand-subtle">{answer}</p></details>)}</div></section><section className="mt-14 rounded-[2rem] bg-brand-sand/25 p-7 sm:p-9"><p className="section-kicker">{labels.related}</p><div className="mt-6 flex flex-wrap gap-3">{editorial.relatedLinks.map(({ label, href }) => <Link key={href} href={href} className="button-secondary">{label}<span aria-hidden="true">→</span></Link>)}</div></section></main></>;
}
