import Link from 'next/link';
import { notFound } from 'next/navigation';
import { JsonLd } from '../../../../components/JsonLd';
import { breadcrumbJsonLd, pageMetadata } from '../../../../lib/metadata';
import { isLocale, localePath, productionAppUrl } from '../../../../lib/site';
import { personalityProfile, TYPE_ORDER, typeFaq, typeFromSlug } from '../../../../lib/personality';
import { pairSlug } from '../../../../lib/comparisons';

export function generateStaticParams() { return ['en', 'hi'].flatMap((locale) => TYPE_ORDER.map((code) => ({ locale, type: code.toLowerCase() }))); }
export const dynamicParams = false;

export async function generateMetadata({ params }) {
  const { locale, type } = await params; const activeLocale = isLocale(locale) ? locale : 'en'; const code = typeFromSlug(type); const profile = code && personalityProfile(code, activeLocale);
  if (!profile) return {};
  return pageMetadata({ locale: activeLocale, path: `personality/${profile.slug}`, title: `${profile.code} — ${profile.displayName}`, description: profile.shortSummary });
}

export default async function PersonalityPage({ params }) {
  const { locale, type } = await params; if (!isLocale(locale)) notFound(); const code = typeFromSlug(type); const profile = code && personalityProfile(code, locale); if (!profile) notFound();
  const hi = locale === 'hi'; const faq = typeFaq(profile, locale); const compareHref = localePath(locale, `compare/${pairSlug(code, profile.relatedTypes[0])}`);
  const labels = hi ? { traits: 'मुख्य विशेषताएँ', strengths: 'ताकत', growth: 'विकास के क्षेत्र', work: 'काम और करियर', communication: 'संवाद शैली', decisions: 'निर्णय लेने का तरीका', leadership: 'नेतृत्व शैली', learning: 'सीखने का अभ्यास', relationships: 'रिश्ते', stress: 'तनाव और विकास', tips: 'व्यावहारिक सुझाव', faq: 'अक्सर पूछे जाने वाले प्रश्न', related: 'संबंधित व्यक्तित्व', test: 'व्यक्तित्व टेस्ट दें', compare: 'तुलना देखें', disclaimer: 'यह आत्मचिंतन का साधन है, नैदानिक निदान या भर्ती निर्णय नहीं।' } : { traits: 'Core traits', strengths: 'Strengths', growth: 'Growth areas', work: 'Work and career themes', communication: 'Communication style', decisions: 'Decision-making approach', leadership: 'Leadership style', learning: 'Learning through practice', relationships: 'Relationships', stress: 'Stress and growth', tips: 'Practical development tips', faq: 'Frequently asked questions', related: 'Related personality types', test: 'Take the personality test', compare: 'Explore a comparison', disclaimer: 'This is a reflection tool, not a clinical diagnosis or hiring decision.' };
  const jsonLd = { '@context': 'https://schema.org', '@graph': [breadcrumbJsonLd(locale, [{ name: 'KalQLater' }, { name: hi ? 'व्यक्तित्व' : 'Personality', path: 'personality' }, { name: `${profile.code} ${profile.displayName}`, path: `personality/${profile.slug}` }]), { '@type': 'FAQPage', mainEntity: faq.map((item) => ({ '@type': 'Question', name: item.q, acceptedAnswer: { '@type': 'Answer', text: item.a } })) }] };
  return <><JsonLd data={jsonLd} /><article className="mx-auto max-w-5xl px-4 py-12 sm:px-6 lg:px-8"><header className="rounded-[2rem] border border-brand-line bg-white p-7 sm:p-10" style={{ borderTopColor: profile.color, borderTopWidth: 5 }}><p className="text-xs font-semibold uppercase tracking-[.22em] text-brand-teal">{profile.group}</p><h1 className="display-font mt-3 text-4xl sm:text-6xl"><span style={{ color: profile.color }}>{profile.code}</span> · {profile.displayName}</h1><p className="mt-5 max-w-3xl text-xl leading-relaxed text-brand-subtle">{profile.shortSummary}</p><p className="mt-6 rounded-2xl bg-brand-cream p-4 text-sm text-brand-subtle">{labels.disclaimer}</p></header><Section title={hi ? 'सारांश' : 'Summary'}><p>{profile.overview}</p></Section><Grid sections={[[labels.traits, profile.coreTraits], [labels.strengths, profile.strengths], [labels.growth, profile.growthAreas], [labels.stress, profile.stressPatterns]]} /><Section title={labels.work}><List items={profile.workStyle} /></Section><Grid sections={[[labels.communication, [profile.communication?.summary, profile.communication?.preferred, profile.communication?.conflict, profile.communication?.listening].filter(Boolean)], [labels.decisions, [profile.leadership?.summary]], [labels.leadership, [profile.leadership?.style, ...(profile.leadership?.strengths || [])]], [labels.learning, [profile.learningStyle]]]} /><Section title={labels.relationships}><p>{profile.relationshipStyle}</p></Section><Section title={labels.tips}><List items={profile.developmentTips} /></Section><Section title={labels.faq}><div className="space-y-4">{faq.map((item) => <details key={item.q} className="rounded-2xl border border-brand-line bg-white p-5"><summary className="cursor-pointer font-semibold">{item.q}</summary><p className="mt-3 leading-relaxed text-brand-subtle">{item.a}</p></details>)}</div></Section><Section title={labels.related}><div className="flex flex-wrap gap-3">{profile.relatedTypes.map((item) => <Link key={item} href={localePath(locale, `personality/${item.toLowerCase()}`)} className="rounded-full border border-brand-line bg-white px-4 py-2 font-semibold hover:border-brand-teal">{item}</Link>)}</div></Section><div className="mt-10 flex flex-wrap gap-3"><a href={productionAppUrl('/test')} className="rounded-full bg-brand-teal px-6 py-3 font-semibold text-white">{labels.test}</a><Link href={compareHref} className="rounded-full border border-brand-line bg-white px-6 py-3 font-semibold">{labels.compare}</Link></div></article></>;
}
function Section({ title, children }) { return <section className="mt-8"><h2 className="display-font text-3xl">{title}</h2><div className="mt-4 leading-relaxed text-brand-subtle">{children}</div></section>; }
function List({ items }) { return <ul className="grid gap-2 sm:grid-cols-2">{items.map((item) => <li key={item} className="rounded-2xl bg-brand-cream px-4 py-3">{item}</li>)}</ul>; }
function Grid({ sections }) { return <div className="mt-8 grid gap-5 md:grid-cols-2">{sections.map(([title, items]) => <section key={title} className="rounded-[1.75rem] border border-brand-line bg-white p-6"><h2 className="display-font text-2xl">{title}</h2><div className="mt-4"><List items={items} /></div></section>)}</div>; }
