import Link from 'next/link';
import { notFound } from 'next/navigation';
import { JsonLd } from '../../../../components/JsonLd';
import { breadcrumbJsonLd, pageMetadata } from '../../../../lib/metadata';
import { isLocale, localePath, productionAppUrl } from '../../../../lib/site';
import { personalityProfile, TYPE_ORDER, typeFaq, typeFromSlug } from '../../../../lib/personality';
import { pairSlug } from '../../../../lib/comparisons';

export function generateStaticParams() { return ['en', 'hi'].flatMap((locale) => TYPE_ORDER.map((code) => ({ locale, type: code.toLowerCase() }))); }
export const dynamicParams = false;
export async function generateMetadata({ params }) { const { locale, type } = await params; const code = typeFromSlug(type); const profile = code && personalityProfile(code, isLocale(locale) ? locale : 'en'); return profile ? pageMetadata({ locale, path: `personality/${profile.slug}`, title: `${profile.code} — ${profile.displayName}`, description: profile.shortSummary }) : {}; }

const COPY = { en: { pattern: 'Core pattern', glance: 'Personality at a glance', strengths: 'Signature strengths', growth: 'Growth edges', communication: 'How this type communicates', decisions: 'Decision pathway', learning: 'Learning and problem-solving', relationships: 'Relationships and connection', leadership: 'Leadership and contribution', stress: 'Stress and recovery', career: 'Career preview', plan: 'A practical growth plan', misconceptions: 'Type misconceptions', related: 'Explore related dynamics', faq: 'Questions worth asking', final: 'Understand the pattern. Choose what to do with it.', test: 'Take the test', careers: 'Explore Career Guide', insights: 'Communication Insights', jobs: 'Browse jobs', join: 'Join the Community', compare: 'Compare personalities', disclaimer: 'This is a reflection tool—not a clinical diagnosis, ability measure, or hiring decision.', lenses: ['Attention', 'Information', 'Decisions', 'Lifestyle'] }, hi: { pattern: 'मूल पैटर्न', glance: 'एक नज़र में व्यक्तित्व', strengths: 'विशिष्ट ताकतें', growth: 'विकास के क्षेत्र', communication: 'इस प्रकार का संवाद', decisions: 'निर्णय पथ', learning: 'सीखना और समस्या-समाधान', relationships: 'रिश्ते और जुड़ाव', leadership: 'नेतृत्व और योगदान', stress: 'तनाव और रिकवरी', career: 'करियर झलक', plan: 'व्यावहारिक विकास योजना', misconceptions: 'प्रचलित गलतफहमियाँ', related: 'संबंधित समझ देखें', faq: 'सोचने योग्य प्रश्न', final: 'पैटर्न समझें। उसके साथ क्या करना है, चुनें।', test: 'टेस्ट दें', careers: 'करियर गाइड देखें', insights: 'कम्युनिकेशन इनसाइट्स', jobs: 'जॉब्स देखें', join: 'कम्युनिटी से जुड़ें', compare: 'पर्सनैलिटी तुलना करें', disclaimer: 'यह आत्मचिंतन का साधन है—न नैदानिक निदान, क्षमता माप या भर्ती निर्णय।', lenses: ['ध्यान', 'जानकारी', 'निर्णय', 'जीवनशैली'] } };

export default async function PersonalityPage({ params }) {
  const { locale, type } = await params; if (!isLocale(locale)) notFound(); const code = typeFromSlug(type); const p = code && personalityProfile(code, locale); if (!p) notFound();
  const c = COPY[locale], hi = locale === 'hi', faq = typeFaq(p, locale), compareTypes = p.relatedTypes.length ? p.relatedTypes : TYPE_ORDER.filter(x => x !== code).slice(0, 3);
  const jsonLd = { '@context': 'https://schema.org', '@graph': [breadcrumbJsonLd(locale, [{ name: 'KalQLater' }, { name: hi ? 'व्यक्तित्व' : 'Personality', path: 'personality' }, { name: `${p.code} ${p.displayName}`, path: `personality/${p.slug}` }]), { '@type': 'FAQPage', mainEntity: faq.map(item => ({ '@type': 'Question', name: item.q, acceptedAnswer: { '@type': 'Answer', text: item.a } })) }] };
  const lenses = [p.coreTraits[0], p.coreTraits[1], p.leadership?.style || p.coreTraits[2], p.workStyle[0]].filter(Boolean);
  const plan = hi ? ['बार-बार दिखने वाला पैटर्न नोट करें', 'एक वैकल्पिक प्रतिक्रिया आजमाएं', 'उपयोगी फीडबैक मांगें', 'असुविधाजनक कौशल का अभ्यास करें', 'देखें क्या बदला'] : ['Notice one recurring pattern', 'Test one alternative response', 'Request useful feedback', 'Practise one uncomfortable skill', 'Review what changed'];
  return <><JsonLd data={jsonLd} /><main className="mx-auto max-w-7xl px-4 py-8 sm:px-6 lg:px-8 lg:py-12">
    <nav aria-label="Breadcrumb" className="text-sm text-brand-subtle"><Link href={`/${locale}`}>KalQLater</Link><span aria-hidden="true"> / </span>{p.code}</nav>
    <header className="relative mt-5 overflow-hidden rounded-[2rem] bg-brand-ink px-7 py-10 text-white shadow-[0_24px_70px_rgba(45,40,37,.2)] sm:px-10 lg:px-14"><div className="relative grid items-center gap-8 lg:grid-cols-[1.15fr_.85fr]"><div><p className="section-kicker text-brand-sand">{p.group}</p><p className="mt-5 text-sm font-bold tracking-[.22em] text-brand-sand">{p.code}</p><h1 className="display-font mt-2 text-4xl sm:text-6xl">{p.displayName}</h1><p className="mt-4 max-w-2xl text-xl leading-relaxed text-white/85">{p.shortSummary}</p><p className="mt-5 max-w-2xl border-l-2 border-brand-sand pl-4 text-sm text-white/70">{c.disclaimer}</p><div className="mt-7 flex flex-wrap gap-3"><a href={productionAppUrl('/test')} className="button-light">{c.test}</a><Link href={localePath(locale, `personality/${p.slug}/careers`)} className="button-dark-outline">{c.careers}</Link><Link href={localePath(locale, 'insights/communication')} className="button-dark-outline">{c.insights}</Link></div></div><TypeVisual code={p.code} color={p.color} /></div></header>
    <section className="mt-12 grid gap-7 lg:grid-cols-[.85fr_1.15fr]"><div><Section eyebrow="01" title={c.pattern} body={p.overview} /></div><div className="rounded-[2rem] bg-brand-cream p-6 sm:p-8"><Section eyebrow="KalQLater" title={c.glance} /><div className="mt-6 grid gap-3 sm:grid-cols-2">{lenses.map((item, i) => <article key={item} className="rounded-2xl bg-white p-4"><p className="text-xs font-bold uppercase tracking-wide text-brand-teal">{c.lenses[i]}</p><p className="mt-2 font-semibold text-brand-ink">{item}</p><p className="mt-2 text-sm text-brand-subtle">{hi ? 'भूमिका और संदर्भ के साथ बदल सकता है।' : 'Can vary with role and context.'}</p></article>)}</div></div></section>
    <section className="mt-14"><Section eyebrow="02" title={c.strengths} /><div className="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{p.strengths.slice(0, 6).map((item, i) => <Insight key={item} index={i} title={item} body={hi ? 'यह ताकत वास्तविक काम, रिश्तों और योगदान में उपयोगी हो सकती है।' : 'This strength may be useful in real work, relationships, and contribution.'} note={hi ? 'अति-उपयोग से बचें: संदर्भ और फीडबैक देखें।' : 'Watch for overuse: keep context and feedback close.'} />)}</div></section>
    <section className="mt-14 grid gap-7 lg:grid-cols-2"><div className="rounded-[2rem] bg-brand-sand/30 p-7 sm:p-9"><Section eyebrow="03" title={c.growth} />{p.growthAreas.slice(0, 5).map((item) => <div key={item} className="mt-4 border-l-2 border-brand-plum pl-4"><h3 className="font-semibold text-brand-ink">{item}</h3><p className="mt-1 text-sm text-brand-subtle">{hi ? 'छोटा सुधार: इसे किसी भरोसेमंद व्यक्ति से जाँचें और एक व्यावहारिक प्रयोग चुनें।' : 'Small corrective: check it with someone you trust and choose one practical experiment.'}</p></div>)}</div><div className="rounded-[2rem] border border-brand-line bg-white p-7 sm:p-9"><Section eyebrow="04" title={c.communication} /><Flow title={p.communication?.summary} items={[p.communication?.preferred, p.communication?.listening, p.communication?.conflict].filter(Boolean)} /><div className="mt-5 grid gap-3 sm:grid-cols-2"><Callout title={hi ? 'आजमाएं' : 'Try this'} text={p.communication?.tips?.[0] || p.developmentTips?.[0]} tone="teal" /><Callout title={hi ? 'बचें' : 'Avoid this'} text={p.communication?.conflict || p.growthAreas[0]} tone="plum" /></div></div></section>
    <section className="mt-14 grid gap-7 lg:grid-cols-2"><div className="rounded-[2rem] bg-brand-teal p-7 text-white sm:p-9"><Section eyebrow="05" title={c.decisions} body={p.leadership?.summary} light /><ol className="mt-6 space-y-3">{[p.coreTraits[0], p.coreTraits[1], p.growthAreas[0], p.developmentTips?.[0]].filter(Boolean).map((x, i) => <li key={x} className="flex gap-3 rounded-xl bg-white/10 p-3"><span className="font-bold text-brand-sand">{i + 1}</span><span className="text-sm text-white/85">{x}</span></li>)}</ol></div><div className="rounded-[2rem] border border-brand-line bg-white p-7 sm:p-9"><Section eyebrow="06" title={c.learning} /><p className="mt-4 leading-relaxed text-brand-subtle">{p.learningStyle}</p><List items={p.workStyle.slice(0, 4)} /></div></section>
    <section className="mt-14 grid gap-7 lg:grid-cols-[1.15fr_.85fr]"><div><Section eyebrow="07" title={c.relationships} /><div className="mt-6 grid gap-3 sm:grid-cols-2">{(hi ? [['दोस्ती', 'friendship'], ['रोमांटिक रिश्ते', 'romance'], ['परिवार', 'family'], ['टीमवर्क', 'teamwork']] : [['Friendship', 'friendship'], ['Romantic relationships', 'romance'], ['Family', 'family'], ['Teamwork', 'teamwork']]).map(([name, context], i) => <article key={context} className={`rounded-2xl p-5 ${i % 2 ? 'bg-brand-cream' : 'border border-brand-line bg-white'}`}><h3 className="font-semibold text-brand-ink">{name}</h3><p className="mt-2 text-sm leading-relaxed text-brand-subtle">{p.relationshipContexts[context]}</p></article>)}</div></div><div className="rounded-[2rem] bg-brand-ink p-7 text-white"><Section eyebrow="08" title={c.leadership} body={p.leadership?.style} light /><List items={(p.leadership?.strengths || p.coreTraits).slice(0, 4)} dark /></div></section>
    <section className="mt-14 grid gap-7 lg:grid-cols-2"><div className="rounded-[2rem] bg-brand-cream p-7"><Section eyebrow="09" title={c.stress} /><p className="mt-4 text-brand-subtle">{hi ? 'जब दबाव बना रहे, आराम, सीमाएँ और भरोसेमंद बातचीत मदद कर सकती है। लगातार या गंभीर परेशानी में योग्य पेशेवर सहयोग लें।' : 'When pressure persists, rest, boundaries, and trusted conversation may help. Seek qualified professional support for persistent or severe distress.'}</p><List items={p.stressPatterns.slice(0, 4)} /></div><div className="rounded-[2rem] border border-brand-line bg-white p-7"><Section eyebrow="10" title={c.career} /><List items={p.careerThemes.slice(0, 3)} /><p className="mt-5 text-sm font-semibold text-brand-teal">{p.developmentTips?.[0] || p.growthAreas[0]}</p><Link href={localePath(locale, `personality/${p.slug}/careers`)} className="button-primary mt-6">{c.careers} {p.code}</Link></div></section>
    <section className="mt-14 rounded-[2rem] border border-brand-line bg-white p-7 sm:p-9"><p className="section-kicker">{hi ? 'संवाद पर विचार' : 'Communication reflection'}</p><div className="mt-3 flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><h2 className="display-font text-3xl text-brand-ink">{hi ? 'आप बातचीत में कैसे दिखाई देते हैं?' : 'How do you show up in conversation?'}</h2><p className="mt-3 max-w-2xl text-brand-subtle">{hi ? 'कम्युनिकेशन इनसाइट्स आपके व्यक्तित्व प्रोफाइल के साथ संवाद की रोज़मर्रा की आदतों को देखने का एक अलग, व्यावहारिक तरीका देता है।' : 'Communication Insights offers a separate, practical way to notice everyday communication habits alongside this personality profile.'}</p></div><Link href={localePath(locale, 'insights/communication')} className="button-secondary shrink-0">{hi ? 'कम्युनिकेशन इनसाइट्स' : 'Communication Insights'} <span aria-hidden="true">→</span></Link></div></section>
    <section className="mt-14 rounded-[2rem] bg-brand-sand/25 p-7 sm:p-9"><Section eyebrow="11" title={c.plan} /><ol className="mt-6 grid gap-3 md:grid-cols-5">{plan.map((item, i) => <li key={item} className="rounded-2xl bg-white p-4 text-sm text-brand-ink"><span className="block text-xs font-bold text-brand-teal">0{i + 1}</span><span className="mt-2 block">{item}</span></li>)}</ol></section>
    <section className="mt-14 grid gap-7 lg:grid-cols-2"><div><Section eyebrow="12" title={c.misconceptions} /><List items={misconceptions(p.code, hi)} /></div><div><Section eyebrow="13" title={c.related} /><div className="mt-6 flex flex-wrap gap-3">{compareTypes.map(other => <Link key={other} href={localePath(locale, `compare/${pairSlug(code, other)}`)} className="button-secondary">{code} · {other}</Link>)}</div><div className="mt-6 flex flex-wrap gap-3"><Link href={localePath(locale, 'jobs')} className="button-secondary">{c.jobs}</Link><Link href={localePath(locale, 'community')} className="button-secondary">{c.join}</Link></div></div></section>
    <section className="mt-14"><Section eyebrow="14" title={c.faq} /><div className="mt-6 space-y-3">{faq.map(item => <details key={item.q} className="rounded-2xl border border-brand-line bg-white p-5"><summary className="cursor-pointer font-semibold text-brand-ink focus:outline-none focus-visible:ring-2 focus-visible:ring-brand-teal">{item.q}</summary><p className="mt-4 max-w-3xl leading-relaxed text-brand-subtle">{item.a}</p></details>)}</div></section>
    <section className="mt-14 rounded-[2rem] bg-brand-teal p-8 text-white"><h2 className="display-font text-3xl sm:text-4xl">{c.final}</h2><p className="mt-4 max-w-2xl text-white/80">{p.shortSummary}</p><div className="mt-7 flex flex-wrap gap-3"><a href={productionAppUrl('/test')} className="button-light">{c.test}</a><Link href={localePath(locale, `personality/${p.slug}/careers`)} className="button-dark-outline">{c.careers}</Link><Link href={localePath(locale, `compare/${pairSlug(code, compareTypes[0])}`)} className="button-dark-outline">{c.compare}</Link><Link href={localePath(locale, 'community')} className="button-dark-outline">{c.join}</Link></div></section>
  </main></>;
}
function Section({ eyebrow, title, body, light = false }) { return <div className="max-w-3xl"><p className={`section-kicker ${light ? 'text-brand-sand' : ''}`}>{eyebrow}</p><h2 className={`display-font mt-2 text-3xl sm:text-4xl ${light ? 'text-white' : 'text-brand-ink'}`}>{title}</h2>{body ? <p className={`mt-3 leading-relaxed ${light ? 'text-white/75' : 'text-brand-subtle'}`}>{body}</p> : null}</div>; }
function List({ items, dark = false }) { return <ul className="mt-5 grid gap-2 sm:grid-cols-2">{items.map(item => <li key={item} className={dark ? 'rounded-xl bg-white/10 px-4 py-3 text-sm text-white/85' : 'rounded-xl bg-white/80 px-4 py-3 text-sm text-brand-subtle'}>{item}</li>)}</ul>; }
function Insight({ index, title, body, note }) { return <article className={`rounded-3xl p-6 ${index % 3 === 1 ? 'bg-brand-cream' : index % 3 === 2 ? 'bg-brand-sand/25' : 'border border-brand-line bg-white'}`}><Glyph index={index} /><h3 className="mt-4 font-semibold text-brand-ink">{title}</h3><p className="mt-2 text-sm text-brand-subtle">{body}</p><p className="mt-4 border-t border-brand-line pt-3 text-xs text-brand-plum">{note}</p></article>; }
function Flow({ title, items }) { return <><p className="mt-4 text-brand-subtle">{title}</p><div className="mt-5 space-y-2">{items.map((item, i) => <p key={item} className="rounded-xl bg-brand-cream p-3 text-sm text-brand-ink"><span className="mr-2 font-bold text-brand-teal">{i + 1}</span>{item}</p>)}</div></>; }
function Callout({ title, text, tone }) { return <div className={`rounded-xl p-4 ${tone === 'teal' ? 'bg-brand-teal/10' : 'bg-brand-plum/10'}`}><p className="text-xs font-bold uppercase tracking-wide text-brand-ink">{title}</p><p className="mt-2 text-sm text-brand-subtle">{text}</p></div>; }
function Glyph({ index }) { return <svg aria-hidden="true" viewBox="0 0 24 24" className="h-9 w-9 fill-none stroke-current stroke-2 text-brand-teal"><path d={['M4 18 12 4l8 14-8 4-8-4Z','M4 20h16M6 16l3-5 3 3 4-7 2 9','M5 5h14v14H5zM8 9h8M8 13h5','M5 20 12 4l7 16M8 14h8','M4 8h16M4 16h16M8 4v16'][index % 5]} strokeLinecap="round" strokeLinejoin="round" /></svg>; }
function TypeVisual({ code, color }) { const motifs={INTJ:'M42 210 150 50l80 90 120-70',INTP:'M48 190c65-150 115 120 175-80s85 125 150-60',ENTJ:'M45 220 130 120l70 38 150-110',ENTP:'M45 95c88 0 82 155 176 70s90-15 150-105',INFJ:'M52 205c60-100 100-100 155 0 40-120 85-125 150-8',INFP:'M48 210c55-165 108 105 166-20 58-125 90 70 155-95',ENFJ:'M50 200 140 105l72 65 145-95',ENFP:'M48 210 115 72l84 125 146-105',ISTJ:'M50 205h320M75 155h270M105 105h210',ISFJ:'M50 200c70-120 100 60 160-55 65-115 95 70 155-40',ESTJ:'M50 210 120 150l72 22 165-100',ESFJ:'M55 200c66-110 107-15 155-70 60-80 98 35 150-60',ISTP:'M55 210 118 70l85 140 164-100',ISFP:'M52 205c58-110 100 70 160-60 65-130 95 85 150-85',ESTP:'M48 215 125 80l78 90 165-135',ESFP:'M48 205c80-135 100 100 165-45 65-130 85 85 150-100'}; return <svg aria-hidden="true" viewBox="0 0 420 270" className="mx-auto w-full max-w-md"><path d={motifs[code]} fill="none" stroke={color} strokeWidth="10" strokeLinecap="round" strokeLinejoin="round"/><circle cx="210" cy="140" r="42" fill="#E8B99A"/><circle cx="210" cy="140" r="18" fill="#1F6C7D"/><circle cx="70" cy="65" r="14" fill={color} opacity=".7"/><circle cx="350" cy="205" r="18" fill="#E8B99A" opacity=".85"/></svg>; }
function misconceptions(code, hi) { return hi ? [`${code} होना क्षमता या सीमाओं का निश्चित फैसला नहीं है।`, 'अंतर्मुखी होना सामाजिक रूप से अक्षम होना नहीं है।', 'सोचने या महसूस करने की पसंद तर्कहीनता या भावनाहीनता नहीं बताती।', 'लोग भूमिका, अनुभव और जीवन-चरण के साथ बदलते हैं।'] : [`Being ${code} is not a verdict on ability or limits.`, 'Introversion does not mean social incapability.', 'Thinking or feeling preferences do not mean emotionlessness or irrationality.', 'People change through roles, experience, and life stages.']; }
