'use client';

import { useCallback, useEffect, useState } from 'react';
import Link from 'next/link';
import { conflictInsightsApi } from '../../lib/conflict-insights-api';
import { conflictCopy } from '../../data/conflict-insights';

const storageKey = 'kalqlater.conflict-insights.session';
const read = () => { try { return JSON.parse(window.sessionStorage.getItem(storageKey) || 'null'); } catch { return null; } };
const band = { en: { higher: 'More present', lower: 'Less present', balanced: 'Context-dependent', limited: 'Limited evidence', 'clear-pattern': 'Clear pattern', 'emerging-pattern': 'Emerging pattern', 'mixed-evidence': 'Mixed evidence', 'limited-evidence': 'Limited evidence' }, hi: { higher: 'अधिक स्पष्ट', lower: 'कम स्पष्ट', balanced: 'संदर्भ के अनुसार', limited: 'सीमित संकेत', 'clear-pattern': 'स्पष्ट पैटर्न', 'emerging-pattern': 'उभरता पैटर्न', 'mixed-evidence': 'मिश्रित संकेत', 'limited-evidence': 'सीमित संकेत' } };

export function ConflictResult({ locale, resultId }) {
  const c = conflictCopy(locale); const [result, setResult] = useState(null); const [error, setError] = useState('');
  const load = useCallback(async () => { const saved = read(); if (!saved?.accessToken || saved.resultId !== resultId || saved.locale !== locale) { setError(locale === 'hi' ? 'यह निजी परिणाम इस ब्राउज़र सत्र में उपलब्ध नहीं है।' : 'This private result is not available in this browser session.'); return; } try { const payload = await conflictInsightsApi.result(resultId, saved.accessToken); setResult(payload.result); } catch { setError(locale === 'hi' ? 'परिणाम अभी उपलब्ध नहीं है।' : 'This result is not available right now.'); } }, [locale, resultId]);
  useEffect(() => { const timer = window.setTimeout(() => { void load(); }, 0); return () => window.clearTimeout(timer); }, [load]);
  if (error) return <Notice locale={locale} title={locale === 'hi' ? 'निजी परिणाम उपलब्ध नहीं है' : 'Private result unavailable'} body={error} />;
  if (!result) return <Notice locale={locale} title={locale === 'hi' ? 'आपके पैटर्न देख रहे हैं…' : 'Looking for patterns in your responses…'} />;
  const names = Object.fromEntries(c.dimensions);
  const weekly = result.weekly_challenge?.title?.[locale] && result.weekly_challenge?.instruction?.[locale] ? result.weekly_challenge : null;
  if (!weekly) return <Notice locale={locale} title={locale === 'hi' ? 'परिणाम उपलब्ध नहीं है' : 'Result unavailable'} body={locale === 'hi' ? 'इस परिणाम का आवश्यक मार्गदर्शन अधूरा है।' : 'Required authored guidance is missing from this result.'} />;
  return <article className="mx-auto max-w-6xl px-4 py-8 sm:px-6 lg:py-12"><header className="rounded-[2rem] bg-brand-ink px-6 py-10 text-white sm:px-10"><p className="section-kicker text-brand-sand">KalQLater · {c.title}</p><h1 className="display-font mt-3 text-4xl sm:text-5xl">{locale === 'hi' ? 'मतभेद में आपके पैटर्न' : 'Your patterns in conflict'}</h1><p className="mt-5 max-w-3xl text-lg leading-relaxed text-white/80">{result.summary}</p></header><section className="mt-10 grid gap-6 lg:grid-cols-2"><div className="rounded-[2rem] border border-brand-line bg-white p-7"><h2 className="display-font text-3xl text-brand-ink">{locale === 'hi' ? 'मुख्य पैटर्न' : 'Key patterns'}</h2><div className="mt-6 grid gap-3 sm:grid-cols-2">{result.dimension_results.map((item) => <div key={item.dimension_id} className="rounded-2xl bg-brand-cream p-4"><h3 className="font-semibold text-brand-ink">{names[item.dimension_id]}</h3><p className="mt-2 text-xs font-semibold text-brand-teal">{band[locale][item.direction]} · {band[locale][item.confidence]}</p><p className="mt-3 text-sm leading-relaxed text-brand-subtle">{item.explanation}</p></div>)}</div></div><aside className="rounded-[2rem] bg-brand-teal p-7 text-white"><p className="section-kicker text-brand-sand">{locale === 'hi' ? 'साप्ताहिक प्रयोग' : 'Weekly Experiment'}</p><h2 className="display-font mt-3 text-3xl">{weekly.title[locale]}</h2><p className="mt-4 leading-relaxed text-white/80">{weekly.instruction[locale]}</p></aside></section><section className="mt-10 rounded-[2rem] bg-brand-sand/30 p-7"><p className="section-kicker">{locale === 'hi' ? 'यह क्यों दिखा' : 'Why this appeared'}</p><h2 className="display-font mt-3 text-3xl text-brand-ink">{locale === 'hi' ? 'आपके चुने हुए क्षण' : 'The moments you chose'}</h2><p className="mt-3 text-sm leading-relaxed text-brand-subtle">{locale === 'hi' ? 'ये उदाहरण आपके चुने उत्तरों से आते हैं। आंतरिक स्कोर या वेट नहीं दिखाए जाते।' : 'These examples come from your selected responses. Internal scores and weights are not shown.'}</p><ul className="mt-6 grid gap-3 sm:grid-cols-3">{result.evidence_moments.map((item) => <li key={item.id} className="rounded-2xl bg-white/80 p-4"><h3 className="font-semibold text-brand-ink">{item.title}</h3><p className="mt-2 text-sm leading-relaxed text-brand-subtle">{item.observation}</p></li>)}</ul></section><section className="mt-10 grid gap-6 lg:grid-cols-3"><List title={locale === 'hi' ? 'उपयोगी पैटर्न' : 'Useful patterns'} items={result.strengths} /><List title={locale === 'hi' ? 'ध्यान देने योग्य जगहें' : 'Places to notice'} items={result.blind_spots} /><List title={locale === 'hi' ? 'व्यावहारिक कदम' : 'Practical habits'} items={result.practical_suggestions} /></section><p className="mt-8 text-center text-xs leading-relaxed text-brand-subtle">{result.disclaimer}</p></article>;
}

function Notice({ locale, title, body }) { return <section className="mx-auto max-w-2xl px-4 py-14"><div className="rounded-[2rem] bg-brand-cream p-8 text-center"><h1 className="display-font text-3xl text-brand-ink">{title}</h1>{body ? <p className="mt-3 text-brand-subtle">{body}</p> : null}<Link className="button-primary mt-7" href={`/${locale}/insights/conflict/start`}>{locale === 'hi' ? 'नया आत्मचिंतन' : 'Start a new reflection'}</Link></div></section>; }
function List({ title, items }) { return <section className="rounded-[2rem] bg-brand-cream p-6"><h2 className="display-font text-2xl text-brand-ink">{title}</h2><ul className="mt-5 space-y-3">{items.map((item) => <li key={item.id || item} className="rounded-xl bg-white/80 p-3 text-sm leading-relaxed text-brand-subtle">{item.text || item}</li>)}</ul></section>; }
