'use client';

import { useCallback, useEffect, useRef, useState } from 'react';
import { useRouter } from 'next/navigation';
import { conflictInsightsApi } from '../../lib/conflict-insights-api';
import { conflictCopy } from '../../data/conflict-insights';

const storageKey = 'kalqlater.conflict-insights.session';
const key = () => `${Date.now()}-${crypto.randomUUID()}`;
const read = () => { try { return JSON.parse(window.sessionStorage.getItem(storageKey) || 'null'); } catch { return null; } };
const save = (value) => window.sessionStorage.setItem(storageKey, JSON.stringify(value));
const errorText = (error, locale) => {
  if (error?.code === 'expired') return locale === 'hi' ? 'यह सत्र समाप्त हो गया है। नया आत्मचिंतन शुरू करें।' : 'This session has expired. Begin a new reflection.';
  if (error?.code === 'timeout') return locale === 'hi' ? 'सेवा को जवाब देने में समय लगा। कनेक्शन जाँचकर फिर कोशिश करें।' : 'The service took too long to respond. Check your connection and try again.';
  return locale === 'hi' ? 'यह कदम पूरा नहीं हो सका। कृपया फिर कोशिश करें।' : 'That step could not be completed. Please try again.';
};

export function ConflictStart({ locale }) {
  const router = useRouter(); const c = conflictCopy(locale); const [state, setState] = useState('idle'); const [error, setError] = useState('');
  const begin = async () => { setState('loading'); setError(''); try { const created = await conflictInsightsApi.createSession(locale); save({ sessionId: created.session_id, accessToken: created.access_token, locale }); router.push(`/${locale}/insights/conflict/session/${created.session_id}`); } catch (issue) { setError(errorText(issue, locale)); setState('idle'); } };
  return <section className="mx-auto max-w-3xl px-4 py-10 sm:px-6 lg:py-16"><div className="content-hero rounded-[2rem] border border-brand-line px-6 py-9 sm:px-10 sm:py-12"><p className="section-kicker">KalQLater · {c.title}</p><h1 className="display-font mt-3 text-4xl text-brand-ink sm:text-5xl">{c.startTitle}</h1><p className="mt-5 max-w-2xl text-lg leading-relaxed text-brand-subtle">{c.startBody}</p><ul className="mt-8 grid gap-3 sm:grid-cols-3">{[[c.time, '◷'], [c.privacy, '◌'], [c.safety, '◇']].map(([text, icon]) => <li key={text} className="rounded-2xl bg-white p-4 text-sm leading-relaxed text-brand-subtle"><span aria-hidden="true" className="mr-2 font-bold text-brand-teal">{icon}</span>{text}</li>)}</ul><p className="mt-7 rounded-xl border-l-2 border-brand-saffron bg-brand-sand/20 px-4 py-3 text-sm text-brand-ink">{locale === 'hi' ? 'वही प्रतिक्रिया चुनें जो आप सामान्यतः करते/करती हैं, न कि जो आदर्श लगता है।' : 'Choose what you would usually do, not what seems ideal.'}</p>{error ? <p role="alert" className="mt-5 rounded-xl bg-brand-plum/10 p-4 text-sm text-brand-ink">{error}</p> : null}<button type="button" className="button-primary mt-8" onClick={begin} disabled={state === 'loading'}>{state === 'loading' ? (locale === 'hi' ? 'शुरू हो रहा है…' : 'Starting…') : c.start}<span aria-hidden="true">→</span></button></div></section>;
}

export function ConflictFlow({ locale, sessionId }) {
  const router = useRouter(); const [scenario, setScenario] = useState(null); const [session, setSession] = useState(null); const [choice, setChoice] = useState(''); const [state, setState] = useState('loading'); const [error, setError] = useState(''); const abortRef = useRef();
  const loadScenario = useCallback(async (current, id, signal) => { const response = await conflictInsightsApi.scenario(sessionId, read().accessToken, id, signal); setSession(current); setScenario(response.scenario); setChoice(response.scenario.selected_option_id || ''); setState('ready'); }, [sessionId]);
  const load = useCallback(async () => { const saved = read(); if (!saved || saved.sessionId !== sessionId || saved.locale !== locale) { setState('invalid'); return; } abortRef.current?.abort(); const controller = new AbortController(); abortRef.current = controller; setState('loading'); setError(''); try { const [current, next] = await Promise.all([conflictInsightsApi.session(sessionId, saved.accessToken, controller.signal), conflictInsightsApi.next(sessionId, saved.accessToken, controller.signal)]); if (!next.scenario) { const completed = saved.resultId ? null : await conflictInsightsApi.complete(sessionId, saved.accessToken, controller.signal); const resultId = saved.resultId || completed.result_id; save({ ...saved, resultId }); router.replace(`/${locale}/insights/conflict/result/${resultId}`); return; } await loadScenario(current, next.scenario.scenario_id, controller.signal); } catch (issue) { setState('error'); setError(errorText(issue, locale)); } }, [loadScenario, locale, router, sessionId]);
  useEffect(() => { const timer = window.setTimeout(() => { void load(); }, 0); return () => { window.clearTimeout(timer); abortRef.current?.abort(); }; }, [load]);
  const submit = async () => { if (!choice || !scenario || state === 'submitting') return; const saved = read(); setState('submitting'); setError(''); try { const payload = { scenario_id: scenario.scenario_id, option_id: choice, idempotency_key: key() }; if (scenario.selected_option_id) await conflictInsightsApi.update(sessionId, saved.accessToken, payload); else await conflictInsightsApi.submit(sessionId, saved.accessToken, payload); const current = await conflictInsightsApi.session(sessionId, saved.accessToken); const nextId = current.scenario_ids[scenario.progress.index + 1]; if (nextId) { await loadScenario(current, nextId); return; } const completed = await conflictInsightsApi.complete(sessionId, saved.accessToken); save({ ...saved, resultId: completed.result_id }); router.replace(`/${locale}/insights/conflict/result/${completed.result_id}`); } catch (issue) { setState('ready'); setError(errorText(issue, locale)); } };
  const back = async () => { if (!scenario || !session || scenario.progress.index === 0) return; setState('loading'); try { await loadScenario(session, session.scenario_ids[scenario.progress.index - 1]); } catch (issue) { setState('ready'); setError(errorText(issue, locale)); } };
  if (state === 'invalid') return <Notice locale={locale} title={locale === 'hi' ? 'सत्र उपलब्ध नहीं है' : 'This session is not available'} />;
  if (state === 'loading') return <Notice locale={locale} title={locale === 'hi' ? 'आपकी प्रतिक्रियाएँ लोड हो रही हैं…' : 'Loading your reflection…'} />;
  if (state === 'error' || !scenario) return <Notice locale={locale} title={locale === 'hi' ? 'फिर कोशिश करें' : 'Try again'} body={error} action={load} />;
  const total = scenario.progress.total; const answered = scenario.progress.answered; const progress = Math.round((answered / total) * 100);
  return <section className="mx-auto max-w-3xl px-4 py-8 sm:px-6 lg:py-12"><div className="rounded-[2rem] border border-brand-line bg-white p-5 shadow-[0_20px_50px_rgba(45,40,37,.06)] sm:p-9"><div className="flex items-center justify-between gap-4"><p className="section-kicker">{scenario.category}</p><p className="text-sm text-brand-subtle">{scenario.progress.index + 1} / {total}</p></div><div className="mt-3 h-1.5 overflow-hidden rounded-full bg-brand-cream" role="progressbar" aria-label={locale === 'hi' ? 'आत्मचिंतन की प्रगति' : 'Reflection progress'} aria-valuemin="0" aria-valuemax={total} aria-valuenow={answered}><span className="block h-full rounded-full bg-brand-teal transition-[width]" style={{ width: `${progress}%` }} /></div><p className="mt-8 text-sm font-medium text-brand-teal">{locale === 'hi' ? 'आप सामान्यतः क्या करते/करती हैं?' : 'What would you usually do?'}</p><h1 className="display-font mt-3 text-3xl leading-tight text-brand-ink sm:text-4xl">{scenario.prompt}</h1><fieldset className="mt-8"><legend className="sr-only">{locale === 'hi' ? 'अपनी प्रतिक्रिया चुनें' : 'Choose your response'}</legend><div className="grid gap-3">{scenario.options.map((option, index) => <label key={option.id} className={`group flex cursor-pointer items-start gap-4 rounded-2xl border p-4 transition sm:p-5 ${choice === option.id ? 'border-brand-teal bg-brand-teal/5 shadow-sm' : 'border-brand-line bg-brand-bg hover:border-brand-teal/60'}`}><input className="mt-1 h-5 w-5 accent-brand-teal" type="radio" name="response" value={option.id} checked={choice === option.id} onChange={() => setChoice(option.id)} /><span className="min-w-0"><span className="text-xs font-bold uppercase tracking-wide text-brand-teal">{String.fromCharCode(65 + index)}</span><span className="mt-1 block leading-relaxed text-brand-ink">{option.text}</span></span></label>)}</div></fieldset>{error ? <p role="alert" className="mt-5 rounded-xl bg-brand-plum/10 p-4 text-sm text-brand-ink">{error}</p> : null}<div className="mt-8 flex items-center justify-between gap-3"><button type="button" className="text-sm font-semibold text-brand-subtle underline underline-offset-4 disabled:opacity-40" onClick={back} disabled={scenario.progress.index === 0}>{locale === 'hi' ? 'वापस' : 'Back'}</button><button type="button" className="button-primary" onClick={submit} disabled={!choice || state === 'submitting'}>{state === 'submitting' ? (locale === 'hi' ? 'सहेज रहे हैं…' : 'Saving…') : (locale === 'hi' ? 'जारी रखें' : 'Continue')} <span aria-hidden="true">→</span></button></div></div></section>;
}

function Notice({ locale, title, body, action }) { return <section className="mx-auto max-w-2xl px-4 py-14"><div className="rounded-[2rem] bg-brand-cream p-8 text-center"><h1 className="display-font text-3xl text-brand-ink">{title}</h1>{body ? <p className="mt-3 text-brand-subtle">{body}</p> : null}{action ? <button type="button" onClick={action} className="button-primary mt-7">{locale === 'hi' ? 'फिर कोशिश करें' : 'Retry'}</button> : <a className="button-primary mt-7" href={`/${locale}/insights/conflict/start`}>{locale === 'hi' ? 'शुरू करें' : 'Start again'}</a>}</div></section>; }
