'use client';

import { useCallback, useEffect, useState } from 'react';
import Link from 'next/link';
import { leadershipInsightsApi as api } from '../../lib/leadership-insights-api';
import { leadershipCopyFor } from '../../data/leadership-insights';

const storageKey = 'kalqlater.leadership-insights.session';
const read = () => { try { return JSON.parse(sessionStorage.getItem(storageKey) || 'null'); } catch { return null; } };

export function LeadershipResult({ locale, resultId }) {
  const c = leadershipCopyFor(locale); const [result, setResult] = useState(null); const [error, setError] = useState('');
  const load = useCallback(async () => { const saved = read(); if (!saved?.accessToken || saved.resultId !== resultId || saved.locale !== locale) { setError(locale === 'hi' ? 'यह निजी परिणाम इस ब्राउज़र में उपलब्ध नहीं है।' : 'This private result is not available in this browser.'); return; } try { setResult((await api.result(resultId, saved.accessToken)).result); } catch { setError(locale === 'hi' ? 'परिणाम उपलब्ध नहीं है।' : 'Result unavailable.'); } }, [locale, resultId]);
  useEffect(() => { const timer = window.setTimeout(() => { void load(); }, 0); return () => window.clearTimeout(timer); }, [load]);
  if (error || !result) return <Notice locale={locale} error={error} />;
  const weekly = result.weekly_challenge?.title?.[locale] && result.weekly_challenge?.instruction?.[locale] ? result.weekly_challenge : null;
  if (!weekly) return <Notice locale={locale} error={locale === 'hi' ? 'इस परिणाम का आवश्यक मार्गदर्शन उपलब्ध नहीं है।' : 'Required authored guidance is unavailable for this result.'} />;
  const names = Object.fromEntries(c.dimensions);
  return <main className="mx-auto max-w-6xl px-4 py-10 sm:px-6"><header className="rounded-[2rem] bg-brand-ink p-8 text-white sm:p-11"><p className="section-kicker text-brand-sand">KalQLater · Leadership Insights</p><h1 className="display-font mt-3 text-4xl">{locale === 'hi' ? 'नेतृत्व में आपके पैटर्न' : 'Your patterns in leadership'}</h1><p className="mt-5 max-w-3xl text-lg text-white/80">{result.summary}</p></header><section className="mt-8 grid items-start gap-6 lg:grid-cols-2"><div className="rounded-[2rem] border border-brand-line bg-white p-7"><h2 className="display-font text-3xl text-brand-ink">{locale === 'hi' ? 'मुख्य पैटर्न' : 'Key patterns'}</h2><div className="mt-6 grid gap-3 sm:grid-cols-2">{result.dimension_results.map((item) => <div key={item.dimension_id} className="rounded-2xl bg-brand-cream p-4"><h3 className="font-semibold text-brand-ink">{names[item.dimension_id]}</h3><p className="mt-3 text-sm leading-relaxed text-brand-subtle">{item.explanation}</p></div>)}</div></div><aside className="self-start rounded-[2rem] bg-brand-teal p-7 text-white"><p className="section-kicker text-brand-sand">{locale === 'hi' ? 'साप्ताहिक प्रयोग' : 'Weekly Experiment'}</p><h2 className="display-font mt-3 text-3xl">{weekly.title[locale]}</h2><p className="mt-4 leading-relaxed text-white/85">{weekly.instruction[locale]}</p><p className="mt-5 border-t border-white/20 pt-5 text-sm leading-relaxed text-white/75">{locale === 'hi' ? 'इसे किसी वास्तविक साझा काम की स्थिति में आज़माएँ और देखें कि बातचीत या जिम्मेदारी में क्या बदलता है।' : 'Try it in one real shared-work situation and notice what changes in the conversation or responsibility.'}</p></aside></section><Evidence moments={result.evidence_moments} locale={locale} /><ResultLists result={result} locale={locale} /><p className="mt-8 text-center text-xs text-brand-subtle">{result.disclaimer}</p></main>;
}

function Evidence({ moments, locale }) { return <section className="mt-8 rounded-[2rem] bg-brand-sand/30 p-7"><h2 className="display-font text-3xl text-brand-ink">{locale === 'hi' ? 'आपके चुने हुए क्षण' : 'The moments you chose'}</h2><p className="mt-3 text-sm leading-relaxed text-brand-subtle">{locale === 'hi' ? 'ये उदाहरण आपके चुने उत्तरों से आते हैं; आंतरिक स्कोर या वेट नहीं दिखाए जाते।' : 'These examples come from your selected responses; internal scores and weights are not shown.'}</p><div className="mt-6 grid gap-3 sm:grid-cols-3">{moments.map((item) => <article key={item.id} className="rounded-2xl bg-white p-4"><h3 className="font-semibold text-brand-ink">{item.title}</h3><p className="mt-2 text-sm leading-relaxed text-brand-subtle">{item.observation}</p></article>)}</div></section>; }
function ResultLists({ result, locale }) { const sections = [[locale === 'hi' ? 'ताकतें' : 'Strengths', result.strengths], [locale === 'hi' ? 'विकास के अवसर' : 'Growth opportunities', result.blind_spots], [locale === 'hi' ? 'व्यावहारिक आदतें' : 'Practical habits', result.practical_suggestions]]; return <section className="mt-8 grid gap-5 lg:grid-cols-3">{sections.map(([title, items]) => <article key={title} className="rounded-[2rem] bg-brand-cream p-6"><h2 className="display-font text-2xl text-brand-ink">{title}</h2><ul className="mt-4 space-y-3">{items.map((item) => <li key={item.id || item} className="rounded-xl bg-white p-3 text-sm leading-relaxed text-brand-subtle">{item.text || item}</li>)}</ul></article>)}</section>; }
function Notice({ locale, error }) { return <section className="mx-auto max-w-2xl px-4 py-14"><div className="rounded-[2rem] bg-brand-cream p-8 text-center"><h1 className="display-font text-3xl text-brand-ink">{error ? (locale === 'hi' ? 'निजी परिणाम उपलब्ध नहीं है' : 'Private result unavailable') : (locale === 'hi' ? 'पैटर्न देख रहे हैं…' : 'Looking for patterns…')}</h1>{error ? <><p className="mt-3 text-brand-subtle">{error}</p><Link className="button-primary mt-7" href={`/${locale}/insights/leadership/start`}>{locale === 'hi' ? 'फिर शुरू करें' : 'Start again'}</Link></> : null}</div></section>; }
