const ORDER = ['INTJ','INTP','ENTJ','ENTP','INFJ','INFP','ENFJ','ENFP','ISTJ','ISFJ','ESTJ','ESFJ','ISTP','ISFP','ESTP','ESFP'];

const LENSES = Object.freeze({
  INTJ:{energy:'protects long stretches of private concentration',information:'compresses patterns into a long-range model',planning:'builds a strategic route before exposing it',voice:'often presents a conclusion after substantial private reasoning',conflict:'may become terse, distant, or fixed on the underlying logic',stress:'can narrow around control, criticism, and solitary problem-solving',need:'needs intellectual respect, autonomy, and advance context',work:'frames systems, dependencies, and long-term consequences',social:'prefers purposeful contact with recovery time'},
  INTP:{energy:'restores clarity through uninterrupted private thought',information:'keeps testing an internal model for logical consistency',planning:'holds plans loosely while the model is still changing',voice:'often speaks in precise qualifications or unfinished hypotheses',conflict:'may retreat into analysis or detach from emotional intensity',stress:'can over-analyse, postpone closure, and disappear into a problem',need:'needs thinking space, curiosity, and freedom from premature closure',work:'deepens models, architecture, and difficult technical questions',social:'prefers low-pressure contact built around shared curiosity'},
  ENTJ:{energy:'directs attention outward toward organised progress',information:'filters information for leverage and strategic relevance',planning:'sets milestones, authority, and a route to delivery',voice:'often communicates directly through outcomes and decisions',conflict:'may increase pressure, certainty, or command when blocked',stress:'can over-control, accelerate, and treat resistance as inefficiency',need:'needs candour, competence, and respect for commitments',work:'coordinates strategy, ownership, and measurable execution',social:'often prefers active, purposeful engagement'},
  ENTP:{energy:'develops momentum through exchange, novelty, and challenge',information:'expands possibilities by testing assumptions aloud',planning:'prefers adaptable experiments over early commitment',voice:'often communicates rapidly through questions, reframes, and debate',conflict:'may keep arguing, shift the frame, or intellectualise impact',stress:'can scatter attention, provoke, and generate options instead of closing',need:'needs intellectual freedom, responsive exchange, and room to revise',work:'generates alternatives, exposes assumptions, and opens opportunities',social:'often wants variety and stimulating conversation'},
  INFJ:{energy:'protects private space to integrate experience and meaning',information:'synthesises patterns with their human consequences',planning:'follows a coherent inner direction while adapting for people',voice:'often communicates in layered themes after private reflection',conflict:'may withdraw, infer a wider pattern, or reach a silent conclusion',stress:'can become over-interpretive, self-contained, and sensitive to rupture',need:'needs depth, trust, boundaries, and time to form language',work:'connects long-range meaning with stakeholder understanding',social:'prefers depth and selective connection over constant contact'},
  INFP:{energy:'returns inward to reconnect with values and imagination',information:'explores possibilities through personal meaning and association',planning:'keeps room for authenticity and emerging possibilities',voice:'often communicates through values, nuance, and illustrative stories',conflict:'may avoid pressure, internalise hurt, or defend a core value',stress:'can ruminate, withdraw, and struggle to turn ideals into a next step',need:'needs authenticity, gentleness, autonomy, and values to be respected',work:'develops purpose, narrative, and imaginative alternatives',social:'prefers sincere connection without forced frequency'},
  ENFJ:{energy:'builds clarity and momentum through human engagement',information:'organises patterns around shared purpose and readiness',planning:'coordinates people and commitments toward a meaningful direction',voice:'often communicates expressively through encouragement and alignment',conflict:'may pursue relational resolution or become overly persuasive',stress:'can over-function, personalise distance, and manage everyone’s response',need:'needs reciprocity, visible commitment, and relational responsiveness',work:'creates alignment, coaching, and coordinated contribution',social:'often values frequent, purposeful connection'},
  ENFP:{energy:'gains momentum from people, possibility, and emerging interest',information:'connects ideas through novelty, meaning, and human potential',planning:'prefers direction with freedom to discover a better route',voice:'often communicates enthusiastically through stories and associations',conflict:'may become scattered, emotionally intense, or avoid constraining closure',stress:'can overcommit, chase possibilities, and lose practical sequence',need:'needs encouragement, authenticity, variety, and space to explore',work:'spots possibilities, mobilises interest, and reframes purpose',social:'often wants warm contact with freedom rather than rigid obligation'},
  ISTJ:{energy:'protects private focus and dependable routines',information:'compares current facts with precedent and verified detail',planning:'defines sequence, standards, and responsibility in advance',voice:'often communicates factually, directly, and with careful specificity',conflict:'may become corrective, rigid, or focused on what was agreed',stress:'can tighten rules, criticise deviations, and carry responsibility alone',need:'needs reliability, clarity, privacy, and respect for standards',work:'protects accuracy, process, risk, and accountable delivery',social:'prefers steady low-drama contact and promises kept'},
  ISFJ:{energy:'restores through privacy, familiarity, and manageable demands',information:'tracks concrete detail alongside personal history and need',planning:'builds dependable routines that support specific people',voice:'often communicates considerately through context and practical care',conflict:'may accommodate, revisit details, or hold hurt quietly',stress:'can over-serve, worry over details, and resist disruptive change',need:'needs appreciation, steadiness, responsiveness, and safe directness',work:'maintains continuity, detail, and attentive support',social:'prefers warm dependable contact over unpredictable intensity'},
  ESTJ:{energy:'organises the external environment toward visible progress',information:'prioritises concrete evidence, standards, and practical constraints',planning:'assigns ownership, sequence, and deadlines early',voice:'often communicates plainly through expectations and correction',conflict:'may become blunt, controlling, or impatient with ambiguity',stress:'can push harder, reduce flexibility, and over-focus on compliance',need:'needs directness, dependability, and shared responsibility',work:'turns standards into coordinated execution and follow-through',social:'often prefers active engagement with clear roles'},
  ESFJ:{energy:'builds energy through responsive contact and shared activity',information:'notices concrete needs, social cues, and established obligations',planning:'organises practical support around people and occasions',voice:'often communicates warmly through inclusion and specific concern',conflict:'may seek reassurance, personalise distance, or preserve harmony too long',stress:'can over-accommodate, monitor reactions, and become approval-focused',need:'needs appreciation, reciprocity, belonging, and considerate feedback',work:'coordinates people, service, continuity, and practical cooperation',social:'often values regular contact and visible mutual care'},
  ISTP:{energy:'restores through autonomy and hands-on concentration',information:'tests immediate mechanics through observation and action',planning:'keeps plans minimal so real conditions can guide adjustment',voice:'often communicates concisely through facts and workable options',conflict:'may disengage, become blunt, or solve the problem without discussing it',stress:'can detach, take abrupt action, and reject perceived interference',need:'needs space, competence, low pressure, and practical honesty',work:'diagnoses systems, tests fixes, and adapts under real conditions',social:'prefers undemanding contact and shared activity'},
  ISFP:{energy:'returns to private sensory and emotional experience',information:'notices immediate impact, aesthetics, and personal resonance',planning:'keeps room to respond authentically to changing reality',voice:'often communicates gently through action, detail, and present feeling',conflict:'may withdraw, resist control, or show hurt indirectly',stress:'can become avoidant, impulsive, or unusually sensitive to intrusion',need:'needs autonomy, acceptance, calm presence, and respect for values',work:'refines lived experience, quality, and practical human detail',social:'prefers authentic low-pressure connection'},
  ESTP:{energy:'builds momentum through immediate action and live feedback',information:'reads opportunities, constraints, and reactions in real time',planning:'uses a short horizon and recalibrates from results',voice:'often communicates directly through challenge, humour, and action',conflict:'may escalate quickly, minimise reflection, or push for immediate resolution',stress:'can act faster, seek stimulation, and overlook later consequences',need:'needs freedom, responsiveness, candour, and room to act',work:'responds quickly, negotiates obstacles, and converts openings into action',social:'often enjoys active contact and spontaneous experience'},
  ESFP:{energy:'gains momentum from people, activity, and immediate experience',information:'tracks concrete experience and visible emotional response',planning:'prefers a clear next step with freedom to adapt',voice:'often communicates vividly through warmth, story, and present impact',conflict:'may react to tone, seek immediate connection, or avoid prolonged analysis',stress:'can become reactive, overextended, and focused on immediate relief',need:'needs warmth, inclusion, appreciation, and practical responsiveness',work:'activates people, notices live needs, and adapts delivery',social:'often values shared experience and responsive contact'},
});

const SCENARIOS = [
  ['planning a trip','balancing advance commitments with room to change'],['handling criticism','separating useful feedback from tone and inferred motive'],['choosing between options','agreeing when exploration ends and commitment begins'],['working toward a deadline','making ownership and progress visible before urgency rises'],['managing social plans','negotiating contact, recovery time, and last-minute change'],['solving an unfamiliar problem','combining each person’s evidence and testing style'],['responding to sudden change','distinguishing true constraints from preferred routines'],['giving emotional support','checking whether support means listening, reassurance, or action'],['making a major purchase','combining values, evidence, risk, and practical consequences'],['repairing a disagreement','returning to one observable event instead of a global judgement'],['starting a shared project','turning interest into roles, sequence, and a review point'],['dealing with uncertainty','naming what is known, assumed, and still open'],
];

const sentence = (value) => String(value || '').replace(/^[a-z]/, (letter) => letter.toUpperCase()).replace(/[.]+$/, '');
const sectionBody = (foundation, pattern) => foundation?.sections?.find(([title]) => pattern.test(title))?.[1];
const sharedPreferences = (a,b) => ['Energy','Information','Decision','Lifestyle'].filter((_,index) => a.code[index] === b.code[index]);
const differencePreferences = (a,b) => ['energy orientation','information focus','decision criteria','approach to structure'].filter((_,index) => a.code[index] !== b.code[index]);

function scenariosFor(a,b,la,lb) {
  const seed = ORDER.indexOf(a.code)*17 + ORDER.indexOf(b.code)*7;
  return [0,3,7,10].map((offset) => SCENARIOS[(seed+offset)%SCENARIOS.length]).map(([situation,focus],index) => ({
    situation: sentence(situation),
    typeA: `${a.code} may ${index%2 ? la.information : la.planning}.`,
    typeB: `${b.code} may ${index%2 ? lb.planning : lb.information}.`,
    friction: `Friction can emerge when ${a.code} reads ${lb.voice} as misaligned with ${la.need}, while ${b.code} reads ${la.voice} through ${lb.need}.`,
    helps: `Use ${focus}: let ${a.code} contribute how it ${la.information}, let ${b.code} contribute how it ${lb.information}, and choose one observable next step.`,
  }));
}

export function comparisonV3({ firstProfile:a, secondProfile:b, insight, foundation, authoredFoundation }) {
  const la=LENSES[a.code],lb=LENSES[b.code];
  const shared=sharedPreferences(a,b),different=differencePreferences(a,b);
  const pair=`${a.code} and ${b.code}`;
  const differences=different.length ? different.join(', ') : 'pace, experience, and context despite the same four-letter preference pattern';
  const common=shared.length ? shared.join(', ').toLowerCase() : 'few letter preferences, making explicit translation especially useful';
  const source=authoredFoundation;
  const decisionA=sentence(insight.decisionA);const decisionB=sentence(insight.decisionB);
  const quickAnswer=source?.quickAnswer || `${a.code} often ${la.information}, while ${b.code} often ${lb.information}. Their biggest practical difference may appear in ${differences}, because ${a.code} ${la.planning} while ${b.code} ${lb.planning}. They can generally get along when neither treats that processing rhythm as lack of care or competence.`;
  const communication=sectionBody(source,/communication/i) || `${a.code} ${la.voice}; ${b.code} ${lb.voice}. What may feel easy is combining a person who ${la.information} with one who ${lb.information}; trouble starts when either pace is mistaken for intent. A useful technique for this pair is to state the purpose, let ${a.code} contribute through how it ${la.voice}, let ${b.code} respond through how it ${lb.voice}, and then confirm one understood next step.`;
  const friendship=sectionBody(source,/friendship/i) || `${pair} may build friendship where ${la.social} meets someone who ${lb.social}. Maintenance works better when they choose activities that let ${a.code} use ${la.information} and ${b.code} use ${lb.information}, while agreeing how often to initiate and when low contact means recovery rather than rejection.`;
  const romance=sectionBody(source,/romance|relationship, dating/i) || `${pair} may be drawn to the contrast between ${la.social} and ${lb.social}. Because ${a.code} ${la.need} while ${b.code} ${lb.need}, affection, alone time, social expectations, routines, commitments, and repair need direct negotiation; attraction and type labels do not predict durability.`;
  const work=sectionBody(source,/work|workplace/i) || `At work, ${a.code} ${la.work}, while ${b.code} ${lb.work}. Make those specific contributions visible by assigning ownership that lets ${a.code} use ${la.planning} and ${b.code} use ${lb.planning}, then review the work and its impact without treating personality as employment suitability.`;
  const learn=sectionBody(source,/learn/i) || `${a.code} can borrow ${b.code}’s capacity to ${lb.information}; ${b.code} can borrow ${a.code}’s capacity to ${la.information}. The goal is a wider behavioural range, not asking either person to imitate the other.`;
  const scenarioItems=scenariosFor(a,b,la,lb);
  return {
    ...foundation,
    version:'v3',
    eyebrow:'Interaction intelligence • No compatibility score',
    helper:`${a.code} is often known as ${a.displayName}, while ${b.code} is often called ${b.displayName}. The useful question is how a person who ${la.information} may interact with someone who ${lb.information}—not whether either label guarantees a match.`,
    intro:source?.intro || `${pair} can bring ${a.strengths?.[0]?.toLowerCase()} together with ${b.strengths?.[0]?.toLowerCase()}. This guide focuses on how ${la.information} meets a person who ${lb.information}: what each may mean, what the other may hear, and which practical adjustments can improve friendship, relationships, and work.`,
    quickAnswer,
    scoreNote:'No compatibility score: personality type alone cannot predict relationship success. KalQLater focuses on communication patterns, differences, and practical interaction guidance instead.',
    atGlance:[
      ['Energy orientation',sentence(la.energy),sentence(lb.energy)],
      ['Information processing',sentence(la.information),sentence(lb.information)],
      ['Decision-making',sentence(insight.decisionA.replace(`${a.code} `,'')),sentence(insight.decisionB.replace(`${b.code} `,''))],
      ['Planning',sentence(la.planning),sentence(lb.planning)],
      ['Communication',sentence(la.voice),sentence(lb.voice)],
      ['Conflict response',sentence(la.conflict),sentence(lb.conflict)],
      ['Social needs',sentence(la.social),sentence(lb.social)],
      ['Work style',sentence(la.work),sentence(lb.work)],
    ],
    keyDifferences:`The most visible differences may involve ${differences}: ${a.code} ${la.information}, while ${b.code} ${lb.information}. In practice, ${a.code} may read how ${b.code} ${lb.planning} as pressure or drift, while ${b.code} may read how ${a.code} ${la.planning} as delay or rigidity.`,
    commonGround:`This pair shares ${common}. They may also recognise ${a.strengths?.[1]?.toLowerCase()} and ${b.strengths?.[1]?.toLowerCase()} as valuable contributions. Common ground helps only when both allow different behaviour inside the shared preference.`,
    interactionLoop:[
      `${a.code} ${la.voice}.`,
      `${b.code} may interpret that through a need for ${lb.need.replace(/^needs /,'')}.`,
      `${b.code} may respond by ${lb.conflict.replace(/^may /,'')}.`,
      `${a.code} can then read that response against a need for ${la.need.replace(/^needs /,'')}, creating friction—or useful complementarity when the interpretation is checked aloud.`,
    ],
    communication,
    decisionMaking:`${decisionA}; ${decisionB}. Together, the decision may stall when ${a.code} ${la.stress} while ${b.code} ${lb.stress}. Their shared decision record should capture evidence from ${la.information} and ${lb.information}, mark reversible choices, name the owner, and set the point at which discussion closes.`,
    conflict:{pattern:`${a.code} ${la.conflict}; ${b.code} ${lb.conflict}. The initial issue can become a disagreement about how the disagreement is being handled.`,escalation:`Escalation is more likely when ${a.code} protects ${la.need} by intensifying its usual response and ${b.code} protects ${lb.need} in the same way.`,repair:`Pause without disappearing, agree when to return, and let ${a.code} explain the event through ${la.information} before ${b.code} explains it through ${lb.information}; then make one concrete request each.`},
    stress:`When both are under stress, ${a.code} ${la.stress}, while ${b.code} ${lb.stress}. These are possible observable tendencies, not clinical claims; for this pair, reduce open issues until ${a.code} can regain ${la.need.replace(/^needs /,'')} and ${b.code} can regain ${lb.need.replace(/^needs /,'')}, then choose one small action.`,
    friendship,romance,work,
    emotionalNeeds:`${a.code} ${la.need}; ${b.code} ${lb.need}. Support becomes easier when ${a.code} names whether ${la.need.replace(/^needs /,'')} currently means listening, space, or action, and ${b.code} translates ${lb.need.replace(/^needs /,'')} into an equally concrete request.`,
    misunderstandings:[
      {from:a.code,signal:sentence(la.voice),heard:`${b.code} may hear distance from ${lb.need.replace(/^needs /,'')}.`,possibility:`${a.code} may instead be trying to ${la.information}.`},
      {from:b.code,signal:sentence(lb.voice),heard:`${a.code} may hear pressure against ${la.need.replace(/^needs /,'')}.`,possibility:`${b.code} may instead be trying to ${lb.information}.`},
      {from:a.code,signal:sentence(la.conflict),heard:`${b.code} may treat the response as a final judgement.`,possibility:`It may be an imperfect attempt to protect ${la.need.replace(/^needs /,'')}.`},
    ],
    scenarios:scenarioItems,
    adviceForTypeA:[`Tell ${b.code} when ${la.energy} is a processing need rather than disengagement.`,`Translate ${la.voice} into one concrete example and one requested response.`,`Before assuming intent, ask how ${b.code} is using ${lb.information}.`,`Close shared decisions with an owner and review point that respects ${lb.planning}.`],
    adviceForTypeB:[`Give ${a.code} enough context to use ${la.information} without forcing immediate certainty.`,`Explain when ${lb.voice} is exploration, care, or a decision request.`,`Do not interpret ${la.conflict} before checking what pressure ${a.code} is experiencing.`,`Make your need for ${lb.need.replace(/^needs /,'')} explicit instead of testing whether it is noticed.`],
    learnFromEachOther:learn,
    myths:[
      [`${pair} ${shared.length ? `are basically the same because they share ${shared.join(' and ')}` : 'are too different to understand each other'}.`,`${a.code} ${la.information}, while ${b.code} ${lb.information}; shared or different letters do not erase the interaction consequences.`],
      [`${a.code}’s ${la.conflict.replace(/^may /,'')} means the same thing as ${b.code}’s ${lb.conflict.replace(/^may /,'')}.`,`The first response may protect ${la.need.replace(/^needs /,'')}; the second may protect ${lb.need.replace(/^needs /,'')}. Check intended meaning before deciding what either behaviour says about the relationship.`],
    ],
    faq:[
      [`Are ${pair} compatible?`,`${pair} can get along, but personality type cannot predict success. Their practical fit depends on how ${la.information} meets ${lb.information}, alongside values, boundaries, and repair.`],
      [`What is the biggest difference between ${a.code} and ${b.code}?`,`${a.code} ${la.information}, while ${b.code} ${lb.information}. This difference often changes how quickly each speaks, decides, and responds to uncertainty.`],
      [`Can ${pair} be good friends?`,`${friendship} Friendship is strengthened by explicit expectations rather than assumed similarity.`],
      [`How do ${pair} communicate?`,`${a.code} ${la.voice}; ${b.code} ${lb.voice}. They communicate more effectively when purpose, example, and requested response are stated separately.`],
      [`Why might ${pair} clash?`,`They may clash when ${la.conflict.replace(/^may /,'')} meets ${lb.conflict.replace(/^may /,'')}, especially if each interprets pace or tone as intent.`],
      [`Can ${pair} work well together?`,`They can when ${la.work} and ${lb.work} are assigned clear ownership and personality is not treated as a hiring or ability measure.`],
    ],
  };
}

export function v3PairCount() { return ORDER.flatMap((_,index)=>ORDER.slice(index+1)).length; }
