import { pairSlug } from '../lib/comparisons';
import { comparisonProfile } from '../lib/comparisons';
import { comparisonContent } from '../lib/comparison-content';
import { personalityProfile } from '../lib/personality';
import { getPersonalityGuideContent } from './personality-guide';

// This is deliberately a small, fail-closed first batch.  Spanish comparison
// pages are only rendered when their complete pair record is authored below.
const PAIRS = Object.freeze({
  'intj-vs-intp': ['Dos mentes analíticas pueden compartir profundidad sin necesitar llegar al mismo ritmo.', 'Diferenciar una estrategia ya lista de una hipótesis aún abierta evita que la conversación se vuelva una prueba de quién tiene más razón.', 'La complementariedad aparece cuando INTJ aporta dirección y INTP mantiene viva la pregunta que mejora esa dirección.'],
  'intj-vs-entj': ['La visión estratégica une a esta pareja; la diferencia está en cuándo convertirla en acción visible.', 'INTJ suele madurar la arquitectura en silencio, mientras ENTJ busca ordenar recursos y mover una decisión. Acordar cuándo explorar y cuándo ejecutar protege a ambos ritmos.', 'Su fortaleza surge al combinar previsión con impulso, sin confundir rapidez con autoridad.'],
  'intj-vs-entp': ['Aquí se encuentran una mirada de largo alcance y una mente que abre posibilidades inesperadas.', 'INTJ puede pedir foco donde ENTP ve alternativas; ENTP puede invitar flexibilidad donde INTJ ya trazó una ruta. La curiosidad funciona mejor con un punto acordado de cierre.', 'Pueden crear ideas valiosas si convierten el debate en pequeños experimentos con responsables claros.'],
  'intj-vs-infj': ['Dos personas reservadas pueden conectar con mucha profundidad y, aun así, necesitar hacer visible lo que esperan.', 'INTJ tiende a ordenar sistemas y consecuencias; INFJ suele atender el sentido humano y los matices de una situación. El silencio es cómodo hasta que sustituye una conversación necesaria.', 'La relación gana madurez cuando la claridad práctica y la consideración humana se escuchan como información complementaria.'],
  'intj-vs-infp': ['Esta comparación reúne convicción estratégica y una atención cuidadosa a la coherencia personal.', 'INTJ puede buscar el camino más sólido; INFP puede preguntar qué impacto tendrá ese camino en las personas y los valores. Ninguna de esas preguntas sobra cuando se conversa sin prisa.', 'El crecimiento compartido consiste en volver explícitas las prioridades antes de debatir la solución.'],
  'intj-vs-enfj': ['Una dirección clara y una sensibilidad por las personas pueden formar una alianza exigente y generosa.', 'INTJ puede concentrarse en la estructura; ENFJ suele percibir la disposición y las necesidades del grupo. Nombrar tanto el objetivo como la experiencia de quienes participan reduce fricciones.', 'Juntos pueden transformar una visión en coordinación humana, siempre que el cuidado no se convierta en suposición.'],
  'intj-vs-enfp': ['La planificación profunda y la energía por lo posible suelen despertar una curiosidad mutua.', 'INTJ puede preferir una prioridad bien pensada; ENFP puede necesitar explorar antes de comprometerse. Un espacio para abrir opciones y otro para elegir evita que uno se sienta limitado o arrastrado.', 'La conexión crece cuando ambos hacen lugar a la imaginación y a la continuidad.'],
  'intj-vs-istj': ['Esta pareja puede valorar la competencia, la independencia y los acuerdos que se cumplen.', 'INTJ mira la dirección futura; ISTJ contrasta la propuesta con hechos, procedimientos y responsabilidades actuales. La conversación se vuelve más útil cuando conectan la ambición con los pasos verificables.', 'Su confianza se fortalece al explicar por qué cambiar algo merece el esfuerzo y cómo se sostendrá en la práctica.'],
  'intj-vs-isfj': ['La previsión estratégica y el cuidado de lo cotidiano pueden ofrecer una base muy atenta.', 'INTJ puede priorizar el sistema que vendrá; ISFJ suele notar quién depende de lo que sucede hoy. Hablar de cambios con tiempo y detalle permite que ambas contribuciones se vean.', 'La relación se beneficia cuando eficiencia y consideración se tratan como objetivos que pueden coexistir.'],
  'intj-vs-estj': ['Dos estilos decididos pueden avanzar mucho si hacen sitio para discutir el método antes de ejecutar.', 'INTJ suele cuestionar la estructura para mejorarla; ESTJ puede apoyarse en estándares y una organización ya probada. El desacuerdo es productivo cuando se traduce en criterios, no en posiciones.', 'Una división clara entre diseño estratégico y seguimiento operativo puede convertir la tensión en cobertura.'],
  'intj-vs-esfj': ['Esta pareja combina una mirada de sistema con una atención directa a la vida del grupo.', 'INTJ puede comunicar primero la lógica; ESFJ puede necesitar entender cómo afectará la decisión a las personas. Cuando ambos plantean sus necesidades sin atribuir intenciones, aparece más cooperación.', 'El vínculo prospera con acuerdos concretos y con tiempo para que la cercanía no quede subordinada a la eficiencia.'],
  'intj-vs-istp': ['Una visión de largo plazo se encuentra con alguien que aprende al observar, probar y ajustar.', 'INTJ puede querer comprender el mapa completo; ISTP puede confiar en una prueba concreta. Separar las decisiones reversibles de los compromisos mayores permite aprovechar los dos enfoques.', 'El respeto crece cuando la teoría explica la prueba y la prueba corrige la teoría.'],
  'intj-vs-isfp': ['La estructura y la sensibilidad a la experiencia real pueden parecer lejanas, pero ambas aportan una perspectiva valiosa.', 'INTJ puede concentrarse en la consecuencia futura; ISFP suele percibir qué se siente honesto y viable en el presente. Una conversación suave y específica ayuda a que ninguna voz quede fuera.', 'La relación mejora cuando se deja espacio para el afecto, la autonomía y una explicación clara de las decisiones.'],
  'intj-vs-estp': ['La estrategia paciente y la acción inmediata pueden generar admiración, impaciencia o las dos cosas a la vez.', 'INTJ tiende a evaluar consecuencias antes de moverse; ESTP aprende con rapidez de la oportunidad concreta. Los límites de riesgo y las revisiones breves hacen que su diferencia sea útil.', 'Pueden complementarse cuando cada persona reconoce que el ritmo de la otra también contiene información.'],
  'intj-vs-esfp': ['Esta combinación pone en diálogo la planificación silenciosa y una forma viva de conectar con el momento.', 'INTJ puede proteger una prioridad de largo alcance; ESFP puede recordar que una decisión también se vive en el presente. La cercanía aumenta cuando los planes incluyen disfrute y las emociones tienen un lugar claro.', 'Su mayor aprendizaje puede ser unir continuidad, espontaneidad y atención mutua.'],
  'infj-vs-enfp': ['Una visión orientada al sentido y una energía abierta a las posibilidades suelen crear conversaciones muy estimulantes.', 'INFJ puede necesitar tiempo para integrar lo que percibe; ENFP puede pensar en voz alta y abrir nuevas rutas. Acordar pausas y retornos permite que la inspiración no se convierta en agotamiento.', 'La relación gana profundidad cuando la intuición compartida se acompaña de límites, prioridades y acciones pequeñas.'],
});

export const spanishComparisonSlugs = Object.freeze(Object.keys(PAIRS));
export function isSpanishComparisonPair(first, second) { return spanishComparisonSlugs.includes(pairSlug(first, second)); }

function spanishProfile(code) { return getPersonalityGuideContent('es', code).profile; }
function seo(first, second, narrative) {
  const pair = `${first.code} y ${second.code}`;
  return { title: `${pair}: relación, comunicación y comparación | KalQLater`, description: `${pair}: una guía de reflexión sobre comunicación, decisiones, amistad, trabajo y crecimiento compartido. ${narrative[0]}` };
}

function spanishContent(first, second, narrative) {
  const pair = `${first.code} y ${second.code}`;
  const aStrength = first.strengths[0].toLowerCase(); const bStrength = second.strengths[0].toLowerCase();
  return {
    eyebrow: 'Relación · amistad · comparación', helper: `${first.displayName} (${first.code}) y ${second.displayName} (${second.code}): una lectura para observar patrones, contexto y elecciones.`, intro: narrative[0],
    snapshot: [['Relación', 'Ritmos que se conocen', narrative[1]], ['Amistad', 'Curiosidad compartida', `La conexión puede crecer al respetar ${aStrength} y ${bStrength}.`], ['Comunicación', 'Decir la intención', 'Explicar el motivo de una conversación evita que la otra persona tenga que adivinarlo.'], ['Decisiones', 'Dos perspectivas', 'Poner por escrito opciones, riesgos y una fecha de revisión puede dar cabida a ambos estilos.'], ['Conflicto', 'Reparación posible', 'Una pausa y un siguiente paso concreto suelen cuidar mejor el vínculo que intentar ganar.'], ['Crecimiento', 'Aprendizaje mutuo', narrative[2]]].map((item, index) => ({ icon: ['♡','☻','↔','◇','↺','↗'][index], title:item[0], label:item[1], text:item[2] })),
    sections: [
      ['Relación, citas y largo plazo', `${narrative[0]} En una relación, la confianza se construye al hablar con claridad de afecto, tiempo propio, responsabilidades y expectativas, en lugar de suponerlas.`, `Pista para conversar: ¿qué necesita cada persona para sentirse acompañada sin perder su espacio?`],
      ['Amistad', `${first.code} y ${second.code} pueden encontrar cercanía en intereses compartidos y en la libertad de mostrar su estilo sin convertirlo en una regla. Un período de silencio o mucho entusiasmo no tiene un único significado: conviene preguntar antes de interpretarlo.`, 'Después de una confusión, prueba con un mensaje breve: «Quiero entender qué era importante para ti».'],
      ['Trabajo, liderazgo y colaboración', `${first.code} puede aportar ${first.workStyle[0].toLowerCase()}, mientras que ${second.code} puede acercarse desde ${second.workStyle[0].toLowerCase()}. Definir roles, autoridad de decisión y momentos de revisión transforma esa diferencia en una colaboración más amplia.`, 'Práctica: anoten opciones, nombren a la persona responsable y acuerden cuándo revisarán la decisión.'],
      ['Guía de comunicación', `${first.code} y ${second.code} pueden expresarse y procesar a ritmos distintos. Preguntar por la experiencia, la evidencia o el valor que sostiene una conclusión ayuda a escuchar más allá de la respuesta final. Si un mensaje delicado crece demasiado por escrito, conviene trasladarlo a una conversación con más contexto.`, 'Para dar retroalimentación: describe el efecto, ofrece un ejemplo y formula una petición concreta.'],
      ['Forma de decidir', `${first.code} puede inclinarse por ${first.developmentTips[0].toLowerCase()}; ${second.code} puede beneficiarse de ${second.developmentTips[0].toLowerCase()}. No es una medida de cuidado ni de capacidad: es una invitación a hacer visibles los criterios antes de comprometerse.`, 'Cuando discrepen, separen lo reversible de lo difícil de cambiar y decidan qué evidencia necesitan.'],
      ['Conflicto, presión y reparación', `Bajo presión, ${first.code} puede necesitar un modo distinto de procesar que ${second.code}. Hablar de los desencadenantes cuando hay calma y volver a una petición concreta reduce la tendencia a atribuir malas intenciones.`, 'Práctica de reparación: pausa, reconoce tu parte y propone un cambio posible.'],
      ['Lo que pueden aprender', narrative[2], 'Esta comparación no define el futuro de una relación. La experiencia, los valores, los límites y las elecciones importan más que una etiqueta.'],
    ],
    misconceptions: [[`Mito: ${pair} son demasiado diferentes para entenderse.`, 'Realidad: las diferencias pueden complementar una relación cuando hay respeto, conversación y metas compartidas.'], ['Mito: el tipo decide el resultado de una relación.', 'Realidad: la confianza, los límites, la madurez y los hábitos cotidianos influyen mucho más.'], ['Mito: pedir perdón primero es perder.', 'Realidad: empezar una reparación puede proteger la seguridad de la relación.']],
    percentage: 'Por qué KalQLater no usa porcentajes de compatibilidad', percentageText: 'Las relaciones humanas no caben en un número. La conexión depende de la comunicación, los valores, la madurez, el momento vital, el comportamiento y los objetivos compartidos. Esta guía propone conversaciones y hábitos, no un veredicto.',
    faq: [[`¿${pair} son compatibles?`, `${pair} no se pueden resumir en un porcentaje. ${narrative[2]} La experiencia dependerá de cómo cuiden la comunicación, los valores y las expectativas cotidianas.`], [`¿${pair} pueden llevarse bien?`, 'Sí, especialmente si tratan sus diferentes ritmos como información y no como un defecto.'], [`¿${pair} pueden tener una relación?`, 'Pueden. Como en cualquier relación, la confianza, los límites, la reciprocidad y la reparación tras conversaciones difíciles son más importantes que el tipo.'], ['¿Pueden ser buenos amigos?', 'La amistad suele crecer cuando ambos crean experiencias compartidas y respetan las diferentes necesidades de cercanía o espacio.'], ['¿Pueden colaborar en el trabajo?', 'Sí, si aclaran roles, criterios de decisión y una forma de revisar los acuerdos.'], ['¿Quién pide perdón primero?', 'El tipo no lo determina. Una reparación saludable la inicia quien puede reconocer su parte.'], ['¿Cómo pueden decidir mejor juntos?', 'Hagan visibles los criterios, separen los riesgos reversibles de los compromisos mayores y acuerden una revisión.'], ['¿Cómo pueden detener una discusión?', 'Tomen una pausa, hablen de un asunto cada vez y definan un siguiente paso concreto.'], ['¿Pueden emprender juntos?', 'Sí, si acuerdan la autoridad de decisión, el riesgo que asumirán, el ritmo de comunicación y la responsabilidad por el seguimiento.'], ['¿Una persona puede cambiar por la otra?', 'Las personas pueden aprender entre sí, pero cambiar a alguien no debería ser el objetivo. El objetivo es una comprensión más útil y más opciones.'], ['¿Por qué KalQLater no usa porcentajes?', 'Porque la relación se construye con comportamiento, valores, comunicación y contexto, no con una cifra inventada.']],
    ui: { snapshot:'Vista rápida', signals:'Señales útiles para esta pareja', instead:'En lugar de un número', myths:'Mitos y realidad', beyond:'Mira más allá de la etiqueta', questions:'Preguntas frecuentes', explore:'Sigue explorando', further:'Lleva esta comparación un paso más allá', related:'Comparaciones relacionadas', test:'Realiza el test de personalidad', another:'Explora otra comparación', career:'Guía de carrera', communication:'Insights de comunicación', hub:'Centro de insights', compare:'Comparar', and:'y', pattern:'Comprende el patrón. Elige la próxima conversación.', reflection:'Esta es una herramienta de reflexión, no un veredicto sobre una relación, una capacidad o el futuro.', myth:'Mito', reality:'Realidad' },
  };
}

export function getComparisonContent(locale, firstCode, secondCode, base = null) {
  if (locale === 'en' || locale === 'hi') {
    if (base) return base;
    const first = personalityProfile(firstCode, locale); const second = personalityProfile(secondCode, locale);
    if (!first || !second) throw new Error(`Comparison unavailable: ${firstCode}/${secondCode}/${locale}`);
    return Object.freeze({ first, second, content: comparisonContent({ firstProfile: first, secondProfile: second, insight: comparisonProfile(firstCode, secondCode, locale), locale }) });
  }
  if (locale !== 'es') throw new Error(`Comparison locale unavailable: ${locale}`);
  const slug = pairSlug(firstCode, secondCode); const narrative = PAIRS[slug];
  if (!narrative) throw new Error(`Spanish comparison unavailable: ${slug}`);
  const first = spanishProfile(firstCode); const second = spanishProfile(secondCode);
  return Object.freeze({ first, second, content: spanishContent(first, second, narrative), seo: seo(first, second, narrative) });
}
