import { pairSlug } from '../lib/comparisons';
import { comparisonProfile } from '../lib/comparisons';
import { comparisonContent } from '../lib/comparison-content';
import { personalityProfile } from '../lib/personality';
import { getPersonalityGuideContent } from './personality-guide';

// This is deliberately a small, fail-closed first batch.  Spanish comparison
// pages are only rendered when their complete pair record is authored below.
const BATCH_ONE = Object.freeze({
  'intj-vs-intp': ['Dos mentes analíticas pueden compartir profundidad sin necesitar llegar al mismo ritmo.', 'Diferenciar una estrategia ya lista de una hipótesis aún abierta evita que la conversación se vuelva una prueba de quién tiene más razón.', 'La complementariedad aparece cuando INTJ aporta dirección y INTP mantiene viva la pregunta que mejora esa dirección.'],
  'intj-vs-entj': ['La visión estratégica une a esta pareja; la diferencia está en cuándo convertirla en acción visible.', 'INTJ suele madurar la arquitectura en silencio, mientras ENTJ busca ordenar recursos y mover una decisión. Acordar cuándo explorar y cuándo ejecutar protege a ambos ritmos.', 'Su fortaleza surge al combinar previsión con impulso, sin confundir rapidez con autoridad.'],
  'intj-vs-entp': ['Aquí se encuentran una mirada de largo alcance y una mente que abre posibilidades inesperadas.', 'INTJ puede pedir foco donde ENTP ve alternativas; ENTP puede invitar flexibilidad donde INTJ ya trazó una ruta. La curiosidad funciona mejor con un punto acordado de cierre.', 'Pueden crear ideas valiosas si convierten el debate en pequeños experimentos con responsables claros.'],
  'intj-vs-infj': ['Dos personas reservadas pueden conectar con mucha profundidad y, aun así, necesitar hacer visible lo que esperan.', 'INTJ tiende a ordenar sistemas y consecuencias; INFJ suele atender el sentido humano y los matices de una situación. El silencio es cómodo hasta que sustituye una conversación necesaria.', 'La relación gana madurez cuando la claridad práctica y la consideración humana se escuchan como información complementaria.'],
  'intj-vs-infp': ['Esta comparación reúne convicción estratégica y una atención cuidadosa a la coherencia personal.', 'INTJ puede buscar el camino más sólido; INFP puede preguntar qué impacto tendrá ese camino en las personas y los valores. Ninguna de esas preguntas sobra cuando se conversa sin prisa.', 'El crecimiento compartido consiste en volver explícitas las prioridades antes de debatir la solución.'],
  'intj-vs-enfj': ['Una dirección clara y una sensibilidad por las personas pueden formar una alianza exigente y generosa.', 'INTJ puede concentrarse en la estructura; ENFJ suele percibir la disposición y las necesidades del grupo. Nombrar tanto el objetivo como la experiencia de quienes participan reduce fricciones.', 'Juntos pueden transformar una visión en coordinación humana, siempre que el cuidado no se convierta en suposición.'],
  'intj-vs-enfp': ['La planificación profunda y la energía por lo posible suelen despertar una curiosidad mutua.', 'INTJ puede preferir una prioridad bien pensada; ENFP puede necesitar explorar antes de comprometerse. Un espacio para abrir opciones y otro para elegir evita que uno se sienta limitado o arrastrado.', 'La conexión crece cuando ambos hacen lugar a la imaginación y a la continuidad.'],
  'intj-vs-istj': ['Esta pareja puede valorar la competencia, la independencia y los acuerdos que se cumplen.', 'INTJ mira la dirección futura; ISTJ contrasta la propuesta con hechos, procedimientos y responsabilidades actuales. La conversación se vuelve más útil cuando conectan la ambición con los pasos verificables.', 'Su confianza se fortalece al explicar por qué cambiar algo merece el esfuerzo y cómo se sostendrá en la práctica.'],
  'intj-vs-isfj': ['La previsión estratégica y el cuidado de lo cotidiano pueden ofrecer una base muy atenta.', 'INTJ puede priorizar el sistema que vendrá; ISFJ suele notar quién depende de lo que sucede hoy. Hablar de cambios con tiempo y detalle permite que ambas contribuciones se vean.', 'La relación se beneficia cuando eficiencia y consideración se tratan como objetivos que pueden coexistir.'],
  'intj-vs-estj': ['Dos estilos decididos pueden avanzar mucho si hacen sitio para discutir el método antes de ejecutar.', 'INTJ suele cuestionar la estructura para mejorarla; ESTJ puede apoyarse en estándares y una organización ya probada. El desacuerdo es productivo cuando se traduce en criterios, no en posiciones.', 'Una división clara entre diseño estratégico y seguimiento operativo puede convertir la tensión en cobertura.'],
  'intj-vs-esfj': ['Esta pareja combina una mirada de sistema con una atención directa a la vida del grupo.', 'INTJ puede comunicar primero la lógica; ESFJ puede necesitar entender cómo afectará la decisión a las personas. Cuando ambos plantean sus necesidades sin atribuir intenciones, aparece más cooperación.', 'El vínculo prospera con acuerdos concretos y con tiempo para que la cercanía no quede subordinada a la eficiencia.'],
  'intj-vs-istp': ['Una visión de largo plazo se encuentra con alguien que aprende al observar, probar y ajustar.', 'INTJ puede querer comprender el mapa completo; ISTP puede confiar en una prueba concreta. Separar las decisiones reversibles de los compromisos mayores permite aprovechar los dos enfoques.', 'El respeto crece cuando la teoría explica la prueba y la prueba corrige la teoría.'],
  'intj-vs-isfp': ['La estructura y la sensibilidad a la experiencia real pueden parecer lejanas, pero ambas aportan una perspectiva valiosa.', 'INTJ puede concentrarse en la consecuencia futura; ISFP suele percibir qué se siente honesto y viable en el presente. Una conversación suave y específica ayuda a que ninguna voz quede fuera.', 'La relación mejora cuando se deja espacio para el afecto, la autonomía y una explicación clara de las decisiones.'],
  'intj-vs-estp': ['La estrategia paciente y la acción inmediata pueden generar admiración, impaciencia o las dos cosas a la vez.', 'INTJ tiende a evaluar consecuencias antes de moverse; ESTP aprende con rapidez de la oportunidad concreta. Los límites de riesgo y las revisiones breves hacen que su diferencia sea útil.', 'Pueden complementarse cuando cada persona reconoce que el ritmo de la otra también contiene información.'],
  'intj-vs-esfp': ['Esta combinación pone en diálogo la planificación silenciosa y una forma viva de conectar con el momento.', 'INTJ puede proteger una prioridad de largo alcance; ESFP puede recordar que una decisión también se vive en el presente. La cercanía aumenta cuando los planes incluyen disfrute y las emociones tienen un lugar claro.', 'Su mayor aprendizaje puede ser unir continuidad, espontaneidad y atención mutua.'],
  'infj-vs-enfp': ['Una visión orientada al sentido y una energía abierta a las posibilidades suelen crear conversaciones muy estimulantes.', 'INFJ puede necesitar tiempo para integrar lo que percibe; ENFP puede pensar en voz alta y abrir nuevas rutas. Acordar pausas y retornos permite que la inspiración no se convierta en agotamiento.', 'La relación gana profundidad cuando la intuición compartida se acompaña de límites, prioridades y acciones pequeñas.'],
});

// Batch 2 is intentionally authored at pair level. These are editorial
// briefs, not a type-name interpolation table: each opening, tension, and
// growth observation preserves the particular dynamic under discussion.
const BATCH_TWO = Object.freeze({
  'intp-vs-entj':['La exploración lógica y la voluntad de dirigir pueden respetarse mucho cuando no se apresuran a cerrar la conversación.','ENTJ puede pedir una decisión mientras INTP aún está comprobando el modelo; acordar qué evidencia basta evita que la precisión parezca resistencia.','El vínculo se vuelve más fuerte cuando la ambición se deja informar por una pregunta bien planteada.'],
  'intp-vs-entp':['Dos personas curiosas pueden disfrutar de una conversación que abre más puertas de las que cierra.','INTP suele profundizar en la coherencia de una idea; ENTP la prueba contra alternativas y debate. Un límite temporal protege la exploración de la dispersión.','Pueden convertir una gran afinidad intelectual en resultados si eligen qué hipótesis merece seguimiento.'],
  'intp-vs-infj':['La curiosidad analítica y la búsqueda de significado pueden producir una intimidad reflexiva.','INTP puede solicitar definiciones antes de confiar en una intuición; INFJ puede captar un patrón humano antes de poder explicarlo por completo.','Aprenden mutuamente cuando dan tiempo tanto a la evidencia como a la interpretación.'],
  'intp-vs-infp':['Una mente que quiere comprender y otra que quiere actuar de acuerdo con sus valores pueden encontrarse con delicadeza.','INTP puede separar una cuestión en partes lógicas; INFP puede insistir en el impacto personal de esas partes.','La cercanía aumenta cuando no tratan sensibilidad y análisis como bandos opuestos.'],
  'intp-vs-enfj':['La investigación independiente y la atención al propósito colectivo pueden ampliar la perspectiva de ambos.','INTP puede necesitar espacio para formular una idea; ENFJ puede buscar saber cómo esa idea afectará al grupo.','La colaboración mejora al ofrecer una conclusión provisional antes de que la otra persona tenga que adivinarla.'],
  'intp-vs-enfp':['La imaginación de ENFP puede activar la curiosidad de INTP, y la precisión de INTP puede dar forma a una posibilidad.','Uno puede pensar en voz alta y el otro en silencio; reconocer esa diferencia evita interpretar la pausa como falta de interés.','El reto compartido es elegir una prioridad sin apagar la creatividad.'],
  'intp-vs-istj':['La lógica exploratoria y la confianza en los procedimientos probados pueden ofrecer una comparación muy práctica.','INTP puede querer revisar el supuesto; ISTJ puede preguntar si la alternativa funciona con los hechos y responsabilidades actuales.','El respeto crece cuando la novedad demuestra su utilidad y la experiencia deja espacio para mejorar.'],
  'intp-vs-isfj':['Una curiosidad por las ideas y una atención cuidadosa a las personas pueden complementarse sin ocupar el mismo lugar.','INTP puede buscar la explicación más limpia; ISFJ puede advertir consecuencias cotidianas que el modelo no muestra.','La relación gana equilibrio al valorar tanto la claridad conceptual como el cuidado fiable.'],
  'intp-vs-estj':['El análisis abierto y la orientación a la ejecución pueden chocar por el momento de tomar una decisión.','ESTJ puede querer un estándar y una persona responsable; INTP puede pedir una pregunta más antes de comprometerse.','Ambos se benefician de distinguir investigación útil de demora, y acción necesaria de prisa.'],
  'intp-vs-esfj':['La independencia intelectual y el deseo de mantener la cooperación requieren una comunicación especialmente explícita.','INTP puede no expresar de inmediato lo que piensa; ESFJ puede leer el silencio desde la relación y el ambiente.','Un acuerdo claro sobre necesidades y seguimiento hace más visible el cuidado de ambos.'],
  'intp-vs-istp':['Dos estilos reservados pueden compartir gusto por entender cómo funciona algo, aunque lo hagan de maneras distintas.','INTP puede seguir una teoría hasta que encaje; ISTP puede preferir tocar el problema y probar un ajuste.','Se enriquecen cuando una explicación acompaña a la prueba, y la prueba devuelve realidad a la explicación.'],
  'intp-vs-isfp':['La abstracción y la sensibilidad a la experiencia concreta pueden abrir una conversación menos obvia y muy valiosa.','INTP puede llegar por una idea; ISFP puede partir de cómo se vive una situación.','La conexión mejora cuando la crítica se formula con tacto y cada cual puede conservar su autenticidad.'],
  'intp-vs-estp':['Una persona puede investigar el sistema mientras la otra detecta una oportunidad en tiempo real.','INTP puede necesitar más evidencia; ESTP puede aprender actuando y corrigiendo.','Los dos ganan al acordar qué puede probarse ahora y qué exige una reflexión más larga.'],
  'intp-vs-esfp':['La conversación entre una mente analítica y una presencia muy conectada al momento puede ser sorprendentemente rica.','INTP puede concentrarse en el porqué; ESFP puede traer atención a quién está viviendo la situación y qué necesita ahora.','Su crecimiento está en hacer que las ideas sean compartibles y que la experiencia tenga espacio para ser comprendida.'],
  'entj-vs-entp':['La iniciativa de ENTJ y la capacidad de ENTP para cuestionar alternativas pueden crear un equipo muy activo.','ENTJ puede buscar avanzar pronto; ENTP puede seguir abriendo posibilidades incluso cuando el camino parece claro.','Una buena regla de decisión convierte el debate en innovación sin perder el impulso.'],
  'entj-vs-infj':['La orientación al resultado y la atención al significado humano pueden complementarse con mucha intención.','ENTJ puede señalar una dirección; INFJ puede preguntar qué impacto profundo tendrá esa dirección sobre las personas.','La colaboración madura cuando la velocidad incluye escucha y la reflexión termina en un siguiente paso.'],
  'entj-vs-infp':['La decisión directa y la coherencia con valores personales pueden exigir traducción mutua.','ENTJ puede pensar primero en eficacia; INFP puede necesitar saber si el modo de avanzar respeta lo que importa.','El desacuerdo se vuelve útil cuando ambos explican sus criterios antes de defender una solución.'],
  'entj-vs-enfj':['Dos estilos orientados a las personas pueden compartir energía, aunque prioricen cosas distintas.','ENTJ puede organizar para lograr resultados; ENFJ puede organizar para generar acuerdo y desarrollo.','Pueden liderar con más amplitud al alternar entre claridad de objetivo y escucha del grupo.'],
  'entj-vs-enfp':['La ambición estructurada y el entusiasmo por las posibilidades pueden atraer y también acelerar demasiado el ritmo.','ENTJ puede pedir compromiso; ENFP puede requerir explorar qué opción conserva más sentido y energía.','El vínculo prospera con prioridades claras que aún dejen lugar a la imaginación.'],
  'entj-vs-istj':['La estrategia de futuro y la responsabilidad por lo que funciona hoy suelen encontrar un terreno común.','ENTJ puede impulsar un cambio amplio; ISTJ puede cuidar que las obligaciones, riesgos y detalles no queden sin dueño.','Su fuerza aparece cuando la mejora se planifica sin perder la fiabilidad.'],
  'entj-vs-isfj':['La dirección firme y el cuidado atento pueden necesitar negociar el ritmo de los cambios.','ENTJ puede valorar la rapidez de una decisión; ISFJ puede percibir quién necesita preparación o apoyo.','La confianza crece cuando la iniciativa incluye explicaciones, escucha y seguimiento.'],
  'entj-vs-estj':['Dos estilos ejecutivos pueden ser muy eficaces si no convierten toda diferencia en una lucha por el control.','ENTJ puede replantear el sistema; ESTJ puede defender el método que permite cumplir.','Definir quién decide qué y cuándo revisar el proceso evita competir por la misma responsabilidad.'],
  'entj-vs-esfj':['La orientación a resultados y el cuidado de la cohesión pueden crear una alianza visible y exigente.','ENTJ puede comunicar la meta; ESFJ puede hacer evidente cómo la meta se recibirá y sostendrá en el grupo.','Ambos avanzan mejor al tratar la participación como parte del resultado, no como una demora.'],
  'entj-vs-istp':['La organización estratégica se cruza con una forma práctica de responder ante lo que ocurre.','ENTJ puede definir una ruta; ISTP puede detectar rápido dónde esa ruta tropieza con la realidad.','La colaboración funciona cuando el plan admite una prueba y la prueba informa la siguiente decisión.'],
  'entj-vs-isfp':['La firmeza para decidir y la sensibilidad individual pueden necesitar un lenguaje que no simplifique al otro.','ENTJ puede enfocarse en la prioridad; ISFP puede notar si la forma de llegar a ella deja a alguien sin voz.','El crecimiento aparece al combinar determinación con espacio para una respuesta honesta.'],
  'entj-vs-estp':['Dos personas orientadas a la acción pueden disfrutar del movimiento, pero diferir en el horizonte que miran.','ENTJ puede comprometer recursos hacia una meta; ESTP puede responder a la oportunidad inmediata.','Los acuerdos sobre riesgo, límites y seguimiento convierten esa energía en una fuerza sostenible.'],
  'entj-vs-esfp':['La disciplina de ejecución y la energía social del momento pueden generar una relación muy dinámica.','ENTJ puede querer priorizar sin distracciones; ESFP puede recordar que una experiencia humana también mueve a las personas.','La alianza mejora cuando la meta se comunica con calidez y el entusiasmo se acompaña de continuidad.'],
  'entp-vs-infj':['La exploración verbal y la reflexión profunda pueden ofrecer conversaciones de gran alcance.','ENTP puede probar una idea mediante el debate; INFJ puede necesitar integrar el tono, el sentido y la consecuencia humana.','La seguridad aumenta cuando el juego intelectual no sustituye el cuidado por el impacto.'],
  'entp-vs-infp':['La provocación creativa y la fidelidad a los valores pueden discrepar con intensidad sin ser incompatibles.','ENTP puede ver una objeción como invitación a pensar; INFP puede vivirla como una cuestión de respeto o autenticidad.','Ambos aprenden cuando aclaran la intención antes de discutir el contenido.'],
  'entp-vs-enfj':['La energía para abrir caminos y la capacidad de reunir personas pueden hacer que esta pareja inspire movimiento.','ENTP puede desafiar el consenso; ENFJ puede cuidar que el desacuerdo no cierre la participación.','La mejor colaboración convierte las ideas audaces en invitaciones claras para otras personas.'],
  'entp-vs-enfp':['Dos exploradores de posibilidades pueden encenderse mutuamente y dejar tareas importantes sin cerrar.','ENTP puede disfrutar del contraste de ideas; ENFP puede seguir la energía emocional de una nueva opción.','Un pequeño acuerdo sobre prioridad y seguimiento permite que la espontaneidad tenga efecto real.'],
  'entp-vs-istj':['La experimentación y la fiabilidad pueden mirarse con escepticismo antes de descubrir su valor mutuo.','ENTP puede cuestionar una regla; ISTJ puede preguntar por las consecuencias de romperla.','La relación gana solidez cuando una novedad se prueba con responsabilidad y una tradición se revisa con curiosidad.'],
  'entp-vs-isfj':['La rapidez para debatir y una forma cuidadosa de sostener los vínculos requieren atención al tono.','ENTP puede pensar que una conversación intensa es estimulante; ISFJ puede necesitar seguridad y tiempo para responder.','La cercanía se protege cuando la franqueza se acompaña de consideración concreta.'],
  'entp-vs-estj':['La inventiva que desafía reglas y la necesidad de convertir planes en resultados pueden debatir a menudo.','ENTP puede abrir un camino alternativo; ESTJ puede pedir criterio, plazo y responsabilidad.','Su diferencia se vuelve útil al definir qué experimento vale la pena y cómo se medirá.'],
  'entp-vs-esfj':['La búsqueda de novedad y la atención a la armonía pueden crear tanto diversión como malentendidos.','ENTP puede cambiar de tema o postura para explorar; ESFJ puede necesitar saber qué compromiso sigue en pie.','La confianza aumenta cuando la creatividad no borra la claridad relacional.'],
  'entp-vs-istp':['Dos estilos adaptables pueden disfrutar de probar límites, aunque uno lo haga con argumentos y otro con acción.','ENTP puede debatir muchas opciones; ISTP puede comprobar rápidamente cuál funciona.','La colaboración se afina cuando el intercambio de ideas termina en una prueba concreta.'],
  'entp-vs-isfp':['La curiosidad provocadora y una sensibilidad personal pueden requerir mucha libertad y tacto a la vez.','ENTP puede buscar una reacción intelectual; ISFP puede valorar que una diferencia no invada su experiencia.','Ambos se benefician de acordar cuándo el juego es bienvenido y cuándo hace falta presencia genuina.'],
  'entp-vs-estp':['Dos personas rápidas pueden detectar oportunidades, pero no siempre mirar el mismo tipo de riesgo.','ENTP puede ensayar posibilidades conceptuales; ESTP puede actuar sobre la ocasión disponible.','El potencial crece cuando asignan a alguien la tarea de revisar consecuencias y compromisos.'],
  'entp-vs-esfp':['La energía social, el humor y la improvisación pueden hacer que esta pareja se sienta muy viva.','ENTP puede ampliar la conversación con una idea inesperada; ESFP puede llevarla a la experiencia del momento.','La relación se profundiza cuando también dejan lugar a lo serio y a los acuerdos que permanecen.'],
  'infj-vs-infp':['Dos estilos sensibles pueden compartir valores profundos y, aun así, procesar el conflicto de manera distinta.','INFJ puede buscar un patrón y una dirección; INFP puede proteger la honestidad de su respuesta personal.','La confianza aumenta cuando ninguno interpreta la reserva del otro como falta de afecto.'],
  'infj-vs-enfj':['Una visión orientada al significado y una capacidad de movilizar relaciones pueden entenderse con facilidad.','INFJ puede necesitar espacio para elaborar; ENFJ puede exteriorizar antes lo que ve y pedir una respuesta.','El vínculo se equilibra al respetar la introspección y mantener visibles las necesidades compartidas.'],
  'infj-vs-istj':['La intuición sobre lo que podría ocurrir y la atención a lo comprobable pueden complementarse con paciencia.','INFJ puede hablar de una dirección emergente; ISTJ puede pedir detalles, precedentes y responsabilidades.','Ambos avanzan cuando traducen una visión en pasos y dejan que los pasos informen la visión.'],
  'infj-vs-isfj':['La sensibilidad por las personas puede ser un punto de encuentro, aunque cada quien la exprese a su manera.','INFJ puede buscar el significado de una situación; ISFJ puede concentrarse en el cuidado concreto que hace falta ahora.','La relación gana calidez cuando reconocen ambos gestos como formas de atención.'],
  'infj-vs-estj':['La orientación a una visión humana y la claridad operativa pueden discrepar por la forma de avanzar.','INFJ puede pedir que se considere el propósito; ESTJ puede pedir una acción definida y realizable.','La colaboración mejora al nombrar tanto el valor que guía la decisión como el estándar que la hará posible.'],
  'infj-vs-esfj':['Dos estilos atentos a las relaciones pueden crear pertenencia, pero pueden evitar una diferencia por razones distintas.','INFJ puede callar para procesar; ESFJ puede suavizar para preservar la armonía.','La confianza se vuelve más sólida cuando invitan una opinión difícil antes de que se convierta en distancia.'],
  'infj-vs-istp':['La búsqueda de significado y la confianza en la experiencia inmediata pueden pedir traducción recíproca.','INFJ puede anticipar consecuencias humanas; ISTP puede responder al problema presente con una solución práctica.','Su diferencia se convierte en recurso cuando hablan tanto de la intención como de lo que funciona.'],
  'infj-vs-isfp':['La sensibilidad tranquila y la atención al sentido pueden crear una relación cuidadosa y poco ruidosa.','INFJ puede organizar una comprensión amplia; ISFP puede proteger la autenticidad de lo que se siente ahora.','Ambos se acercan más cuando expresan una necesidad antes de retirarse a procesarla.'],
  'infj-vs-estp':['La reflexión sobre el futuro y la respuesta directa al momento pueden contrastar de manera intensa.','INFJ puede necesitar tiempo para ver el patrón; ESTP puede necesitar acción para descubrir qué es posible.','Los acuerdos sobre pausa, riesgo y seguimiento permiten aprender del contraste sin competir por el ritmo.'],
  'infj-vs-esfp':['La profundidad reflexiva y la expresividad cercana pueden despertar curiosidad y ternura.','INFJ puede cuidar el significado oculto; ESFP puede cuidar la experiencia compartida y la energía de la conversación.','La relación se beneficia cuando la seriedad no apaga la alegría y la alegría no evita lo importante.'],
  'infp-vs-enfj':['La fidelidad a valores personales y la orientación al bienestar colectivo pueden compartir una intención de cuidado.','INFP puede necesitar conservar su propia voz; ENFJ puede querer construir una dirección común.','La relación florece cuando el apoyo no se convierte en presión y la individualidad no se vuelve silencio.'],
  'infp-vs-enfp':['Dos estilos imaginativos pueden reconocerse en su búsqueda de significado y posibilidad.','INFP puede procesar su emoción en privado; ENFP puede descubrirla al hablar y conectar ideas.','La cercanía crece con espacio para la profundidad y una forma sencilla de volver a los compromisos cotidianos.'],
  'infp-vs-istj':['La convicción íntima y la responsabilidad práctica pueden requerir curiosidad antes de llegar a un acuerdo.','INFP puede empezar por lo que siente correcto; ISTJ puede partir de los hechos, la obligación y el precedente.','Ambos ganan cuando convierten sus valores en peticiones concretas y sus reglas en razones comprensibles.'],
  'infp-vs-isfj':['La sensibilidad personal y el cuidado constante pueden construir un vínculo amable si también hacen visibles sus límites.','INFP puede necesitar espacio para ser auténtico; ISFJ puede expresar afecto a través de atención y servicio.','La reciprocidad mejora cuando cada persona pide lo que necesita en vez de esperar que se intuya.'],
  'infp-vs-estj':['La atención a la autenticidad y la preferencia por resultados claros pueden entrar en conflicto por el lenguaje y el ritmo.','INFP puede necesitar que una decisión respete un valor; ESTJ puede buscar que sea viable y ejecutable.','El entendimiento aumenta al tratar ambos criterios como partes legítimas de una decisión.'],
  'infp-vs-esfj':['La calidez y el deseo de cuidar pueden estar presentes en ambos, aunque la vida social tenga un peso diferente.','INFP puede preferir una conexión selectiva y profunda; ESFJ puede crear cercanía mediante participación y seguimiento.','La relación se fortalece cuando respetan las diferentes formas de pertenecer sin medir el afecto por la frecuencia.'],
  'infp-vs-istp':['La autenticidad sensible y el pragmatismo tranquilo pueden parecer hablar idiomas distintos al principio.','INFP puede compartir primero el significado personal; ISTP puede responder con una solución o con espacio.','La confianza surge cuando la ayuda práctica se acompaña de escucha y la emoción se formula en una petición clara.'],
});

const BATCH_THREE = Object.freeze({
  'infp-vs-isfp':['Dos sensibilidades personales pueden encontrarse con facilidad sin necesitar expresar ni decidir de la misma forma.','INFP puede buscar el significado de lo que siente; ISFP puede confiar en la experiencia presente y en lo que resulta auténtico ahora.','La cercanía se cuida cuando ambos ponen palabras a una necesidad antes de esperar que el otro la perciba.'],
  'infp-vs-estp':['La atención a los valores íntimos y la respuesta rápida a la oportunidad pueden parecer lejanas, pero ambas tienen algo que enseñar.','INFP puede necesitar considerar el impacto antes de actuar; ESTP puede descubrir posibilidades al ponerse en movimiento.','El respeto aumenta cuando la pausa no se llama indecisión y la acción no se llama falta de profundidad.'],
  'infp-vs-esfp':['La imaginación reservada y la expresividad del momento pueden crear una conexión cálida y creativa.','INFP puede cuidar una emoción en privado; ESFP puede compartirla al vivirla con otras personas.','El vínculo gana estabilidad al combinar espontaneidad con conversaciones sinceras sobre lo que importa.'],
  'enfj-vs-enfp':['El deseo de inspirar y la apertura a nuevas posibilidades pueden hacer que esta relación tenga mucha energía.','ENFJ puede buscar una dirección que incluya al grupo; ENFP puede seguir una oportunidad que acaba de cobrar sentido.','Su mejor versión aparece cuando la inspiración se acompaña de prioridades realistas y libertad para aportar.'],
  'enfj-vs-istj':['La atención a las personas y el sentido de responsabilidad pueden coincidir, aunque el modo de organizarse sea distinto.','ENFJ puede empezar por el propósito compartido; ISTJ puede empezar por el deber, los datos y el procedimiento.','La colaboración se fortalece al convertir una intención humana en acuerdos claros y sostenibles.'],
  'enfj-vs-isfj':['Dos personas orientadas al cuidado pueden construir un vínculo muy atento, siempre que no oculten sus propias necesidades.','ENFJ puede movilizar conversación y apoyo; ISFJ puede sostenerlo con constancia en los detalles.','La reciprocidad crece cuando cuidar no significa asumir todo en silencio.'],
  'enfj-vs-estj':['La capacidad de reunir personas y la de ordenar la ejecución pueden ser muy potentes si se escuchan mutuamente.','ENFJ puede pedir participación antes de decidir; ESTJ puede pedir una decisión que se traduzca en tareas.','Un proceso claro que también abra espacio para las voces afectadas integra sus fortalezas.'],
  'enfj-vs-esfj':['La calidez, la organización social y la voluntad de ayudar pueden crear una fuerte sensación de comunidad.','ENFJ puede mirar el desarrollo a largo plazo; ESFJ puede atender lo que el grupo necesita de forma inmediata.','El desafío compartido es sostener límites para que la generosidad no se transforme en agotamiento.'],
  'enfj-vs-istp':['La conexión humana explícita y la independencia práctica pueden requerir paciencia para entenderse.','ENFJ puede invitar a hablar de la experiencia; ISTP puede mostrar cuidado resolviendo un problema o tomando distancia para pensar.','La confianza crece cuando las intenciones se nombran sin exigir que se expresen de una sola manera.'],
  'enfj-vs-isfp':['La sensibilidad interpersonal y la autenticidad serena pueden encontrarse en una relación de mucho cuidado.','ENFJ puede organizar apoyo y conversación; ISFP puede necesitar elegir cuándo y cómo comparte lo que siente.','Ambos avanzan cuando la cercanía deja sitio para la autonomía y los límites se reciben con respeto.'],
  'enfj-vs-estp':['La atención a la participación y la habilidad de actuar en el momento pueden crear una relación de gran impulso.','ENFJ puede considerar el efecto sobre todas las personas; ESTP puede identificar una oportunidad que exige respuesta inmediata.','La coordinación mejora cuando acuerdan qué requiere consulta y qué puede probarse con rapidez.'],
  'enfj-vs-esfp':['Dos estilos expresivos pueden hacer que las personas se sientan vistas, incluidas y con más energía.','ENFJ puede conectar una experiencia con un propósito; ESFP puede hacer que ese propósito se sienta vivo en el presente.','La relación se profundiza cuando también reservan espacio para límites, prioridades y conversaciones menos ligeras.'],
  'enfp-vs-istj':['La imaginación expansiva y la confianza en lo probado pueden desafiarse y complementarse a la vez.','ENFP puede abrir una posibilidad antes de conocer todos los detalles; ISTJ puede pedir evidencia, orden y continuidad.','El entendimiento crece cuando la novedad se convierte en un plan manejable y la cautela permite probar algo nuevo.'],
  'enfp-vs-isfj':['La energía por explorar y una forma de cuidar estable pueden necesitar acordar qué significa estar presentes.','ENFP puede necesitar libertad y conversación abierta; ISFJ puede valorar constancia, gestos concretos y previsibilidad.','La relación se vuelve más segura cuando hacen explícitos los compromisos sin reducir la curiosidad.'],
  'enfp-vs-estj':['La búsqueda de posibilidades y la orientación a resultados pueden diferir más en el proceso que en el deseo de avanzar.','ENFP puede descubrir prioridades al explorar; ESTJ puede necesitar fijarlas para coordinar acción.','Ambos ganan cuando alternan una fase abierta de ideas con una fase clara de compromiso.'],
  'enfp-vs-esfj':['La sociabilidad, el entusiasmo y la atención a las relaciones pueden ser un punto de encuentro natural.','ENFP puede buscar lo novedoso y significativo; ESFJ puede cuidar el ritmo y las responsabilidades que sostienen al grupo.','La confianza crece cuando la conexión no depende solo de la energía del momento.'],
  'enfp-vs-istp':['La exploración de posibilidades y el pragmatismo directo pueden sorprenderse mutuamente con enfoques que no esperaban.','ENFP puede hablar para encontrar sentido; ISTP puede actuar para averiguar qué funciona.','Su vínculo mejora cuando la imaginación llega a una prueba y la prueba deja espacio para una conversación personal.'],
  'enfp-vs-isfp':['La apertura emocional y la sensibilidad a la experiencia pueden crear un ambiente creativo y acogedor.','ENFP puede compartir lo que imagina de inmediato; ISFP puede necesitar sentir si una idea le encaja antes de responder.','La cercanía se fortalece con libertad, tacto y una petición clara cuando algo resulta importante.'],
  'enfp-vs-estp':['Dos estilos vivos pueden alimentar la aventura, la improvisación y el deseo de aprovechar una oportunidad.','ENFP puede seguir una posibilidad por su sentido; ESTP puede seguirla porque está disponible ahora.','El crecimiento compartido consiste en disfrutar el impulso sin perder de vista los acuerdos que sostienen la confianza.'],
  'enfp-vs-esfp':['La expresividad, la curiosidad y el deseo de conexión pueden hacer que esta pareja disfrute mucho de lo compartido.','ENFP puede imaginar futuras alternativas; ESFP puede enriquecer lo que ocurre en el presente.','El reto es elegir alguna prioridad para que el entusiasmo no deje sin cuidado lo que ambos valoran.'],
  'istj-vs-isfj':['La fiabilidad, el cuidado y la atención a lo concreto pueden crear una base de confianza muy sólida.','ISTJ puede centrarse en responsabilidades y procedimientos; ISFJ puede notar cómo esas responsabilidades afectan a las personas.','Su relación se vuelve más flexible cuando no confunden constancia con la obligación de mantener todo igual.'],
  'istj-vs-estj':['Dos estilos responsables pueden avanzar con claridad, aunque no siempre compartan el mismo alcance de una decisión.','ISTJ puede preferir confirmar hechos y riesgos; ESTJ puede querer organizar rápidamente la ejecución.','La cooperación mejora al decidir qué requiere verificación y qué puede delegarse con confianza.'],
  'istj-vs-esfj':['La responsabilidad práctica y la atención a la convivencia pueden coincidir en muchos valores cotidianos.','ISTJ puede mostrar compromiso al cumplir; ESFJ puede hacerlo al mantener a las personas conectadas.','El vínculo gana profundidad cuando reconocen que ambas formas de cuidado merecen ser nombradas.'],
  'istj-vs-istp':['La disciplina de lo probado y la disposición a ajustar sobre la marcha pueden debatir qué cuenta como una buena solución.','ISTJ puede pedir método y precedentes; ISTP puede preferir observar el problema real y repararlo.','El respeto aparece cuando la experiencia práctica informa la norma y la norma ofrece una base fiable.'],
  'istj-vs-isfp':['El sentido del deber y la autenticidad personal pueden necesitar una conversación clara sobre expectativas.','ISTJ puede valorar lo acordado y previsible; ISFP puede necesitar que una decisión respete su ritmo y su forma propia de vivirla.','La relación se beneficia al reemplazar las suposiciones por acuerdos sencillos y concretos.'],
  'istj-vs-estp':['La planificación cuidadosa y la respuesta rápida a lo inesperado pueden generar contraste y aprendizaje.','ISTJ puede proteger la estabilidad antes de actuar; ESTP puede detectar cuándo una oportunidad no espera.','Los dos se complementan mejor cuando acuerdan umbrales de riesgo y revisan lo aprendido después.'],
  'istj-vs-esfp':['La fiabilidad tranquila y la energía expresiva pueden mostrar afecto de maneras muy distintas.','ISTJ puede ofrecer continuidad y presencia; ESFP puede traer calidez, celebración y atención al ambiente.','La conexión se fortalece cuando los planes incluyen disfrute y la espontaneidad honra los compromisos.'],
  'isfj-vs-estj':['El cuidado constante y la claridad para organizar pueden formar una alianza práctica y protectora.','ISFJ puede advertir necesidades antes de que se pidan; ESTJ puede establecer el orden necesario para responder.','Ambos crecen cuando dejan espacio a una diferencia honesta en lugar de asumir que el deber resuelve todo.'],
  'isfj-vs-esfj':['La atención a las personas y el deseo de sostener la armonía pueden hacer que esta relación se sienta muy cercana.','ISFJ puede cuidar con discreción; ESFJ puede hacerlo de forma más visible y social.','Su bienestar mejora cuando comparten responsabilidades y no confunden ser necesarios con estar obligados.'],
  'isfj-vs-istp':['El cuidado previsible y la independencia práctica pueden requerir aclarar cuánto contacto y espacio necesita cada persona.','ISFJ puede buscar seguridad a través de seguimiento; ISTP puede valorar libertad y ayuda concreta sin demasiada explicación.','La confianza se construye al cumplir lo acordado y decir cuándo hace falta una pausa.'],
  'isfj-vs-isfp':['Dos sensibilidades discretas pueden sentirse cómodas con una cercanía que no necesita demasiado ruido.','ISFJ puede cuidar mediante constancia; ISFP puede expresar afecto a través de presencia, belleza o un gesto espontáneo.','El vínculo se mantiene sano cuando también se habla de los límites y no solo de lo que cada quien ofrece.'],
  'isfj-vs-estp':['La cautela protectora y la energía de acción pueden mirar de forma distinta una misma oportunidad.','ISFJ puede pensar primero en las consecuencias para las personas cercanas; ESTP puede reaccionar a lo que el momento permite.','La colaboración se vuelve más segura cuando comparten información antes de actuar y revisan cómo resultó.'],
  'isfj-vs-esfp':['La atención cuidadosa y la alegría por compartir pueden crear un vínculo acogedor y afectuoso.','ISFJ puede sostener la logística y la memoria de lo importante; ESFP puede dar vida a la experiencia y acercar a las personas.','La relación gana equilibrio cuando ambos protegen su energía y expresan una necesidad antes de agotarse.'],
  'estj-vs-esfj':['La organización, la responsabilidad y la atención al grupo pueden hacer que esta pareja funcione con mucha eficacia.','ESTJ puede concentrarse en el estándar y la tarea; ESFJ puede cuidar la recepción, el ánimo y la cooperación.','El resultado mejora cuando la productividad incluye preguntas sobre la experiencia de quienes participan.'],
  'estj-vs-istp':['La necesidad de estructura y la preferencia por una solución práctica pueden discrepar cuando aparecen imprevistos.','ESTJ puede querer un proceso claro; ISTP puede actuar primero para comprobar la situación.','Ambos se benefician de acordar qué decisiones necesitan protocolo y cuáles exigen adaptación inmediata.'],
  'estj-vs-isfp':['La dirección directa y la necesidad de autenticidad pueden pedir mucha precisión en el modo de comunicarse.','ESTJ puede expresar una expectativa sin rodeos; ISFP puede necesitar que la crítica respete su experiencia y su autonomía.','La relación mejora cuando la claridad no se vuelve dureza y la sensibilidad no queda sin voz.'],
  'estj-vs-estp':['Dos estilos prácticos pueden reconocer rápido cómo avanzar, aunque difieran en planificación y riesgo.','ESTJ puede buscar organización y control de seguimiento; ESTP puede aprovechar una apertura inmediata.','Su fuerza está en combinar rapidez con responsabilidad y en revisar quién mantiene lo que se inició.'],
  'estj-vs-esfp':['La estructura para cumplir y la energía para conectar pueden equilibrarse en proyectos y relaciones vivas.','ESTJ puede proteger la prioridad; ESFP puede recordar el efecto que tiene el proceso sobre las personas.','Ambos crecen cuando los acuerdos dejan lugar para el disfrute y el disfrute no desplaza la responsabilidad.'],
  'esfj-vs-istp':['La búsqueda de cercanía y la preferencia por autonomía pueden necesitar acuerdos explícitos, no interpretaciones.','ESFJ puede hacer seguimiento como forma de cuidado; ISTP puede necesitar espacio para responder a su propio ritmo.','El respeto aumenta cuando la presencia se ofrece sin invadir y el espacio se comunica sin desaparecer.'],
  'esfj-vs-isfp':['La calidez social y una sensibilidad reservada pueden enriquecerse si no imponen una sola forma de participar.','ESFJ puede crear inclusión mediante invitaciones; ISFP puede valorar elegir cuándo compartir.','La conexión se vuelve más auténtica cuando la atención se acompaña de permiso para ser diferente.'],
  'esfj-vs-estp':['La sociabilidad organizada y la acción espontánea pueden generar mucha actividad y algunas diferencias de ritmo.','ESFJ puede cuidar que nadie quede fuera; ESTP puede responder a la oportunidad que aparece.','El vínculo se fortalece con acuerdos sencillos sobre compromisos, límites y seguimiento.'],
  'esfj-vs-esfp':['Dos estilos cálidos pueden disfrutar mucho de hacer que otras personas se sientan incluidas.','ESFJ puede sostener la relación con constancia; ESFP puede llenarla de energía, humor y momentos memorables.','La relación se vuelve más sólida cuando no evitan un tema difícil solo para conservar un buen ambiente.'],
  'istp-vs-isfp':['La independencia tranquila y la autenticidad sensible pueden compartir una forma poco teatral de estar cerca.','ISTP puede responder con soluciones o acciones; ISFP puede responder desde cómo una situación se siente de verdad.','La comprensión crece cuando la ayuda práctica también pregunta por la experiencia y la emoción se expresa con claridad.'],
  'istp-vs-estp':['Dos estilos atentos a la realidad inmediata pueden disfrutar de la acción, el reto y la capacidad de ajustarse.','ISTP puede observar antes de intervenir; ESTP puede intervenir para aprender de la respuesta.','Su reto común es no confundir habilidad para improvisar con no necesitar compromisos ni revisión.'],
  'istp-vs-esfp':['La calma resolutiva y la expresividad cercana pueden ofrecer una combinación de libertad y vitalidad.','ISTP puede mostrar afecto haciendo algo útil; ESFP puede hacerlo creando una experiencia compartida.','La relación mejora cuando ambos nombran lo que necesitan antes de que la distancia o la distracción hablen por ellos.'],
  'isfp-vs-estp':['La sensibilidad al momento y el impulso por actuar pueden coincidir en el gusto por una experiencia viva.','ISFP puede necesitar que una elección se sienta auténtica; ESTP puede necesitar comprobar qué oportunidad permite ahora.','El vínculo se cuida cuando la espontaneidad respeta los límites y los límites se explican sin juicio.'],
  'isfp-vs-esfp':['La creatividad, la atención a la experiencia y una forma personal de conectar pueden ser un terreno compartido.','ISFP puede vivir la emoción de manera más privada; ESFP puede hacerla visible y contagiosa.','La cercanía gana profundidad cuando cada persona puede tener su ritmo sin medir el afecto por la intensidad.'],
  'estp-vs-esfp':['Dos presencias activas pueden encontrar mucha alegría, movimiento y facilidad para crear experiencias memorables.','ESTP puede orientarse a la oportunidad y el reto; ESFP puede orientarse a la conexión y la energía del momento.','Su crecimiento consiste en reservar atención para las consecuencias, los acuerdos y las conversaciones que llegan después de la diversión.'],
});

const PAIRS = Object.freeze({ ...BATCH_ONE, ...BATCH_TWO, ...BATCH_THREE });

export const spanishComparisonSlugs = Object.freeze(Object.keys(PAIRS));
export function isSpanishComparisonPair(first, second) { return spanishComparisonSlugs.includes(pairSlug(first, second)); }

function spanishProfile(code) { return getPersonalityGuideContent('es', code).profile; }
function seo(first, second, narrative) {
  const pair = `${first.code} y ${second.code}`;
  return { title: `${pair}: relación, comunicación y comparación | KalQLater`, description: `${pair}: una guía de reflexión sobre comunicación, decisiones, amistad, trabajo y crecimiento compartido. ${narrative[0]}` };
}

function spanishContent(first, second, narrative) {
  const pair = `${first.code} y ${second.code}`;
  const aStrength = first.strengths[0].toLowerCase(); const bStrength = second.strengths[0].toLowerCase();
  return {
    eyebrow: 'Relación · amistad · comparación', helper: `${first.displayName} (${first.code}) y ${second.displayName} (${second.code}): una lectura para observar patrones, contexto y elecciones.`, intro: narrative[0],
    snapshot: [['Relación', 'Ritmos que se conocen', narrative[1]], ['Amistad', 'Curiosidad compartida', `La conexión puede crecer al respetar ${aStrength} y ${bStrength}.`], ['Comunicación', 'Decir la intención', 'Explicar el motivo de una conversación evita que la otra persona tenga que adivinarlo.'], ['Decisiones', 'Dos perspectivas', 'Poner por escrito opciones, riesgos y una fecha de revisión puede dar cabida a ambos estilos.'], ['Conflicto', 'Reparación posible', 'Una pausa y un siguiente paso concreto suelen cuidar mejor el vínculo que intentar ganar.'], ['Crecimiento', 'Aprendizaje mutuo', narrative[2]]].map((item, index) => ({ icon: ['♡','☻','↔','◇','↺','↗'][index], title:item[0], label:item[1], text:item[2] })),
    sections: [
      ['Relación, citas y largo plazo', `${narrative[0]} En una relación, la confianza se construye al hablar con claridad de afecto, tiempo propio, responsabilidades y expectativas, en lugar de suponerlas.`, `Pista para conversar: ¿qué necesita cada persona para sentirse acompañada sin perder su espacio?`],
      ['Amistad', `${first.code} y ${second.code} pueden encontrar cercanía en intereses compartidos y en la libertad de mostrar su estilo sin convertirlo en una regla. Un período de silencio o mucho entusiasmo no tiene un único significado: conviene preguntar antes de interpretarlo.`, 'Después de una confusión, prueba con un mensaje breve: «Quiero entender qué era importante para ti».'],
      ['Trabajo, liderazgo y colaboración', `${first.code} puede aportar ${first.workStyle[0].toLowerCase()}, mientras que ${second.code} puede acercarse desde ${second.workStyle[0].toLowerCase()}. Definir roles, autoridad de decisión y momentos de revisión transforma esa diferencia en una colaboración más amplia.`, 'Práctica: anoten opciones, nombren a la persona responsable y acuerden cuándo revisarán la decisión.'],
      ['Guía de comunicación', `${first.code} y ${second.code} pueden expresarse y procesar a ritmos distintos. Preguntar por la experiencia, la evidencia o el valor que sostiene una conclusión ayuda a escuchar más allá de la respuesta final. Si un mensaje delicado crece demasiado por escrito, conviene trasladarlo a una conversación con más contexto.`, 'Para dar retroalimentación: describe el efecto, ofrece un ejemplo y formula una petición concreta.'],
      ['Forma de decidir', `${first.code} puede inclinarse por ${first.developmentTips[0].toLowerCase()}; ${second.code} puede beneficiarse de ${second.developmentTips[0].toLowerCase()}. No es una medida de cuidado ni de capacidad: es una invitación a hacer visibles los criterios antes de comprometerse.`, 'Cuando discrepen, separen lo reversible de lo difícil de cambiar y decidan qué evidencia necesitan.'],
      ['Conflicto, presión y reparación', `Bajo presión, ${first.code} puede necesitar un modo distinto de procesar que ${second.code}. Hablar de los desencadenantes cuando hay calma y volver a una petición concreta reduce la tendencia a atribuir malas intenciones.`, 'Práctica de reparación: pausa, reconoce tu parte y propone un cambio posible.'],
      ['Lo que pueden aprender', narrative[2], 'Esta comparación no define el futuro de una relación. La experiencia, los valores, los límites y las elecciones importan más que una etiqueta.'],
    ],
    misconceptions: [[`Mito: ${pair} son demasiado diferentes para entenderse.`, 'Realidad: las diferencias pueden complementar una relación cuando hay respeto, conversación y metas compartidas.'], ['Mito: el tipo decide el resultado de una relación.', 'Realidad: la confianza, los límites, la madurez y los hábitos cotidianos influyen mucho más.'], ['Mito: pedir perdón primero es perder.', 'Realidad: empezar una reparación puede proteger la seguridad de la relación.']],
    percentage: 'Por qué KalQLater no usa porcentajes de compatibilidad', percentageText: 'Las relaciones humanas no caben en un número. La conexión depende de la comunicación, los valores, la madurez, el momento vital, el comportamiento y los objetivos compartidos. Esta guía propone conversaciones y hábitos, no un veredicto.',
    faq: [[`¿${pair} son compatibles?`, `${pair} no se pueden resumir en un porcentaje. ${narrative[2]} La experiencia dependerá de cómo cuiden la comunicación, los valores y las expectativas cotidianas.`], [`¿${pair} pueden llevarse bien?`, 'Sí, especialmente si tratan sus diferentes ritmos como información y no como un defecto.'], [`¿${pair} pueden tener una relación?`, 'Pueden. Como en cualquier relación, la confianza, los límites, la reciprocidad y la reparación tras conversaciones difíciles son más importantes que el tipo.'], ['¿Pueden ser buenos amigos?', 'La amistad suele crecer cuando ambos crean experiencias compartidas y respetan las diferentes necesidades de cercanía o espacio.'], ['¿Pueden colaborar en el trabajo?', 'Sí, si aclaran roles, criterios de decisión y una forma de revisar los acuerdos.'], ['¿Quién pide perdón primero?', 'El tipo no lo determina. Una reparación saludable la inicia quien puede reconocer su parte.'], ['¿Cómo pueden decidir mejor juntos?', 'Hagan visibles los criterios, separen los riesgos reversibles de los compromisos mayores y acuerden una revisión.'], ['¿Cómo pueden detener una discusión?', 'Tomen una pausa, hablen de un asunto cada vez y definan un siguiente paso concreto.'], ['¿Pueden emprender juntos?', 'Sí, si acuerdan la autoridad de decisión, el riesgo que asumirán, el ritmo de comunicación y la responsabilidad por el seguimiento.'], ['¿Una persona puede cambiar por la otra?', 'Las personas pueden aprender entre sí, pero cambiar a alguien no debería ser el objetivo. El objetivo es una comprensión más útil y más opciones.'], ['¿Por qué KalQLater no usa porcentajes?', 'Porque la relación se construye con comportamiento, valores, comunicación y contexto, no con una cifra inventada.']],
    ui: { snapshot:'Vista rápida', signals:'Señales útiles para esta pareja', instead:'En lugar de un número', myths:'Mitos y realidad', beyond:'Mira más allá de la etiqueta', questions:'Preguntas frecuentes', explore:'Sigue explorando', further:'Lleva esta comparación un paso más allá', related:'Comparaciones relacionadas', test:'Realiza el test de personalidad', another:'Explora otra comparación', career:'Guía de carrera', communication:'Insights de comunicación', hub:'Centro de insights', compare:'Comparar', and:'y', pattern:'Comprende el patrón. Elige la próxima conversación.', reflection:'Esta es una herramienta de reflexión, no un veredicto sobre una relación, una capacidad o el futuro.', myth:'Mito', reality:'Realidad' },
  };
}

export function getComparisonContent(locale, firstCode, secondCode, base = null) {
  if (locale === 'en' || locale === 'hi') {
    if (base) return base;
    const first = personalityProfile(firstCode, locale); const second = personalityProfile(secondCode, locale);
    if (!first || !second) throw new Error(`Comparison unavailable: ${firstCode}/${secondCode}/${locale}`);
    return Object.freeze({ first, second, content: comparisonContent({ firstProfile: first, secondProfile: second, insight: comparisonProfile(firstCode, secondCode, locale), locale }) });
  }
  if (locale !== 'es') throw new Error(`Comparison locale unavailable: ${locale}`);
  const slug = pairSlug(firstCode, secondCode); const narrative = PAIRS[slug];
  if (!narrative) throw new Error(`Spanish comparison unavailable: ${slug}`);
  const first = spanishProfile(firstCode); const second = spanishProfile(secondCode);
  return Object.freeze({ first, second, content: spanishContent(first, second, narrative), seo: seo(first, second, narrative) });
}
