/** Unpublished Spanish homepage package; no English fallback is permitted. */
const spanishHomepage = Object.freeze({
  eyebrow: '16 tipos de personalidad · Gratis · Sin registro', title: 'Conoce mejor a la persona que ya eres', body: 'Responde 60 preguntas con honestidad en unos diez minutos y descubre qué tipo de los 16 se parece más a ti. Después, úsalo como una invitación a entender tus patrones con más perspectiva.', start: 'Empezar el test gratis', types: 'Explorar los 16 tipos', trust: 'Una experiencia de reflexión privada y cuidada', featuresTitle: '¿Qué puedes descubrir aquí?',
  features: [['sparkles', 'Un marco claro para observarte', 'Cuatro dimensiones —E/I, S/N, T/F y J/P— ayudan a poner palabras a preferencias cotidianas.'], ['people', 'Contenido disponible en dos idiomas', 'Las preguntas y los perfiles también están disponibles en inglés y en hindi.'], ['layers', 'Una lectura personal', 'Explora preferencias, fortalezas, áreas de desarrollo, temas profesionales y maneras de relacionarte.'], ['shield', 'La privacidad primero', 'No necesitas una cuenta para completar la evaluación. Tus respuestas siguen siendo tuyas.']],
  dimensionTitle: 'Cuatro dimensiones de la personalidad', dimensionBody: 'Tu tipo reúne preferencias que pueden aparecer en cuatro patrones humanos.', dimensions: [['bolt', 'E / I', 'Extraversión e introversión', 'De dónde suele venir tu energía', 'teal'], ['layers', 'S / N', 'Sensación e intuición', 'Cómo acostumbras a incorporar información', 'saffron'], ['heart', 'T / F', 'Pensamiento y sentimiento', 'Cómo sueles orientar tus decisiones', 'plum'], ['compass', 'J / P', 'Juicio y percepción', 'Cómo te relacionas con el mundo exterior', 'teal']],
  insightsEyebrow: 'Más allá de la personalidad', insightsTitle: 'Observa los hábitos que hay detrás de tus patrones.', insightsBody: 'La personalidad puede ser un buen comienzo. Perspectivas de Comunicación te ayuda a mirar cómo esos patrones se hacen presentes en conversaciones reales.', insightsLive: 'Disponible ahora', insightsTool: 'Perspectivas de Comunicación', insightsToolBody: 'Una reflexión práctica sobre claridad, escucha, desacuerdo y adaptación.', insightsCta: 'Explorar Perspectivas de Comunicación', insightsSoon: 'Próximamente', insightsPlanned: ['Patrones de decisión', 'Energía en el trabajo', 'Dinámicas de relación'],
  communityEyebrow: 'Más allá del resultado', communityTitle: 'Lleva tus reflexiones a las conversaciones que importan.', communityBody: 'Explora dinámicas de relación, conoce a personas con intereses afines y descubre oportunidades con contexto de personalidad: siempre para reflexionar, nunca para etiquetar.', community: 'Explorar la comunidad', compare: 'Comparar personalidades', jobs: 'Ver oportunidades', finalTitle: '¿Listo para empezar?', finalBody: 'No existe un tipo correcto. Existe una manera más útil de entender tus propios patrones.', architect: 'El arquitecto', architectBody: 'Un estratega sereno que entiende los sistemas en profundidad.', map: 'Un mapa práctico de tus preferencias', allInsights: 'Ver todas las perspectivas', seo: { title: 'Test de personalidad para conocerte mejor | KalQLater', description: 'Explora tus patrones de personalidad con una evaluación original de 16 tipos diseñada para la reflexión y el desarrollo personal.' },
});

export function homepageContent(locale) {
  if (locale !== 'es') throw new Error(`Missing authored homepage locale: ${locale}`);
  return spanishHomepage;
}
