import React, { useState } from 'react';
import axios from 'axios';
import { CheckCircle2, Send } from 'lucide-react';
import { useLang } from '../context/LangContext';

import { API_URL } from '../services/apiConfig';
const API = API_URL;
const initial = { name: '', email: '', subject: '', message: '', website: '' };
const copy = {
    en: { eyebrow: 'Get in touch', title: 'Contact us', sub: 'Questions, feedback, or partnership ideas — we would love to hear from you.', name: 'Name', email: 'Email', subject: 'Subject', message: 'Message', send: 'Send message', sending: 'Sending…', success: "Thank you for contacting us. We'll get back to you soon.", error: 'We could not send your message right now. Please try again later.', required: 'Please complete all required fields.', invalid: 'Please enter a valid email address.' },
    hi: { eyebrow: 'संपर्क करें', title: 'हमसे संपर्क करें', sub: 'सवाल, फीडबैक या साझेदारी के विचार — हमें आपसे सुनकर खुशी होगी।', name: 'नाम', email: 'ईमेल', subject: 'विषय', message: 'संदेश', send: 'संदेश भेजें', sending: 'भेजा जा रहा है…', success: 'संपर्क करने के लिए धन्यवाद। हम जल्द ही आपसे संपर्क करेंगे।', error: 'अभी आपका संदेश नहीं भेजा जा सका। कृपया बाद में प्रयास करें।', required: 'कृपया सभी आवश्यक फ़ील्ड भरें।', invalid: 'कृपया सही ईमेल दर्ज करें।' },
};

export default function Contact() {
    const { lang } = useLang(); const t = copy[lang] || copy.en;
    const [form, setForm] = useState(initial); const [status, setStatus] = useState('idle'); const [error, setError] = useState(''); const [successMessage, setSuccessMessage] = useState('');
    const [startedAt] = useState(() => Date.now());
    const update = (event) => setForm((current) => ({ ...current, [event.target.name]: event.target.value }));
    const submit = async (event) => { event.preventDefault(); setError(''); setSuccessMessage(''); const emailOk = /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(form.email); if (!form.name || !form.email || !form.subject || !form.message) { setError(t.required); return; } if (!emailOk) { setError(t.invalid); return; } setStatus('loading'); try { const response = await axios.post(`${API}/contact`, { ...form, started_at: startedAt }); setSuccessMessage(response.data.message || t.success); setStatus('success'); setForm(initial); } catch { setStatus('error'); setError(t.error); } };
    const cls = lang === 'hi' ? 'font-body-hi' : ''; const clsH = lang === 'hi' ? 'font-display-hi' : 'font-display';
    return <div className="max-w-3xl mx-auto px-4 py-14 sm:px-6 lg:px-8"><header className="max-w-xl"><p className={`text-xs font-semibold uppercase tracking-[.24em] text-brand-teal ${cls}`}>{t.eyebrow}</p><h1 className={`mt-3 text-4xl text-brand-ink sm:text-5xl ${clsH}`}>{t.title}</h1><p className={`mt-4 text-brand-subtle ${cls}`}>{t.sub}</p></header><form onSubmit={submit} className="mt-10 rounded-[2rem] border border-brand-line bg-white p-6 shadow-[0_20px_50px_rgba(45,40,37,.06)] sm:p-8" noValidate><div className="grid gap-5 sm:grid-cols-2"><Field label={t.name} name="name" value={form.name} onChange={update} maxLength={100} required /><Field label={t.email} name="email" value={form.email} onChange={update} maxLength={254} type="email" required /><Field label={t.subject} name="subject" value={form.subject} onChange={update} maxLength={150} required /></div><Field label={t.message} name="message" value={form.message} onChange={update} maxLength={5000} multiline required /><div className="absolute -left-[10000px]" aria-hidden="true"><label>Website<input name="website" value={form.website} onChange={update} tabIndex="-1" autoComplete="off" /></label></div>{error && <p role="alert" className={`mt-5 text-sm text-[#B35841] ${cls}`}>{error}</p>}{status === 'success' && <p role="status" className={`mt-5 flex items-center gap-2 text-sm text-brand-teal ${cls}`}><CheckCircle2 size={17} />{successMessage}</p>}<button type="submit" disabled={status === 'loading' || status === 'success'} className={`mt-6 inline-flex items-center gap-2 rounded-full bg-brand-teal px-6 py-3 text-white disabled:opacity-60 ${cls}`}><Send size={16} />{status === 'loading' ? t.sending : t.send}</button></form></div>;
}
function Field({ label, name, value, onChange, maxLength, required, type = 'text', multiline = false }) { const shared = { name, value, onChange, maxLength, required, className: 'mt-2 w-full rounded-2xl border border-brand-line bg-brand-bg px-4 py-3 text-brand-ink outline-none focus:border-brand-teal focus:ring-2 focus:ring-brand-teal/20' }; return <label className={`block mt-5 ${name !== 'message' ? 'sm:first:mt-0' : ''}`}><span className="text-sm font-medium text-brand-ink">{label}</span>{multiline ? <textarea {...shared} rows="6" /> : <input {...shared} type={type} />}</label>; }
