import Link from 'next/link';
import { notFound } from 'next/navigation';
import { JsonLd } from '../../../../../components/JsonLd';
import { INTJ_CAREERS } from '../../../../../data/intj-careers';
import { breadcrumbJsonLd, pageMetadata } from '../../../../../lib/metadata';
import { isLocale, localePath, productionAppUrl } from '../../../../../lib/site';

export const dynamicParams = false;
export function generateStaticParams() { return [{ locale: 'en' }, { locale: 'hi' }]; }

export async function generateMetadata({ params }) {
  const { locale } = await params;
  if (!isLocale(locale)) return {};
  const content = INTJ_CAREERS[locale];
  return pageMetadata({ locale, path: 'personality/intj/careers', title: content.title, description: content.description });
}

const COPY = {
  en: {
    eyebrow: 'INTJ Career Guide', crumb: 'Careers', title: 'Best Careers for INTJ',
    hero: 'A guide for exploring work that may reward systems thinking, focused investigation and purposeful improvement.',
    disclaimer: 'Personality is one career-exploration input—not proof of ability, qualification or future success.',
    top: 'Start here: career directions worth investigating', all: 'View all career directions', compass: 'Career Compass', compassNote: 'Common work-style preferences—not a test score.',
    explorer: 'Career Path Explorer', comparison: 'Quick comparison', environment: 'Where work may feel sustainable', formats: 'Choose the format, not a stereotype',
    skills: 'Skills that widen your options', stages: 'Choose by career stage', industries: 'Industries to explore', jobs: 'Current opportunities to explore', faq: 'Questions worth asking',
    guide: 'How to use this guide', finalTitle: 'Use personality as a starting point—not the final answer.', finalBody: 'Compare the daily work, required skills and real constraints before choosing a direction.',
    test: 'Take the test', jobsAction: 'Browse jobs', join: 'Join the Community', profile: 'INTJ personality page', compare: 'Compare INTJ and ENFP',
    useful: 'Useful strength', build: 'Build', watch: 'Watch for', type: 'Main work', independence: 'Independence', collaboration: 'Collaboration', setting: 'Environment', skill: 'Key skill',
    environmentNote: 'The right environment depends on the actual role, team and individual—not only personality type.',
    jobsEmpty: 'No matching public opportunities are listed right now.', post: 'Post a job',
    compassItems: [['Deep focus', 'Often important', 'Space to investigate before responding.'], ['Structured problem-solving', 'Often important', 'Clear constraints can make complexity workable.'], ['Independent ownership', 'Helpful', 'Ownership works best with visible decision context.'], ['Strategic collaboration', 'Depends on the role', 'Prepared conversations can sharpen the plan.']],
    spectrum: [['Independent work', 'Constant collaboration', 'Often comfortable: focused ownership with purposeful collaboration'], ['Conceptual thinking', 'Immediate practical execution', 'Often comfortable: connecting models to a real problem'], ['Flexible process', 'Defined systems', 'Often comfortable: clear systems with room to improve them'], ['Long-horizon work', 'Rapid feedback', 'Often comfortable: long-term direction with early feedback']],
    formatItems: [['Remote', 'Protected focus time', 'Isolation or delayed context', 'Write decisions down and create regular feedback rituals.'], ['Hybrid', 'Focus plus useful in-person problem-solving', 'Fragmented weeks', 'Agree what belongs in shared time.'], ['Office', 'Fast context and mentoring', 'Constant interruption', 'Protect concentration blocks in the calendar.']],
    roadmapItems: [['Build expertise', 'Develop depth in a problem domain you genuinely want to understand.', 'Choose one real case study or small project.'], ['Explain your thinking', 'Make your reasoning useful before it is fully polished.', 'Write a one-page recommendation for someone else.'], ['Test ideas earlier', 'Let reality shape the plan before effort compounds.', 'Share a rough experiment, not only the final answer.'], ['Work through people', 'Influence needs trust, context and follow-through.', 'Ask one stakeholder what would make the plan usable.'], ['Lead systems, not only tasks', 'Help others see ownership, decisions and outcomes clearly.', 'Delegate a decision with its context, not just its deadline.']],
    toolkit: ['Domain expertise', 'Writing', 'Stakeholder communication', 'Experimentation', 'Delegation', 'Mentoring', 'Decision-making'],
    stageItems: [['Student', 'Build evidence of curiosity and craft.', 'Try a course, project or practitioner conversation.', 'Choosing only for a prestigious title.'], ['Early career', 'Learn how work moves through a real team.', 'Ask for feedback on a visible contribution.', 'Waiting until your work is perfect to share.'], ['Career changer', 'Translate existing strengths into a new domain.', 'Test one low-risk project or shadowing conversation.', 'Assuming a label is a substitute for evidence.'], ['Manager', 'Turn strategic clarity into a team habit.', 'Delegate with context and invite disagreement early.', 'Solving every important problem alone.'], ['Founder or freelancer', 'Balance a long thesis with immediate customer learning.', 'Run one small market or user experiment.', 'Protecting the idea from useful challenge.']],
    checklist: ['Does the daily work interest me?', 'Does the environment fit how I work?', 'Will I build the required skills?', 'Does it fit real financial and life constraints?', 'Have I tested it through a small experiment?'],
    industryItems: [['Technology and platforms', 'Turn systems into useful tools.', 'Software engineer · systems architect', 'Rapid change can require frequent communication.'], ['Research and education', 'Pursue difficult questions with rigour.', 'Research scientist · learning designer', 'Feedback cycles may be long.'], ['Finance and analytics', 'Make evidence useful for decisions.', 'Financial analyst · risk specialist', 'Commercial pace can be demanding.'], ['Healthcare systems', 'Improve coordination in complex care work.', 'Health systems analyst · operations strategist', 'Human context matters as much as the model.'], ['Law and public policy', 'Explore rules and long-term consequences.', 'Policy researcher · legal researcher', 'Influence relies on accessible writing.'], ['Product and design', 'Connect systems insight to human needs.', 'UX researcher · product manager', 'Qualitative feedback cannot be skipped.']],
  },
  hi: {
    eyebrow: 'INTJ करियर गाइड', crumb: 'करियर', title: 'INTJ के लिए करियर दिशाएँ',
    hero: 'ऐसे काम की खोज के लिए गाइड जिसमें सिस्टम सोच, केंद्रित जाँच और उद्देश्यपूर्ण सुधार उपयोगी लग सकता है।',
    disclaimer: 'व्यक्तित्व करियर खोज का एक इनपुट है—क्षमता, पात्रता या भविष्य की सफलता का प्रमाण नहीं।',
    top: 'यहाँ से शुरू करें: खोजने योग्य करियर दिशाएँ', all: 'सभी करियर दिशाएँ देखें', compass: 'करियर कंपास', compassNote: 'सामान्य कार्य-शैली पसंद—टेस्ट स्कोर नहीं।',
    explorer: 'करियर पथ खोजें', comparison: 'त्वरित तुलना', environment: 'कहाँ काम टिकाऊ लग सकता है', formats: 'फॉर्मेट चुनें, रूढ़ि नहीं',
    skills: 'ऐसे कौशल जो विकल्प बढ़ाएँ', stages: 'करियर चरण के अनुसार चुनें', industries: 'खोजने योग्य उद्योग', jobs: 'वर्तमान अवसर खोजें', faq: 'सोचने योग्य प्रश्न',
    guide: 'इस गाइड का उपयोग कैसे करें', finalTitle: 'व्यक्तित्व को शुरुआती बिंदु मानें—अंतिम उत्तर नहीं।', finalBody: 'दिशा चुनने से पहले रोज़ का काम, जरूरी कौशल और वास्तविक सीमाओं की तुलना करें।',
    test: 'टेस्ट दें', jobsAction: 'जॉब्स देखें', join: 'कम्युनिटी से जुड़ें', profile: 'INTJ पर्सनैलिटी पेज', compare: 'INTJ और ENFP की तुलना करें',
    useful: 'उपयोगी ताकत', build: 'बनाएं', watch: 'ध्यान रखें', type: 'मुख्य काम', independence: 'स्वतंत्रता', collaboration: 'सहयोग', setting: 'परिवेश', skill: 'मुख्य कौशल',
    environmentNote: 'सही परिवेश केवल व्यक्तित्व नहीं, वास्तविक भूमिका, टीम और व्यक्ति पर निर्भर करता है।',
    jobsEmpty: 'अभी कोई मेल खाता सार्वजनिक अवसर सूचीबद्ध नहीं है।', post: 'जॉब पोस्ट करें',
    compassItems: [['गहरा फोकस', 'अक्सर महत्वपूर्ण', 'उत्तर देने से पहले जाँचने की जगह।'], ['संरचित समस्या-समाधान', 'अक्सर महत्वपूर्ण', 'स्पष्ट सीमाएँ जटिलता को संभालने योग्य बना सकती हैं।'], ['स्वतंत्र जिम्मेदारी', 'सहायक', 'जिम्मेदारी साझा निर्णय-संदर्भ के साथ बेहतर है।'], ['रणनीतिक सहयोग', 'भूमिका पर निर्भर', 'तैयार बातचीत योजना को बेहतर बना सकती है।']],
    spectrum: [['स्वतंत्र काम', 'लगातार सहयोग', 'अक्सर सहज: उद्देश्यपूर्ण सहयोग के साथ केंद्रित जिम्मेदारी'], ['वैचारिक सोच', 'तुरंत व्यावहारिक क्रियान्वयन', 'अक्सर सहज: मॉडल को वास्तविक समस्या से जोड़ना'], ['लचीली प्रक्रिया', 'निर्धारित सिस्टम', 'अक्सर सहज: सुधार की जगह वाले स्पष्ट सिस्टम'], ['दीर्घ दृष्टि का काम', 'तेज़ फीडबैक', 'अक्सर सहज: जल्दी फीडबैक के साथ दीर्घ दिशा']],
    formatItems: [['रिमोट', 'सुरक्षित फोकस समय', 'अलगाव या देर से मिलने वाला संदर्भ', 'निर्णय लिखें और नियमित फीडबैक आदत बनाएं।'], ['हाइब्रिड', 'फोकस और उपयोगी आमने-सामने समस्या-समाधान', 'टुकड़ों में बंटा सप्ताह', 'तय करें कि साझा समय में कौन-सा काम होगा।'], ['ऑफिस', 'तेज़ संदर्भ और मेंटरिंग', 'लगातार बाधा', 'कैलेंडर में एकाग्रता के ब्लॉक सुरक्षित रखें।']],
    roadmapItems: [['विशेषज्ञता बनाएं', 'उस समस्या क्षेत्र में गहराई बनाएं जिसे आप सच में समझना चाहते हैं।', 'एक वास्तविक केस स्टडी या छोटा प्रोजेक्ट चुनें।'], ['अपनी सोच समझाएं', 'तर्क पूरा चमकने से पहले भी उपयोगी बनाएं।', 'किसी और के लिए एक पेज की सिफारिश लिखें।'], ['विचार जल्दी जाँचें', 'प्रयास बढ़ने से पहले वास्तविकता को योजना बदलने दें।', 'सिर्फ अंतिम उत्तर नहीं, शुरुआती प्रयोग साझा करें।'], ['लोगों के साथ काम करें', 'प्रभाव के लिए भरोसा, संदर्भ और फॉलो-थ्रू चाहिए।', 'एक हितधारक से पूछें कि योजना उपयोगी कैसे बनेगी।'], ['सिस्टम का नेतृत्व करें', 'दूसरों को जिम्मेदारी, निर्णय और परिणाम स्पष्ट दिखाएं।', 'समयसीमा नहीं, संदर्भ के साथ निर्णय सौंपें।']],
    toolkit: ['डोमेन विशेषज्ञता', 'लेखन', 'हितधारक संवाद', 'प्रयोग', 'जिम्मेदारी सौंपना', 'मेंटोरिंग', 'निर्णय-निर्माण'],
    stageItems: [['छात्र', 'जिज्ञासा और कौशल का प्रमाण बनाएं।', 'कोर्स, प्रोजेक्ट या प्रैक्टिशनर बातचीत आजमाएं।', 'केवल प्रतिष्ठित पद के लिए चुनना।'], ['करियर की शुरुआत', 'सीखें कि वास्तविक टीम में काम कैसे आगे बढ़ता है।', 'दिखने वाले योगदान पर फीडबैक मांगें।', 'काम पूरा होने तक उसे साझा न करना।'], ['करियर बदलने वाले', 'मौजूदा ताकतों को नए डोमेन में समझाएं।', 'एक कम-जोखिम प्रोजेक्ट या शैडोइंग बातचीत करें।', 'लेबल को प्रमाण का विकल्प मानना।'], ['मैनेजर', 'रणनीतिक स्पष्टता को टीम की आदत बनाएं।', 'संदर्भ के साथ जिम्मेदारी दें और जल्दी असहमति आमंत्रित करें।', 'हर जरूरी समस्या अकेले हल करना।'], ['फाउंडर या फ्रीलांसर', 'दीर्घ दृष्टि और तत्काल ग्राहक सीख का संतुलन रखें।', 'एक छोटा मार्केट या यूज़र प्रयोग चलाएं।', 'विचार को उपयोगी चुनौती से बचाना।']],
    checklist: ['क्या रोज़ का काम रुचिकर है?', 'क्या परिवेश मेरी कार्य-शैली के अनुकूल है?', 'क्या मैं जरूरी कौशल बनाऊँगा?', 'क्या यह आर्थिक और जीवन की वास्तविक सीमाओं में फिट है?', 'क्या मैंने इसे छोटे प्रयोग से जाँचा है?'],
    industryItems: [['टेक्नोलॉजी और प्लेटफॉर्म', 'सिस्टम को उपयोगी टूल में बदलें।', 'सॉफ्टवेयर इंजीनियर · सिस्टम्स आर्किटेक्ट', 'तेज़ बदलाव में बार-बार संवाद जरूरी हो सकता है।'], ['रिसर्च और शिक्षा', 'कठिन प्रश्नों को कठोरता से देखें।', 'रिसर्च साइंटिस्ट · लर्निंग डिज़ाइनर', 'फीडबैक चक्र लंबे हो सकते हैं।'], ['फाइनेंस और एनालिटिक्स', 'प्रमाण को निर्णयों में उपयोगी बनाएं।', 'फाइनेंशियल एनालिस्ट · रिस्क विशेषज्ञ', 'व्यावसायिक गति चुनौतीपूर्ण हो सकती है।'], ['हेल्थकेयर सिस्टम्स', 'जटिल देखभाल कार्य के समन्वय को बेहतर बनाएं।', 'हेल्थ सिस्टम्स एनालिस्ट · ऑपरेशंस स्ट्रैटेजिस्ट', 'मानवीय संदर्भ मॉडल जितना ही महत्वपूर्ण है।'], ['कानून और पब्लिक पॉलिसी', 'नियम और दीर्घ परिणामों की जाँच करें।', 'पॉलिसी रिसर्चर · लीगल रिसर्चर', 'प्रभाव के लिए स्पष्ट लेखन चाहिए।'], ['प्रोडक्ट और डिज़ाइन', 'सिस्टम इनसाइट को मानवीय जरूरतों से जोड़ें।', 'UX रिसर्चर · प्रोडक्ट मैनेजर', 'गुणात्मक फीडबैक छोड़ा नहीं जा सकता।']],
  },
};

const GROUPS = {
  en: [['Build systems', [0, 5, 4]], ['Discover patterns', [1, 2, 7]], ['Shape direction', [3, 6, 9]], ['Understand people and systems', [8, 10, 11]]],
  hi: [['सिस्टम बनाएं', [0, 5, 4]], ['पैटर्न खोजें', [1, 2, 7]], ['दिशा दें', [3, 6, 9]], ['लोगों और सिस्टम को समझें', [8, 10, 11]]],
};

const FACTS = {
  en: [
    ['Building software', 'Technical depth', 'Clear writing', 'Collaboration cannot be an afterthought'], ['Working with data', 'Pattern recognition', 'Explain uncertainty', 'Models need real context'], ['Researching questions', 'Methodical curiosity', 'Share work-in-progress', 'Feedback may take time'], ['Shaping products', 'Systems perspective', 'Stakeholder listening', 'Customer evidence matters'], ['Reducing risk', 'Anticipating failure', 'Incident communication', 'Urgency can change the plan'], ['Designing platforms', 'Structural thinking', 'Mentoring', 'Implementation changes the model'], ['Framing choices', 'Strategic synthesis', 'Relationship-building', 'Client pace may be fast'], ['Analysing decisions', 'Evidence discipline', 'Commercial context', 'Constraints are part of the answer'], ['Learning from users', 'Pattern synthesis', 'Qualitative listening', 'Do not skip human nuance'], ['Improving operations', 'Process clarity', 'Change facilitation', 'Adoption needs people'], ['Interpreting policy', 'Rigorous reasoning', 'Accessible writing', 'Influence takes patience'], ['Coordinating care systems', 'System awareness', 'Practical empathy', 'The human story stays central'],
  ],
  hi: [
    ['सॉफ्टवेयर बनाना', 'तकनीकी गहराई', 'स्पष्ट लेखन', 'सहयोग बाद की बात नहीं हो सकता'], ['डेटा के साथ काम', 'पैटर्न पहचान', 'अनिश्चितता समझाना', 'मॉडल को वास्तविक संदर्भ चाहिए'], ['प्रश्नों पर रिसर्च', 'व्यवस्थित जिज्ञासा', 'प्रगति में काम साझा करें', 'फीडबैक में समय लग सकता है'], ['प्रोडक्ट दिशा', 'सिस्टम दृष्टि', 'हितधारक सुनना', 'ग्राहक प्रमाण महत्वपूर्ण है'], ['जोखिम घटाना', 'विफलता का अनुमान', 'घटना संवाद', 'तात्कालिकता योजना बदल सकती है'], ['प्लेटफॉर्म डिज़ाइन', 'संरचनात्मक सोच', 'मेंटोरिंग', 'क्रियान्वयन मॉडल बदल सकता है'], ['विकल्प स्पष्ट करना', 'रणनीतिक सार', 'संबंध-निर्माण', 'क्लाइंट की गति तेज़ हो सकती है'], ['निर्णय विश्लेषण', 'प्रमाण अनुशासन', 'व्यावसायिक संदर्भ', 'सीमाएँ उत्तर का हिस्सा हैं'], ['यूज़र से सीखना', 'पैटर्न सार', 'गुणात्मक सुनना', 'मानवीय बारीकी न छोड़ें'], ['ऑपरेशंस सुधारना', 'प्रक्रिया स्पष्टता', 'बदलाव सुगम बनाना', 'अपनाने के लिए लोग चाहिए'], ['पॉलिसी समझना', 'कठोर तर्क', 'स्पष्ट लेखन', 'प्रभाव में धैर्य लगता है'], ['हेल्थ सिस्टम समन्वय', 'सिस्टम जागरूकता', 'व्यावहारिक सहानुभूति', 'मानवीय कहानी केंद्र में रहे'],
  ],
};

function Heading({ eyebrow, title, body, light = false }) {
  return <div className="max-w-3xl"><p className={`section-kicker ${light ? 'text-brand-sand' : ''}`}>{eyebrow}</p><h2 className={`display-font mt-2 text-3xl sm:text-4xl ${light ? 'text-white' : 'text-brand-ink'}`}>{title}</h2>{body ? <p className={`mt-3 leading-relaxed ${light ? 'text-white/75' : 'text-brand-subtle'}`}>{body}</p> : null}</div>;
}

export default async function IntjCareersPage({ params }) {
  const { locale } = await params;
  if (!isLocale(locale)) notFound();
  const c = COPY[locale];
  const content = INTJ_CAREERS[locale];
  const facts = FACTS[locale];
  const topIndexes = [0, 1, 5, 4, 2];
  const faqSchema = { '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: content.faq.map(([name, text]) => ({ '@type': 'Question', name, acceptedAnswer: { '@type': 'Answer', text } })) };

  return <><JsonLd data={{ '@context': 'https://schema.org', '@graph': [breadcrumbJsonLd(locale, [{ name: 'KalQLater' }, { name: 'INTJ', path: 'personality/intj' }, { name: c.crumb, path: 'personality/intj/careers' }]), faqSchema] }} />
    <main className="mx-auto max-w-7xl px-4 py-8 sm:px-6 lg:px-8 lg:py-12">
      <nav aria-label="Breadcrumb" className="text-sm text-brand-subtle"><Link className="hover:text-brand-teal" href={`/${locale}`}>KalQLater</Link><span aria-hidden="true"> / </span><Link className="hover:text-brand-teal" href={localePath(locale, 'personality/intj')}>INTJ</Link><span aria-hidden="true"> / </span>{c.crumb}</nav>

      <header className="relative mt-5 overflow-hidden rounded-[2rem] bg-brand-ink px-6 py-9 text-white shadow-[0_24px_70px_rgba(45,40,37,.2)] sm:px-10 sm:py-12">
        <div className="relative grid items-center gap-10 lg:grid-cols-[1.1fr_.9fr]"><div><p className="section-kicker text-brand-sand">{c.eyebrow}</p><h1 className="display-font mt-3 max-w-xl text-4xl leading-[1.02] sm:text-6xl">{c.title}</h1><p className="mt-5 max-w-xl text-lg leading-relaxed text-white/80">{c.hero}</p><p className="mt-5 max-w-xl border-l-2 border-brand-sand pl-4 text-sm leading-relaxed text-white/70">{c.disclaimer}</p><div className="mt-7 flex flex-wrap gap-3"><a href="#top-careers" className="button-light">{c.top}</a><a href={productionAppUrl('/test')} className="button-dark-outline">{c.test}</a><Link href={localePath(locale, 'personality/intj')} className="text-sm font-semibold text-brand-sand underline underline-offset-4">{c.profile}</Link></div></div><CareerHeroVisual /></div>
      </header>

      <section id="top-careers" className="mt-12 scroll-mt-6"><Heading eyebrow="01" title={c.top} /><div className="mt-6 grid gap-4 lg:grid-cols-[1.25fr_.75fr_.75fr]"><FeaturedCareer index={topIndexes[0]} career={content.careers[topIndexes[0]]} facts={facts[topIndexes[0]]} c={c} large />{topIndexes.slice(1).map((index) => <FeaturedCareer key={index} index={index} career={content.careers[index]} facts={facts[index]} c={c} />)}</div><a href="#career-explorer" className="mt-5 inline-flex items-center gap-2 font-semibold text-brand-teal underline underline-offset-4">{c.all}<span aria-hidden="true">↓</span></a></section>

      <section className="mt-14 grid gap-8 lg:grid-cols-[.85fr_1.15fr]"><div className="rounded-[2rem] bg-brand-cream p-7 sm:p-9"><Heading eyebrow="02" title={c.compass} body={c.compassNote} /><p className="mt-6 text-sm leading-relaxed text-brand-ink">{locale === 'hi' ? 'यह कंपास संभावित कार्य-शैली संकेत देता है। भूमिका और टीम के अनुसार अनुभव अलग हो सकता है।' : 'This compass offers possible working-style signals. The experience will vary by role and team.'}</p></div><div className="relative grid gap-3 rounded-[2rem] border border-brand-line bg-white p-5 sm:grid-cols-2 sm:p-7"><div aria-hidden="true" className="pointer-events-none absolute left-1/2 top-1/2 hidden h-20 w-20 -translate-x-1/2 -translate-y-1/2 rounded-full border-[10px] border-brand-sand/40 bg-brand-teal/10 sm:block" />{c.compassItems.map(([title, label, description], index) => <article key={title} className={`relative rounded-2xl p-5 ${index % 2 === 0 ? 'bg-brand-teal/5' : 'bg-brand-sand/25'}`}><CompassIcon index={index} /><p className="mt-4 text-xs font-bold uppercase tracking-[.14em] text-brand-teal">{label}</p><h3 className="mt-1 font-semibold text-brand-ink">{title}</h3><p className="mt-2 text-sm leading-relaxed text-brand-subtle">{description}</p></article>)}</div></section>

      <section id="career-explorer" className="mt-14 scroll-mt-6"><Heading eyebrow="03" title={c.explorer} body={locale === 'hi' ? 'पदों की लंबी सूची के बजाय, उस तरह के योगदान से शुरुआत करें जो आपको आकर्षित करता है।' : 'Start with the kind of contribution that draws you in, rather than a long list of titles.'} /><div className="mt-7 grid gap-5 lg:grid-cols-2">{GROUPS[locale].map(([group, indexes], groupIndex) => <section key={group} className={`rounded-[2rem] p-6 sm:p-7 ${groupIndex % 2 === 0 ? 'bg-brand-cream/80' : 'border border-brand-line bg-white'}`}><h3 className="section-kicker">{group}</h3><div className="mt-5 space-y-3">{indexes.map((index) => <ExplorerCareer key={index} index={index} career={content.careers[index]} facts={facts[index]} c={c} />)}</div></section>)}</div></section>

      <section className="mt-14"><Heading eyebrow="04" title={c.comparison} /><div className="mt-6 grid gap-4 md:hidden">{topIndexes.map((index) => <ComparisonCard key={index} career={content.careers[index]} facts={facts[index]} c={c} />)}</div><div className="mt-6 hidden overflow-hidden rounded-3xl border border-brand-line bg-white md:block"><table className="w-full text-left text-sm"><caption className="sr-only">{c.comparison}</caption><thead className="bg-brand-cream"><tr>{[c.type, c.independence, c.collaboration, c.setting, c.skill].map((label) => <th key={label} scope="col" className="p-4 font-semibold text-brand-ink">{label}</th>)}</tr></thead><tbody>{topIndexes.map((index) => <tr key={index} className="border-t border-brand-line"><th scope="row" className="p-4 font-semibold text-brand-ink">{content.careers[index][0]}</th><td className="p-4 text-brand-subtle">{index === 3 ? (locale === 'hi' ? 'साझा' : 'Shared') : (locale === 'hi' ? 'अक्सर स्वतंत्र' : 'Often independent')}</td><td className="p-4 text-brand-subtle">{index === 0 || index === 4 ? (locale === 'hi' ? 'उद्देश्यपूर्ण' : 'Purposeful') : (locale === 'hi' ? 'नियमित' : 'Regular')}</td><td className="p-4 text-brand-subtle">{facts[index][0]}</td><td className="p-4 text-brand-subtle">{facts[index][2]}</td></tr>)}</tbody></table></div></section>

      <section className="mt-14 rounded-[2rem] bg-brand-teal p-7 text-white sm:p-10"><Heading eyebrow="05" title={c.environment} body={c.environmentNote} light /><div className="mt-7 space-y-4">{c.spectrum.map(([left, right, zone]) => <div key={left} className="grid gap-2 sm:grid-cols-[1fr_2fr_1fr] sm:items-center"><p className="text-sm text-white/75">{left}</p><div className="relative h-12 rounded-full border border-white/20 bg-brand-ink/25"><span aria-hidden="true" className="absolute left-[29%] top-1/2 h-7 w-[42%] -translate-y-1/2 rounded-full bg-brand-sand/80" /><p className="absolute inset-0 grid place-items-center px-3 text-center text-xs font-semibold text-brand-ink">{zone}</p></div><p className="text-sm text-white/75 sm:text-right">{right}</p></div>)}</div></section>

      <section className="mt-14"><Heading eyebrow="06" title={c.formats} /><div className="mt-6 grid gap-4 md:grid-cols-3">{c.formatItems.map(([title, advantage, challenge, habit], index) => <article key={title} className={`rounded-[2rem] p-6 ${index === 0 ? 'bg-brand-cream' : index === 1 ? 'border border-brand-line bg-white' : 'bg-brand-sand/30'}`}><FormatIcon index={index} /><h3 className="display-font mt-5 text-2xl text-brand-ink">{title}</h3><p className="mt-3 text-sm text-brand-subtle"><strong className="text-brand-ink">{locale === 'hi' ? 'फायदा: ' : 'Advantage: '}</strong>{advantage}</p><p className="mt-2 text-sm text-brand-subtle"><strong className="text-brand-ink">{c.watch}: </strong>{challenge}</p><p className="mt-4 border-t border-brand-line pt-4 text-sm font-medium text-brand-teal">{habit}</p></article>)}</div></section>

      <section className="mt-14 rounded-[2rem] bg-brand-ink p-7 text-white sm:p-10"><Heading eyebrow="07" title={c.skills} light /><ol className="mt-8 grid gap-4 lg:grid-cols-5">{c.roadmapItems.map(([title, text, action], index) => <li key={title} className="rounded-2xl bg-white/10 p-5"><span aria-hidden="true" className="grid h-8 w-8 place-items-center rounded-full bg-brand-sand font-semibold text-brand-ink">{index + 1}</span><h3 className="mt-4 font-semibold">{title}</h3><p className="mt-2 text-sm leading-relaxed text-white/70">{text}</p><p className="mt-4 text-sm font-medium text-brand-sand">{action}</p></li>)}</ol><div className="mt-7 flex flex-wrap gap-2">{c.toolkit.map((skill) => <span key={skill} className="rounded-full border border-white/20 px-3 py-1.5 text-sm text-white/80">{skill}</span>)}</div></section>

      <section className="mt-14 grid gap-7 lg:grid-cols-[1.25fr_.75fr]"><div><Heading eyebrow="08" title={c.stages} /><div className="mt-6 grid gap-3">{c.stageItems.map(([stage, focus, test, avoid], index) => <article key={stage} className={`grid gap-4 rounded-2xl p-5 sm:grid-cols-[auto_1fr_1fr_1fr] ${index % 2 === 0 ? 'bg-brand-cream' : 'border border-brand-line bg-white'}`}><StageIcon index={index} /><div><h3 className="font-semibold text-brand-ink">{stage}</h3><p className="mt-1 text-sm text-brand-subtle">{focus}</p></div><p className="text-sm text-brand-subtle"><strong className="text-brand-teal">{locale === 'hi' ? 'जाँचें: ' : 'Test: '}</strong>{test}</p><p className="text-sm text-brand-subtle"><strong className="text-brand-plum">{locale === 'hi' ? 'बचें: ' : 'Avoid: '}</strong>{avoid}</p></article>)}</div></div><aside className="rounded-[2rem] bg-brand-sand/30 p-7"><h2 className="display-font text-3xl text-brand-ink">{locale === 'hi' ? 'पाँच प्रश्न' : 'Five questions'}</h2><ul className="mt-5 space-y-3">{c.checklist.map((item) => <li key={item} className="flex gap-3 text-sm leading-relaxed text-brand-ink"><span aria-hidden="true" className="font-bold text-brand-teal">✓</span>{item}</li>)}</ul></aside></section>

      <section className="mt-14"><Heading eyebrow="09" title={c.industries} /><div className="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{c.industryItems.map(([industry, appeal, roles, challenge], index) => <article key={industry} className="rounded-3xl border border-brand-line bg-white p-6"><IndustryIcon index={index} /><h3 className="display-font mt-4 text-2xl text-brand-ink">{industry}</h3><p className="mt-2 text-sm text-brand-subtle">{appeal}</p><p className="mt-4 text-sm font-medium text-brand-teal">{roles}</p><p className="mt-3 border-t border-brand-line pt-3 text-xs leading-relaxed text-brand-subtle">{challenge}</p></article>)}</div></section>

      <section className="mt-14 grid gap-6 lg:grid-cols-2"><div className="rounded-[2rem] bg-brand-cream p-7 sm:p-9"><Heading eyebrow="10" title={c.jobs} /><p className="mt-5 max-w-md text-lg leading-relaxed text-brand-subtle">{c.jobsEmpty}</p><div className="mt-7 flex flex-wrap gap-3"><a href={productionAppUrl('/community/jobs')} className="button-primary">{c.jobsAction}</a><a href={productionAppUrl('/community/jobs/new')} className="button-secondary">{c.post}</a><a href={productionAppUrl('/community')} className="button-secondary">{c.join}</a></div></div><div className="rounded-[2rem] border border-brand-saffron/30 bg-brand-sand/20 p-7 sm:p-9"><Heading eyebrow="KalQLater" title={c.guide} /><p className="mt-5 leading-relaxed text-brand-ink">{locale === 'hi' ? 'पसंद क्षमता नहीं होती। रुचि, मूल्य, अनुभव और वास्तविक परिवेश करियर संतुष्टि को आकार देते हैं। लोग सुझाई गई दिशाओं के बाहर भी सफल हो सकते हैं और नियोक्ताओं को व्यक्तित्व से भर्ती निर्णय नहीं लेना चाहिए।' : 'Preferences are not abilities. Interests, values, experience and the real work environment shape career satisfaction. People can thrive outside these directions, and employers must not use personality in hiring decisions.'}</p></div></section>

      <section className="mt-14"><Heading eyebrow="11" title={c.faq} /><div className="mt-6 space-y-3">{content.faq.map(([question, answer]) => <details key={question} className="rounded-2xl border border-brand-line bg-white p-5"><summary className="cursor-pointer font-semibold text-brand-ink focus:outline-none focus-visible:ring-2 focus-visible:ring-brand-teal">{question}</summary><p className="mt-4 max-w-3xl leading-relaxed text-brand-subtle">{answer}</p></details>)}</div></section>

      <section className="relative mt-14 overflow-hidden rounded-[2rem] bg-brand-teal px-7 py-10 text-white sm:px-10"><div aria-hidden="true" className="absolute -right-10 -top-10 h-52 w-52 rounded-full border-[18px] border-brand-sand/30" /><div className="relative max-w-3xl"><p className="section-kicker text-brand-sand">KalQLater</p><h2 className="display-font mt-3 text-3xl sm:text-4xl">{c.finalTitle}</h2><p className="mt-4 leading-relaxed text-white/80">{c.finalBody}</p><div className="mt-7 flex flex-wrap gap-3"><a href={productionAppUrl('/test')} className="button-light">{c.test}</a><a href={productionAppUrl('/community/jobs')} className="button-dark-outline">{c.jobsAction}</a><a href={productionAppUrl('/community')} className="button-dark-outline">{c.join}</a><Link href={localePath(locale, 'compare/intj-vs-enfp')} className="button-dark-outline">{c.compare}</Link></div></div></section>
    </main></>;
}

function FeaturedCareer({ index, career, facts, c, large = false }) { return <article className={`rounded-[2rem] border border-brand-line p-6 ${large ? 'row-span-2 bg-brand-ink text-white sm:p-8' : 'bg-white'}`}><CareerIcon index={index} light={large} /><p className={`mt-5 text-xs font-bold uppercase tracking-[.14em] ${large ? 'text-brand-sand' : 'text-brand-teal'}`}>{career[1]}</p><h3 className={`display-font mt-2 ${large ? 'text-3xl' : 'text-2xl'} ${large ? 'text-white' : 'text-brand-ink'}`}>{career[0]}</h3><p className={`mt-3 text-sm leading-relaxed ${large ? 'text-white/75' : 'text-brand-subtle'}`}>{career[2]}</p><dl className="mt-5 grid gap-3 text-sm"><div><dt className={large ? 'text-brand-sand' : 'text-brand-teal'}>{c.build}</dt><dd className="mt-1 font-medium">{facts[2]}</dd></div><div><dt className={large ? 'text-brand-sand' : 'text-brand-teal'}>{c.watch}</dt><dd className={`mt-1 ${large ? 'text-white/70' : 'text-brand-subtle'}`}>{facts[3]}</dd></div></dl></article>; }
function ExplorerCareer({ index, career, facts, c }) { return <article className="grid gap-3 rounded-2xl bg-white p-4 sm:grid-cols-[auto_1fr_auto]"><CareerIcon index={index} /><div><h4 className="font-semibold text-brand-ink">{career[0]}</h4><p className="mt-1 text-sm text-brand-subtle">{career[2]}</p></div><dl className="grid gap-1 text-xs text-brand-subtle sm:text-right"><div><dt className="inline font-semibold text-brand-teal">{c.useful}: </dt><dd className="inline">{facts[1]}</dd></div><div><dt className="inline font-semibold text-brand-teal">{c.build}: </dt><dd className="inline">{facts[2]}</dd></div><div><dt className="inline font-semibold text-brand-plum">{c.watch}: </dt><dd className="inline">{facts[3]}</dd></div></dl></article>; }
function ComparisonCard({ career, facts, c }) { return <article className="rounded-2xl border border-brand-line bg-white p-5"><h3 className="font-semibold text-brand-ink">{career[0]}</h3><dl className="mt-4 grid gap-2 text-sm text-brand-subtle"><div><dt className="inline font-semibold text-brand-teal">{c.type}: </dt><dd className="inline">{facts[0]}</dd></div><div><dt className="inline font-semibold text-brand-teal">{c.skill}: </dt><dd className="inline">{facts[2]}</dd></div><div><dt className="inline font-semibold text-brand-plum">{c.watch}: </dt><dd className="inline">{facts[3]}</dd></div></dl></article>; }
function CareerHeroVisual() { return <svg aria-hidden="true" viewBox="0 0 420 320" className="mx-auto w-full max-w-md"><path d="M210 58v204M86 116l124 72 124-72M86 238l124-50 124 50" fill="none" stroke="rgba(255,255,255,.35)" strokeWidth="2"/><circle cx="210" cy="160" r="55" fill="#E8B99A"/><circle cx="210" cy="160" r="31" fill="#1F6C7D"/><rect x="35" y="78" width="102" height="72" rx="14" fill="rgba(255,255,255,.12)"/><path d="M54 126h18l11-25 16 35 12-18h13" fill="none" stroke="#E8B99A" strokeWidth="5" strokeLinecap="round"/><rect x="283" y="78" width="102" height="72" rx="14" fill="rgba(255,255,255,.12)"/><path d="M306 129l19-19 15 12 22-25" fill="none" stroke="#E8B99A" strokeWidth="5" strokeLinecap="round"/><rect x="35" y="204" width="102" height="72" rx="14" fill="rgba(255,255,255,.12)"/><path d="M55 224h62M55 241h42M55 258h54" stroke="#E8B99A" strokeWidth="5" strokeLinecap="round"/><rect x="283" y="204" width="102" height="72" rx="14" fill="rgba(255,255,255,.12)"/><circle cx="314" cy="239" r="11" fill="none" stroke="#E8B99A" strokeWidth="5"/><path d="M331 255l22 12" stroke="#E8B99A" strokeWidth="5" strokeLinecap="round"/></svg>; }
function CareerIcon({ index, light = false }) { const paths = ['M4 18 12 4l8 14-8 4-8-4Z','M4 20h16M6 16l3-5 3 3 4-7 2 9','M5 5h14v14H5zM8 9h8M8 13h5','M5 20 12 4l7 16M8 14h8','M4 8h16M4 16h16M8 4v16M16 4v16','M4 18 9 6l5 7 6-9','M5 5h14v14H5zM8 15l3-4 3 2 3-5','M5 12a7 7 0 0 1 14 0c0 5-7 8-7 8s-7-3-7-8Z','M4 6h16v12H4zM8 10h8M8 14h5','M6 19V5h12v14M9 9h6M9 13h6','M5 6h14v12H5zM8 10h8M8 14h4','M5 5h14v14H5zM8 9h8M8 13h8']; return <svg aria-hidden="true" viewBox="0 0 24 24" className={`h-9 w-9 fill-none stroke-current stroke-2 ${light ? 'text-brand-sand' : 'text-brand-teal'}`}><path d={paths[index % paths.length]} strokeLinecap="round" strokeLinejoin="round" /></svg>; }
function CompassIcon({ index }) { return <svg aria-hidden="true" viewBox="0 0 24 24" className="h-8 w-8 fill-none stroke-current stroke-2 text-brand-teal"><path d={['M12 3v18M3 12h18','M4 17 10 5l4 7 6-5','M5 19V5h14v14M9 9h6','M4 12h16M12 4v16'][index]} strokeLinecap="round" strokeLinejoin="round" /></svg>; }
function FormatIcon({ index }) { return <svg aria-hidden="true" viewBox="0 0 24 24" className="h-10 w-10 fill-none stroke-current stroke-2 text-brand-teal"><path d={['M4 5h16v11H4zM9 20h6','M4 7h16M8 4v6M16 4v6M6 14h12v6H6z','M5 20V5h14v15M9 9h6M9 13h6'][index]} strokeLinecap="round" strokeLinejoin="round" /></svg>; }
function StageIcon({ index }) { return <span aria-hidden="true" className="grid h-9 w-9 place-items-center rounded-full bg-brand-teal/10 text-sm font-bold text-brand-teal">{index + 1}</span>; }
function IndustryIcon({ index }) { return <svg aria-hidden="true" viewBox="0 0 24 24" className="h-9 w-9 fill-none stroke-current stroke-2 text-brand-plum"><path d={['M4 5h16v14H4zM8 9h8M8 13h5','M4 19 10 5l4 7 6-10','M5 19V5h14v14M8 15h8','M5 5h14v14H5zM8 9h8M8 13h6','M6 20V5h12v15M9 9h6M9 13h6','M4 5h16v14H4zM8 9h8M8 13h4'][index]} strokeLinecap="round" strokeLinejoin="round" /></svg>; }
