import Link from 'next/link';
import { JsonLd } from '../JsonLd';
import { TrafficIntentLink } from '../TrafficIntentLink';
import { breadcrumbJsonLd } from '../../lib/metadata';

const environments = [
  ['Autonomy and focus', 'Look for decision space, clear ownership, and enough uninterrupted time for the work itself.'],
  ['Collaboration and feedback', 'Ask how teams share context, resolve disagreement, and make feedback useful rather than constant.'],
  ['Pace and predictability', 'Consider whether you prefer steady operating rhythms, short experiments, or work that changes quickly.'],
];

const stages = [
  ['Starting out', 'Use projects, shadowing, and entry-level work to test what the daily tasks actually feel like.'],
  ['Changing direction', 'Translate existing experience into transferable skills before assuming you need to start over.'],
  ['Growing as a specialist', 'Compare depth, influence, learning runway, and the kind of problems you want to own.'],
  ['Leading others', 'Evaluate people responsibility separately from status, salary, or technical progression.'],
];

export function CareersHub({ guides }) {
  const schema = {
    '@context': 'https://schema.org',
    '@graph': [
      breadcrumbJsonLd('en', [{ name: 'KalQLater' }, { name: 'Careers', path: 'careers' }]),
      { '@type': 'CollectionPage', '@id': 'https://kalqlater.com/en/careers#page', url: 'https://kalqlater.com/en/careers', name: 'Career exploration and guidance', description: 'Explore career direction through work preferences, strengths, skills, environments, and real opportunities.', inLanguage: 'en-IN', mainEntity: { '@type': 'ItemList', itemListElement: guides.map((guide, index) => ({ '@type': 'ListItem', position: index + 1, url: `https://kalqlater.com/en/personality/${guide.code.toLowerCase()}/careers`, name: `${guide.code} career guide` })) } },
    ],
  };
  return <><JsonLd data={schema} /><main className="mx-auto max-w-7xl px-4 py-10 sm:px-6 lg:px-8">
    <nav aria-label="Breadcrumb" className="text-sm text-brand-subtle"><Link href="/en">KalQLater</Link><span aria-hidden="true"> / </span>Careers</nav>
    <header className="mt-5 overflow-hidden rounded-[2rem] bg-brand-ink p-8 text-white sm:p-12"><p className="section-kicker text-brand-sand">Career exploration</p><h1 className="display-font mt-3 max-w-4xl text-5xl sm:text-7xl">Find career direction without reducing yourself to a type.</h1><p className="mt-6 max-w-3xl text-lg leading-relaxed text-white/75">Explore the work you want to do, the environments where you can sustain it, and the skills you want to build. Personality can prompt useful questions, but it never determines suitability or predicts success.</p><div className="mt-8 flex flex-wrap gap-3"><a className="button-light" href="#guides">Explore career guides</a><TrafficIntentLink className="button-dark-outline" href="/en/jobs" locale="en" fromEntity="career-guide:hub" toEntity="jobs:directory">Browse current jobs</TrafficIntentLink></div></header>
    <section className="mt-14 grid gap-6 lg:grid-cols-2"><div className="rounded-[2rem] bg-brand-cream p-8"><p className="section-kicker">A practical approach</p><h2 className="display-font mt-3 text-4xl">Start with evidence from real work.</h2><p className="mt-4 leading-relaxed text-brand-subtle">A useful career direction sits at the intersection of interests, strengths, access, values, skills, responsibilities, and opportunity. Test a direction through a small project, a conversation with someone doing the work, or a close reading of real job descriptions.</p></div><div className="rounded-[2rem] border border-brand-line bg-white p-8"><p className="section-kicker">Use personality carefully</p><h2 className="display-font mt-3 text-4xl">One lens, not a hiring rule.</h2><p className="mt-4 leading-relaxed text-brand-subtle">A personality framework can help you notice preferences around focus, decisions, structure, and collaboration. It cannot measure ability, guarantee satisfaction, or justify screening people for a role.</p></div></section>
    <section className="mt-14"><p className="section-kicker">Work environments</p><h2 className="display-font mt-2 text-4xl">Describe the conditions where you do good work.</h2><div className="mt-6 grid gap-4 md:grid-cols-3">{environments.map(([title, body]) => <article key={title} className="rounded-3xl border border-brand-line bg-white p-6"><h3 className="display-font text-2xl">{title}</h3><p className="mt-3 text-brand-subtle">{body}</p></article>)}</div></section>
    <section className="mt-14 rounded-[2rem] bg-brand-teal p-8 text-white"><p className="section-kicker text-brand-sand">Skills and strengths</p><h2 className="display-font mt-2 text-4xl">Separate what energises you from what you can learn.</h2><p className="mt-4 max-w-4xl text-white/80">Strengths are patterns you can apply; skills are capabilities you can practise. Compare role-specific skills, transferable skills, and the support available to develop them. A gap is information for a learning plan, not proof that a path is closed.</p></section>
    <section className="mt-14"><p className="section-kicker">Career stages</p><h2 className="display-font mt-2 text-4xl">Ask different questions at different moments.</h2><div className="mt-6 grid gap-4 md:grid-cols-2">{stages.map(([title, body], index) => <article key={title} className={`rounded-3xl p-6 ${index % 2 ? 'border border-brand-line bg-white' : 'bg-brand-sand/25'}`}><h3 className="display-font text-2xl">{title}</h3><p className="mt-3 text-brand-subtle">{body}</p></article>)}</div></section>
    <section className="mt-14"><p className="section-kicker">Industries and role families</p><h2 className="display-font mt-2 text-4xl">Explore the work before choosing the label.</h2><p className="mt-4 max-w-4xl text-brand-subtle">The guides below cover directions across technology, research, education, operations, public service, health, finance, communication, design, and community work. The same role title can mean very different daily work across industries, so compare responsibilities, constraints, and team context.</p></section>
    <section id="guides" className="mt-14 scroll-mt-6"><p className="section-kicker">Personality as context</p><h2 className="display-font mt-2 text-4xl">Explore all 16 career guides.</h2><p className="mt-4 max-w-3xl text-brand-subtle">Choose a guide as a structured reflection prompt. Each one explains possible directions, real role demands, work settings, skills, career stages, and questions to test in practice.</p><div className="mt-7 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{guides.map((guide) => <TrafficIntentLink key={guide.code} href={`/en/personality/${guide.code.toLowerCase()}/careers`} locale="en" fromEntity="career-guide:hub" toEntity={`career-guide:${guide.code.toLowerCase()}`} className="rounded-3xl border border-brand-line bg-white p-6 transition hover:-translate-y-1 hover:shadow-lg"><p className="section-kicker">{guide.code}</p><h3 className="display-font mt-2 text-2xl">{guide.code} career guide</h3><p className="mt-3 text-sm text-brand-subtle">Explore work connected with {guide.lens}.</p><span className="mt-5 inline-block font-semibold text-brand-teal">Read the guide →</span></TrafficIntentLink>)}</div></section>
    <section className="mt-14 rounded-[2rem] bg-brand-ink p-8 text-white sm:p-10"><p className="section-kicker text-brand-sand">Current opportunities</p><h2 className="display-font mt-2 text-4xl">Test a direction against real roles.</h2><p className="mt-4 max-w-3xl text-white/75">Search fresh public opportunities, edit or clear any suggested role, and compare the work with your skills and constraints. Browsing does not require a profile or account.</p><TrafficIntentLink className="button-light mt-7" href="/en/jobs" locale="en" fromEntity="career-guide:hub" toEntity="jobs:directory">Explore current opportunities</TrafficIntentLink></section>
  </main></>;
}
