import Link from 'next/link';
import { JsonLd } from '../JsonLd';
import { breadcrumbJsonLd } from '../../lib/metadata';
import { localePath, productionAppUrl } from '../../lib/site';
import { RelatedContent } from '../RelatedContent';
import { schemaLanguage } from '../../lib/locales';
import { TrafficIntentLink } from '../TrafficIntentLink';
import { CareerQuickAnswer } from '../TrafficSprintEnhancements';

const COPY = {
  en: { guide: 'Career Guide', top: 'Start here: directions worth investigating', explorer: 'Career Path Explorer', compare: 'Role comparison', environment: 'Where work may feel sustainable', formats: 'Choose the format, not a stereotype', skills: 'Skills that widen your options', stage: 'Choose by career stage', industries: 'Industries to explore', jobs: 'Current opportunities to explore', faq: 'Questions worth asking', use: 'How to use this guide', final: 'Use personality as a starting point—not the final answer.', test: 'Take the test', browse: 'Browse jobs', explore: 'Explore current roles', join: 'Join the Community', post: 'Post a job', profile: 'View personality profile', insights: 'Communication Insights', groups: ['Build and improve', 'Discover and analyse', 'Shape direction', 'Serve people and systems'], role: 'Role-specific work', demand: 'Real demand', skill: 'Skill to build' },
  hi: { guide: 'करियर गाइड', top: 'यहाँ से शुरू करें: खोजने योग्य दिशाएँ', explorer: 'करियर पथ खोजें', compare: 'भूमिका तुलना', environment: 'कहाँ काम टिकाऊ लग सकता है', formats: 'फॉर्मेट चुनें, रूढ़ि नहीं', skills: 'ऐसे कौशल जो विकल्प बढ़ाएँ', stage: 'करियर चरण के अनुसार चुनें', industries: 'खोजने योग्य उद्योग', jobs: 'वर्तमान अवसर खोजें', faq: 'सोचने योग्य प्रश्न', use: 'इस गाइड का उपयोग कैसे करें', final: 'व्यक्तित्व को शुरुआती बिंदु मानें—अंतिम उत्तर नहीं।', test: 'टेस्ट दें', browse: 'जॉब्स देखें', explore: 'मौजूदा भूमिकाएँ देखें', join: 'कम्युनिटी से जुड़ें', post: 'जॉब पोस्ट करें', profile: 'पर्सनैलिटी प्रोफाइल देखें', insights: 'कम्युनिकेशन इनसाइट्स', groups: ['बनाएं और बेहतर करें', 'खोजें और विश्लेषण करें', 'दिशा दें', 'लोगों और सिस्टम की सेवा करें'], role: 'भूमिका का वास्तविक काम', demand: 'वास्तविक चुनौती', skill: 'बनाने योग्य कौशल' },
  es: { guide: 'Guía profesional', top: 'Empieza aquí: direcciones para investigar', explorer: 'Explorador de trayectorias', compare: 'Comparación de roles', environment: 'Dónde el trabajo puede ser sostenible', formats: 'Elige el formato, no un estereotipo', skills: 'Habilidades que amplían tus opciones', stage: 'Elige según tu etapa profesional', industries: 'Sectores para explorar', jobs: 'Oportunidades actuales para explorar', faq: 'Preguntas para profundizar', use: 'Cómo usar esta guía', final: 'Usa la personalidad como punto de partida, no como respuesta final.', test: 'Hacer el test', browse: 'Ver oportunidades', explore: 'Explorar puestos actuales', join: 'Unirse a la comunidad', post: 'Publicar una oportunidad', profile: 'Ver perfil de personalidad', insights: 'Perspectivas de Comunicación', groups: ['Construir y mejorar', 'Descubrir y analizar', 'Dar dirección', 'Acompañar a personas y sistemas'], role: 'Trabajo propio del rol', demand: 'Desafío real', skill: 'Habilidad por desarrollar', explorerBody: 'Revisa por separado el trabajo cotidiano, las habilidades necesarias y el desafío real de cada dirección.', environmentBody: 'El entorno adecuado depende del rol, el equipo y la persona, no del tipo.', questions: 'Cinco preguntas', questionItems: ['¿Me interesa el trabajo cotidiano?', '¿Puedo desarrollar las habilidades del rol?', '¿Encajan el equipo y el entorno?', '¿Es asumible el desafío real?', '¿Lo he probado en un experimento pequeño?'], emptyJobs: 'Ahora mismo no hay oportunidades públicas que coincidan.', useBody: 'Las preferencias no son capacidades. El trabajo cotidiano, las habilidades, las oportunidades y las condiciones reales dan forma a la satisfacción profesional.', finalBody: 'Antes de elegir una dirección, compara el trabajo cotidiano, las habilidades necesarias y las condiciones reales.', table: ['Dirección', 'Trabajo principal', 'Desafío real', 'Habilidad'] },
};

export function CareerGuide({ locale, guide }) {
  const c = COPY[locale];
  const es = locale === 'es';
  const groups = [guide.careers.slice(0, 3), guide.careers.slice(3, 6), guide.careers.slice(6, 9), guide.careers.slice(9, 12)];
  const faqSchema = { '@context': 'https://schema.org', '@type': 'FAQPage', inLanguage: schemaLanguage(locale), mainEntity: guide.faq.map(([name, text]) => ({ '@type': 'Question', name, acceptedAnswer: { '@type': 'Answer', text } })) };
  const careersHubAvailable = locale === 'en';
  const jobsHref = `${localePath(locale, 'jobs')}?q=${encodeURIComponent(guide.careers[0])}`;
  return <><JsonLd data={{ '@context': 'https://schema.org', '@graph': [breadcrumbJsonLd(locale, [{ name: 'KalQLater' }, ...(careersHubAvailable ? [{ name: 'Careers', path: 'careers' }] : []), { name: guide.code, path: `personality/${guide.code.toLowerCase()}` }, { name: c.guide, path: `personality/${guide.code.toLowerCase()}/careers` }]), faqSchema] }} />
    <main className="mx-auto max-w-7xl px-4 py-8 sm:px-6 lg:px-8 lg:py-12">
      <nav aria-label={es ? 'Ruta de navegación' : 'Breadcrumb'} className="text-sm text-brand-subtle"><Link href={`/${locale}`}>KalQLater</Link>{careersHubAvailable ? <><span aria-hidden="true"> / </span><Link href={localePath(locale, 'careers')}>Careers</Link></> : null}<span aria-hidden="true"> / </span><Link href={localePath(locale, `personality/${guide.code.toLowerCase()}`)}>{guide.code}</Link><span aria-hidden="true"> / </span>{c.guide}</nav>
      <header className="relative mt-5 overflow-hidden rounded-[2rem] bg-brand-ink px-6 py-9 text-white shadow-[0_24px_70px_rgba(45,40,37,.2)] sm:px-10 sm:py-12"><div className="relative grid items-center gap-8 lg:grid-cols-[1.1fr_.9fr]"><div><p className="section-kicker text-brand-sand">{guide.code} · {c.guide}</p><h1 className="display-font mt-3 text-4xl leading-[1.02] sm:text-6xl">{guide.title}</h1><p className="mt-5 max-w-xl text-lg leading-relaxed text-white/80">{guide.hero}</p><p className="mt-5 max-w-xl border-l-2 border-brand-sand pl-4 text-sm text-white/70">{guide.disclaimer}</p><div className="mt-7 flex flex-wrap gap-3"><a href="#top-careers" className="button-light">{c.top}</a><a href={productionAppUrl('/test')} className="button-dark-outline">{c.test}</a><Link href={localePath(locale, 'insights/communication')} className="button-dark-outline">{c.insights}</Link><Link href={localePath(locale, `personality/${guide.code.toLowerCase()}`)} className="text-sm font-semibold text-brand-sand underline underline-offset-4">{c.profile}</Link></div></div><HeroVisual /></div></header>
      {locale === 'en' ? <CareerQuickAnswer code={guide.code} /> : null}
      <section id="top-careers" className="mt-12 scroll-mt-6"><Section eyebrow="01" title={c.top} body={guide.lens} /><div className="mt-6 grid gap-4 lg:grid-cols-[1.25fr_.75fr_.75fr]">{guide.careers.slice(0, 5).map((career, index) => <CareerCard key={career} career={career} detail={guide.roleDetails[career]} labels={c} large={index === 0} index={index} locale={locale} code={guide.code} />)}</div></section>
      <section id="career-explorer" className="mt-14 scroll-mt-6"><Section eyebrow="02" title={c.explorer} body={es ? c.explorerBody : locale === 'hi' ? 'हर दिशा के रोज़ के काम, कौशल और वास्तविक चुनौती को अलग-अलग जाँचें।' : 'Examine each direction’s day-to-day work, skill demands, and real challenge separately.'} /><div className="mt-7 grid gap-5 lg:grid-cols-2">{groups.map((careers, groupIndex) => <section key={c.groups[groupIndex]} className={`rounded-[2rem] p-6 ${groupIndex % 2 ? 'border border-brand-line bg-white' : 'bg-brand-cream/80'}`}><p className="section-kicker">{c.groups[groupIndex]}</p><div className="mt-5 space-y-3">{careers.map((career, index) => { const detail = guide.roleDetails[career]; return <article key={career} className="grid gap-3 rounded-2xl bg-white p-4 sm:grid-cols-[auto_1fr]"><Icon index={index + groupIndex} /><div><h3 className="font-semibold text-brand-ink">{career}</h3><p className="mt-1 text-sm text-brand-subtle">{detail.reason}</p><p className="mt-2 text-xs text-brand-plum">{detail.demand}</p><p className="mt-1 text-xs font-semibold text-brand-teal">{detail.skill}</p></div></article>; })}</div></section>)}</div></section>
      <section className="mt-14"><Section eyebrow="03" title={c.compare} /><div className="mt-6 grid gap-3 md:hidden">{guide.careers.slice(0, 5).map((career) => <ComparisonCard key={career} career={career} detail={guide.roleDetails[career]} labels={c} />)}</div><div className="mt-6 hidden overflow-hidden rounded-3xl border border-brand-line bg-white md:block"><table className="w-full text-left text-sm"><caption className="sr-only">{c.compare}</caption><thead className="bg-brand-cream"><tr>{(es ? c.table : locale === 'hi' ? ['दिशा', 'मुख्य काम', 'वास्तविक चुनौती', 'कौशल'] : ['Direction', 'Main work', 'Real challenge', 'Skill']).map((x) => <th key={x} scope="col" className="p-4">{x}</th>)}</tr></thead><tbody>{guide.careers.slice(0, 5).map((career) => { const d = guide.roleDetails[career]; return <tr key={career} className="border-t border-brand-line"><th scope="row" className="p-4 text-brand-ink">{career}</th><td className="p-4 text-brand-subtle">{d.reason}</td><td className="p-4 text-brand-subtle">{d.demand}</td><td className="p-4 text-brand-teal">{d.skill}</td></tr>; })}</tbody></table></div></section>
      <section className="mt-14 rounded-[2rem] bg-brand-teal p-7 text-white sm:p-10"><Section eyebrow="04" title={c.environment} body={es ? c.environmentBody : locale === 'hi' ? 'सही परिवेश भूमिका, टीम और व्यक्ति पर निर्भर करता है—टाइप पर नहीं।' : 'The right environment depends on the role, team, and individual—not type alone.'} light /><div className="mt-7 space-y-4">{guide.settings.map(([left, right], index) => <div key={left} className="grid gap-2 sm:grid-cols-[1fr_2fr_1fr] sm:items-center"><span className="text-sm text-white/75">{left}</span><div className="relative h-11 rounded-full border border-white/20 bg-brand-ink/25"><span aria-hidden="true" className={`absolute top-1/2 h-6 w-[42%] -translate-y-1/2 rounded-full bg-brand-sand/80 ${index % 2 ? 'left-[29%]' : 'left-[42%]'}`} /><span className="absolute inset-0 grid place-items-center px-3 text-center text-xs font-semibold text-brand-ink">{guide.lens}</span></div><span className="text-sm text-white/75 sm:text-right">{right}</span></div>)}</div></section>
      <section className="mt-14"><Section eyebrow="05" title={c.formats} /><div className="mt-6 grid gap-4 md:grid-cols-3">{guide.formats.map(([format, detail], index) => <article key={format} className={`rounded-[2rem] p-6 ${index === 0 ? 'bg-brand-cream' : index === 1 ? 'border border-brand-line bg-white' : 'bg-brand-sand/30'}`}><Icon index={index} /><h3 className="display-font mt-4 text-2xl text-brand-ink">{format}</h3><p className="mt-3 text-sm text-brand-subtle">{detail}</p></article>)}</div></section>
      <section className="mt-14 rounded-[2rem] bg-brand-ink p-7 text-white sm:p-10"><Section eyebrow="06" title={c.skills} light /><ol className="mt-7 grid gap-4 lg:grid-cols-5">{guide.skills.map((step, index) => <li key={step} className="rounded-2xl bg-white/10 p-5"><span className="grid h-8 w-8 place-items-center rounded-full bg-brand-sand font-semibold text-brand-ink">{index + 1}</span><p className="mt-4 text-sm text-white/80">{step}</p></li>)}</ol></section>
      <section className="mt-14 grid gap-7 lg:grid-cols-[1.25fr_.75fr]"><div><Section eyebrow="07" title={c.stage} /><div className="mt-6 space-y-3">{guide.stages.map(([stage, detail], index) => <article key={stage} className={`grid gap-3 rounded-2xl p-5 sm:grid-cols-[auto_1fr_2fr] ${index % 2 ? 'border border-brand-line bg-white' : 'bg-brand-cream'}`}><span className="grid h-8 w-8 place-items-center rounded-full bg-brand-teal/10 font-semibold text-brand-teal">{index + 1}</span><h3 className="font-semibold text-brand-ink">{stage}</h3><p className="text-sm text-brand-subtle">{detail}</p></article>)}</div></div><aside className="rounded-[2rem] bg-brand-sand/30 p-7"><h2 className="display-font text-3xl text-brand-ink">{es ? c.questions : locale === 'hi' ? 'पाँच प्रश्न' : 'Five questions'}</h2><ul className="mt-5 space-y-3 text-sm text-brand-ink">{(es ? c.questionItems : locale === 'hi' ? ['क्या रोज़ का काम रुचिकर है?', 'क्या भूमिका के कौशल उपलब्ध हैं?', 'क्या टीम और पर्यावरण उचित हैं?', 'क्या असली चुनौती स्वीकार्य है?', 'क्या इसे छोटे प्रयोग से जाँचा है?'] : ['Does daily work interest me?', 'Can I build the role skills?', 'Does the team and environment fit?', 'Is the real challenge acceptable?', 'Have I tested it through a small experiment?']).map((x) => <li key={x}>✓ {x}</li>)}</ul></aside></section>
      <section className="mt-14"><Section eyebrow="08" title={c.industries} /><div className="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{guide.industries.map(([industry, detail], index) => <article key={industry} className="rounded-3xl border border-brand-line bg-white p-6"><Icon index={index} /><h3 className="display-font mt-4 text-2xl text-brand-ink">{industry}</h3><p className="mt-3 text-sm text-brand-subtle">{detail}</p></article>)}</div></section>
      <section className="mt-14 grid gap-6 lg:grid-cols-2"><div className="rounded-[2rem] bg-brand-cream p-7"><Section eyebrow="09" title={c.jobs} /><p className="mt-5 text-brand-subtle">{es ? c.emptyJobs : locale === 'hi' ? 'अभी कोई मेल खाता सार्वजनिक अवसर सूचीबद्ध नहीं है।' : 'Use this direction as an editable starting point for a live job search—not as an eligibility rule.'}</p><div className="mt-6 flex flex-wrap gap-3"><TrafficIntentLink href={jobsHref} locale={locale} fromEntity={`career-guide:${guide.code.toLowerCase()}`} toEntity="jobs:directory" className="button-primary">{c.browse}: {guide.careers[0]}</TrafficIntentLink><a href={productionAppUrl('/community/jobs/new')} className="button-secondary">{c.post}</a><Link href={localePath(locale, 'community')} className="button-secondary">{c.join}</Link></div></div><div className="rounded-[2rem] bg-brand-sand/25 p-7"><Section eyebrow="KalQLater" title={c.use} /><p className="mt-5 text-brand-ink">{es ? c.useBody : locale === 'hi' ? 'पसंद क्षमता नहीं होती। भूमिका का रोज़ का काम, कौशल, अवसर और वास्तविक सीमाएँ करियर संतुष्टि को आकार देते हैं।' : 'Preferences are not abilities. Daily work, skills, opportunity, and real constraints shape career satisfaction.'}</p><Link href={localePath(locale, 'insights/communication')} className="button-secondary mt-5">{c.insights} <span aria-hidden="true">→</span></Link></div></section>
      <section className="mt-14"><Section eyebrow="10" title={c.faq} /><div className="mt-6 space-y-3">{guide.faq.map(([question, answer]) => <details key={question} className="rounded-2xl border border-brand-line bg-white p-5"><summary className="cursor-pointer font-semibold text-brand-ink focus:outline-none focus-visible:ring-2 focus-visible:ring-brand-teal">{question}</summary><p className="mt-4 max-w-3xl text-brand-subtle">{answer}</p></details>)}</div></section>
      <RelatedContent sourceEntityId={`career-guide:${guide.code.toLowerCase()}`} sourceType="career-guide" locale={locale} mode={es ? 'preview' : 'public'} />
      <section className="mt-14 rounded-[2rem] bg-brand-teal p-8 text-white"><h2 className="display-font text-3xl">{c.final}</h2><p className="mt-4 text-white/80">{es ? c.finalBody : locale === 'hi' ? 'दिशा चुनने से पहले रोज़ का काम, जरूरी कौशल और वास्तविक सीमाओं की तुलना करें।' : 'Compare daily work, required skills, and real constraints before choosing a direction.'}</p><div className="mt-7 flex flex-wrap gap-3"><a href={productionAppUrl('/test')} className="button-light">{c.test}</a>{careersHubAvailable ? <Link href={localePath(locale, 'careers')} className="button-dark-outline">Explore all career guides</Link> : null}<TrafficIntentLink href={jobsHref} locale={locale} fromEntity={`career-guide:${guide.code.toLowerCase()}`} toEntity="jobs:directory" className="button-dark-outline">{c.browse}</TrafficIntentLink><Link href={localePath(locale, 'community')} className="button-dark-outline">{c.join}</Link></div></section>
    </main></>;
}

function Section({ eyebrow, title, body, light = false }) { return <div className="max-w-3xl"><p className={`section-kicker ${light ? 'text-brand-sand' : ''}`}>{eyebrow}</p><h2 className={`display-font mt-2 text-3xl sm:text-4xl ${light ? 'text-white' : 'text-brand-ink'}`}>{title}</h2>{body ? <p className={`mt-3 leading-relaxed ${light ? 'text-white/75' : 'text-brand-subtle'}`}>{body}</p> : null}</div>; }
function CareerCard({ career, detail, labels, large, index, locale, code }) { return <article className={`rounded-[2rem] border border-brand-line p-6 ${large ? 'row-span-2 bg-brand-ink text-white sm:p-8' : 'bg-white'}`}><Icon index={index} light={large} /><p className={`mt-4 text-xs font-bold uppercase tracking-wide ${large ? 'text-brand-sand' : 'text-brand-teal'}`}>{labels.role}</p><h3 className={`display-font mt-2 ${large ? 'text-3xl text-white' : 'text-2xl text-brand-ink'}`}>{career}</h3><p className={`mt-3 text-sm ${large ? 'text-white/75' : 'text-brand-subtle'}`}>{detail.reason}</p><p className={`mt-4 text-xs ${large ? 'text-white/65' : 'text-brand-plum'}`}>{detail.demand}</p><p className={`mt-3 text-sm font-medium ${large ? 'text-brand-sand' : 'text-brand-teal'}`}>{detail.skill}</p><TrafficIntentLink href={`${localePath(locale, 'jobs')}?q=${encodeURIComponent(career)}`} locale={locale} fromEntity={`career-guide:${code.toLowerCase()}`} toEntity="jobs:directory" className={`mt-5 inline-block text-sm font-semibold underline underline-offset-4 ${large ? 'text-brand-sand' : 'text-brand-teal'}`}>{labels.explore} →</TrafficIntentLink></article>; }
function ComparisonCard({ career, detail }) { return <article className="rounded-2xl border border-brand-line bg-white p-5"><h3 className="font-semibold text-brand-ink">{career}</h3><p className="mt-2 text-sm text-brand-subtle">{detail.reason}</p><p className="mt-3 text-xs text-brand-plum">{detail.demand}</p><p className="mt-2 text-sm text-brand-teal">{detail.skill}</p></article>; }
function Icon({ index, light = false }) { const paths = ['M4 18 12 4l8 14-8 4-8-4Z', 'M4 20h16M6 16l3-5 3 3 4-7 2 9', 'M5 5h14v14H5zM8 9h8M8 13h5', 'M5 20 12 4l7 16M8 14h8', 'M4 8h16M4 16h16M8 4v16M16 4v16', 'M4 18 9 6l5 7 6-9']; return <svg aria-hidden="true" viewBox="0 0 24 24" className={`h-9 w-9 fill-none stroke-current stroke-2 ${light ? 'text-brand-sand' : 'text-brand-teal'}`}><path d={paths[index % paths.length]} strokeLinecap="round" strokeLinejoin="round" /></svg>; }
function HeroVisual() { return <svg aria-hidden="true" viewBox="0 0 420 300" className="mx-auto w-full max-w-md"><path d="M210 46v204M70 110l140 76 140-76M70 238l140-52 140 52" fill="none" stroke="rgba(255,255,255,.35)" strokeWidth="2"/><circle cx="210" cy="158" r="54" fill="#E8B99A"/><circle cx="210" cy="158" r="28" fill="#1F6C7D"/><rect x="28" y="70" width="105" height="72" rx="14" fill="rgba(255,255,255,.12)"/><path d="M48 121h18l11-25 16 35 12-18h13" fill="none" stroke="#E8B99A" strokeWidth="5"/><rect x="286" y="70" width="105" height="72" rx="14" fill="rgba(255,255,255,.12)"/><path d="m307 126 18-18 15 12 23-27" fill="none" stroke="#E8B99A" strokeWidth="5"/></svg>; }
